// Nasdaq.NsmEquities.Aggregated.Itch.v2.0 messages as JSON, written without a JSON library.
//
// Generated by CppGenerators — do not edit.

#pragma once

#include "cpp/advanced/nasdaq/nsmequities/aggregated/itch/v2.0/messages/Definitions.hpp"
#include "json/native/Writer.hpp"

namespace nasdaq::nsmequities::aggregated::itch::v2_0::json::native {

namespace itch_aggregated = ::nasdaq::nsmequities::aggregated::itch::v2_0;

// The session dispatches every message the protocol has; these are the ones written, asked
// at compile time so a program instantiates nothing for the rest.
template <typename Message>
inline constexpr bool writes = true;

inline void write(omi::json::native::Writer& writer, const itch_aggregated::system_event_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("SystemEventMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("event_code");
    writer.string(itch_aggregated::event_code::to_string(message.fields.event_code.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_aggregated::stock_directory_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("StockDirectoryMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("market_category");
    writer.string(itch_aggregated::market_category::to_string(message.fields.market_category.get().value()));
    writer.key("financial_status_indicator");
    writer.string(itch_aggregated::financial_status_indicator::to_string(message.fields.financial_status_indicator.get().value()));
    writer.key("round_lot_size");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.round_lot_size.get().value()));
    writer.key("round_lots_only");
    writer.string(itch_aggregated::round_lots_only::to_string(message.fields.round_lots_only.get().value()));
    writer.key("issue_classification");
    writer.string(itch_aggregated::issue_classification::to_string(message.fields.issue_classification.get().value()));
    writer.key("issue_sub_type");
    writer.string(message.fields.issue_sub_type.get_trimmed().value());
    writer.key("authenticity");
    writer.string(itch_aggregated::authenticity::to_string(message.fields.authenticity.get().value()));
    writer.key("short_sale_threshold_indicator");
    writer.string(itch_aggregated::short_sale_threshold_indicator::to_string(message.fields.short_sale_threshold_indicator.get().value()));
    writer.key("ipo_flag");
    writer.string(itch_aggregated::ipo_flag::to_string(message.fields.ipo_flag.get().value()));
    writer.key("luld_reference_price_tier");
    writer.string(itch_aggregated::luld_reference_price_tier::to_string(message.fields.luld_reference_price_tier.get().value()));
    writer.key("etp_flag");
    writer.string(itch_aggregated::etp_flag::to_string(message.fields.etp_flag.get().value()));
    writer.key("etp_leverage_factor");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.etp_leverage_factor.get().value()));
    writer.key("inverse_indicator");
    writer.string(itch_aggregated::inverse_indicator::to_string(message.fields.inverse_indicator.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_aggregated::stock_trading_action_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("StockTradingActionMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("trading_state");
    writer.string(itch_aggregated::trading_state::to_string(message.fields.trading_state.get().value()));
    writer.key("reason");
    writer.string(message.fields.reason.get_trimmed().value());
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_aggregated::reg_sho_short_sale_price_test_restricted_indicator_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("RegShoShortSalePriceTestRestrictedIndicatorMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("reg_sho_action");
    writer.string(itch_aggregated::reg_sho_action::to_string(message.fields.reg_sho_action.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_aggregated::market_participant_position_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("MarketParticipantPositionMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("mpid");
    writer.string(message.fields.mpid.get_trimmed().value());
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("primary_market_maker");
    writer.string(itch_aggregated::primary_market_maker::to_string(message.fields.primary_market_maker.get().value()));
    writer.key("market_maker_mode");
    writer.string(itch_aggregated::market_maker_mode::to_string(message.fields.market_maker_mode.get().value()));
    writer.key("market_participant_state");
    writer.string(itch_aggregated::market_participant_state::to_string(message.fields.market_participant_state.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_aggregated::mwcb_decline_level_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("MwcbDeclineLevelMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("level_1");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.level_1.get().value()), itch_aggregated::level_1::exponent);
    writer.key("level_2");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.level_2.get().value()), itch_aggregated::level_2::exponent);
    writer.key("level_3");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.level_3.get().value()), itch_aggregated::level_3::exponent);
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_aggregated::mwcb_status_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("MwcbStatusMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("breached_level");
    writer.string(itch_aggregated::breached_level::to_string(message.fields.breached_level.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_aggregated::ipo_quoting_period_update_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("IpoQuotingPeriodUpdateMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("ipo_quotation_release_time");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.ipo_quotation_release_time.get().value()));
    writer.key("ipo_quotation_release_qualifier");
    writer.string(itch_aggregated::ipo_quotation_release_qualifier::to_string(message.fields.ipo_quotation_release_qualifier.get().value()));
    writer.key("ipo_price");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.ipo_price.get().value()), itch_aggregated::ipo_price::exponent);
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_aggregated::luld_auction_collar_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("LuldAuctionCollarMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("auction_collar_reference_price");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.auction_collar_reference_price.get().value()), itch_aggregated::auction_collar_reference_price::exponent);
    writer.key("upper_auction_collar_price");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.upper_auction_collar_price.get().value()), itch_aggregated::upper_auction_collar_price::exponent);
    writer.key("lower_auction_collar_price");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.lower_auction_collar_price.get().value()), itch_aggregated::lower_auction_collar_price::exponent);
    writer.key("auction_collar_extension");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.auction_collar_extension.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_aggregated::operational_halt_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("OperationalHaltMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("market_code");
    writer.string(itch_aggregated::market_code::to_string(message.fields.market_code.get().value()));
    writer.key("operational_halt_action");
    writer.string(itch_aggregated::operational_halt_action::to_string(message.fields.operational_halt_action.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_aggregated::price_level_update_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("PriceLevelUpdateMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("market_side");
    writer.string(itch_aggregated::market_side::to_string(message.fields.market_side.get().value()));
    writer.key("participant_shares");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.participant_shares.get().value()));
    writer.key("aggregate_shares");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.aggregate_shares.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("price");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.price.get().value()), itch_aggregated::price::exponent);
    writer.key("mpid");
    writer.string(message.fields.mpid.get_trimmed().value());
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_aggregated::net_order_imbalance_indicator_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("NetOrderImbalanceIndicatorMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("paired_shares");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.paired_shares.get().value()));
    writer.key("imbalance_shares");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.imbalance_shares.get().value()));
    writer.key("imbalance_direction");
    writer.string(itch_aggregated::imbalance_direction::to_string(message.fields.imbalance_direction.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("far_price");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.far_price.get().value()), itch_aggregated::far_price::exponent);
    writer.key("near_price");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.near_price.get().value()), itch_aggregated::near_price::exponent);
    writer.key("current_reference_price");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.current_reference_price.get().value()), itch_aggregated::current_reference_price::exponent);
    writer.key("cross_type");
    writer.string(itch_aggregated::cross_type::to_string(message.fields.cross_type.get().value()));
    writer.key("price_variation_indicator");
    writer.string(itch_aggregated::price_variation_indicator::to_string(message.fields.price_variation_indicator.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_aggregated::retail_price_improvement_indicator_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("RetailPriceImprovementIndicatorMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("interest_flag");
    writer.string(itch_aggregated::interest_flag::to_string(message.fields.interest_flag.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_aggregated::direct_listing_with_capital_raise_price_discovery_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("DirectListingWithCapitalRaisePriceDiscoveryMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("open_eligibility_status");
    writer.string(itch_aggregated::open_eligibility_status::to_string(message.fields.open_eligibility_status.get().value()));
    writer.key("minimum_allowable_price");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.minimum_allowable_price.get().value()), itch_aggregated::minimum_allowable_price::exponent);
    writer.key("maximum_allowable_price");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.maximum_allowable_price.get().value()), itch_aggregated::maximum_allowable_price::exponent);
    writer.key("near_execution_price");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.near_execution_price.get().value()), itch_aggregated::near_execution_price::exponent);
    writer.key("near_execution_time");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.near_execution_time.get().value()));
    writer.key("lower_price_range_collar");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.lower_price_range_collar.get().value()), itch_aggregated::lower_price_range_collar::exponent);
    writer.key("upper_price_range_collar");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.upper_price_range_collar.get().value()), itch_aggregated::upper_price_range_collar::exponent);
    writer.end_object();
}

}
