// Iex.IexEquities.Tops.IexTp.v1.56 messages as JSON, written without a JSON library.
//
// Generated by CppGenerators — do not edit.

#pragma once

#include "cpp/advanced/iex/iexequities/tops/iextp/v1.56/messages/Definitions.hpp"
#include "json/native/Writer.hpp"

namespace iex::iexequities::tops::iextp::v1_56::json::native {

namespace iextp_tops = ::iex::iexequities::tops::iextp::v1_56;

// The session dispatches every message the protocol has; these are the ones written, asked
// at compile time so a program instantiates nothing for the rest.
template <typename Message>
inline constexpr bool writes = true;

inline void write(omi::json::native::Writer& writer, const iextp_tops::quote_update_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("QuoteUpdateMessage");
    writer.key("quote_update_flags");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.quote_update_flags.get().value()));
    writer.key("timestamp");
    writer.signed_integer(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.key("symbol");
    writer.string(message.fields.symbol.get_trimmed().value());
    writer.key("bid_size");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.bid_size.get().value()));
    writer.key("bid_price");
    writer.decimal(static_cast<std::int64_t>(message.fields.bid_price.get().value()), iextp_tops::bid_price::exponent);
    writer.key("ask_price");
    writer.decimal(static_cast<std::int64_t>(message.fields.ask_price.get().value()), iextp_tops::ask_price::exponent);
    writer.key("ask_size");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.ask_size.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const iextp_tops::trade_report_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("TradeReportMessage");
    writer.key("sale_condition_flags");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.sale_condition_flags.get().value()));
    writer.key("timestamp");
    writer.signed_integer(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.key("symbol");
    writer.string(message.fields.symbol.get_trimmed().value());
    writer.key("size");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.size.get().value()));
    writer.key("price");
    writer.decimal(static_cast<std::int64_t>(message.fields.price.get().value()), iextp_tops::price::exponent);
    writer.key("trade_id");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.trade_id.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const iextp_tops::trade_break_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("TradeBreakMessage");
    writer.key("sale_condition_flags");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.sale_condition_flags.get().value()));
    writer.key("timestamp");
    writer.signed_integer(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.key("symbol");
    writer.string(message.fields.symbol.get_trimmed().value());
    writer.key("size");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.size.get().value()));
    writer.key("price");
    writer.decimal(static_cast<std::int64_t>(message.fields.price.get().value()), iextp_tops::price::exponent);
    writer.key("trade_id");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.trade_id.get().value()));
    writer.end_object();
}

}
