// Iex.IexEquities.Deep.IexTp.v1.08 messages as one wide Parquet table.
//
// Generated by CppGenerators — do not edit.

#pragma once

#include "cpp/advanced/iex/iexequities/deep/iextp/v1.08/messages/Definitions.hpp"
#include "parquet/wide/Table.hpp"

namespace iex::iexequities::deep::iextp::v1_08::parquet::wide {

namespace iextp_deep = ::iex::iexequities::deep::iextp::v1_08;

// The session dispatches every message the protocol has; these are the ones written, asked
// at compile time so a program instantiates nothing for the rest.
template <typename Message>
inline constexpr bool writes = true;

// Every column any message of this protocol holds, the message's own name first.
inline std::shared_ptr<arrow::Schema> schema() {
    return arrow::schema({
        arrow::field("message", arrow::utf8()),
        arrow::field("system_event", arrow::utf8()),
        arrow::field("timestamp", arrow::int64()),
        arrow::field("security_directory_flags", arrow::uint64()),
        arrow::field("symbol", arrow::utf8()),
        arrow::field("round_lot_size", arrow::uint64()),
        arrow::field("adjusted_poc_price", arrow::decimal128(18, 4)),
        arrow::field("luld_tier", arrow::utf8()),
        arrow::field("trading_status", arrow::utf8()),
        arrow::field("reason", arrow::utf8()),
        arrow::field("retail_liquidity_indicator", arrow::utf8()),
        arrow::field("operational_halt_status", arrow::utf8()),
        arrow::field("short_sale_price_test_status", arrow::utf8()),
        arrow::field("detail", arrow::utf8()),
        arrow::field("security_event", arrow::utf8()),
        arrow::field("event_flags", arrow::utf8()),
        arrow::field("size", arrow::uint64()),
        arrow::field("price", arrow::decimal128(18, 4)),
        arrow::field("sale_condition_flags", arrow::uint64()),
        arrow::field("trade_id", arrow::uint64()),
        arrow::field("price_type", arrow::utf8()),
        arrow::field("official_price", arrow::decimal128(18, 4)),
        arrow::field("auction_type", arrow::utf8()),
        arrow::field("paired_shares", arrow::uint64()),
        arrow::field("reference_price", arrow::decimal128(18, 4)),
        arrow::field("indicative_clearing_price", arrow::decimal128(18, 4)),
        arrow::field("imbalance_shares", arrow::uint64()),
        arrow::field("imbalance_side", arrow::utf8()),
        arrow::field("extension_number", arrow::utf8()),
        arrow::field("scheduled_auction_time", arrow::uint64()),
        arrow::field("auction_book_clearing_price", arrow::decimal128(18, 4)),
        arrow::field("collar_reference_price", arrow::decimal128(18, 4)),
        arrow::field("lower_auction_collar", arrow::decimal128(18, 4)),
        arrow::field("upper_auction_collar", arrow::decimal128(18, 4)),
    });
}

// One table of every message read, written out as Parquet when it is finished.
class Table {
  public:
    Table()
      : schema_{ schema() } {}

    void append(const iextp_deep::system_event_message& message) {
        message_.append("SystemEventMessage");
        column_0_.append(iextp_deep::system_event::to_string(message.fields.system_event.get().value()));
        column_1_.append(message.fields.timestamp.get().value());
        column_2_.null();
        column_3_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        ++rows_;
    }

    void append(const iextp_deep::security_directory_message& message) {
        message_.append("SecurityDirectoryMessage");
        column_2_.append(message.fields.security_directory_flags.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.symbol.get_trimmed().value());
        column_4_.append(message.fields.round_lot_size.get().value());
        column_5_.append(message.fields.adjusted_poc_price.get().value());
        column_6_.append(iextp_deep::luld_tier::to_string(message.fields.luld_tier.get().value()));
        column_0_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        ++rows_;
    }

    void append(const iextp_deep::trading_status_message& message) {
        message_.append("TradingStatusMessage");
        column_7_.append(iextp_deep::trading_status::to_string(message.fields.trading_status.get().value()));
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.symbol.get_trimmed().value());
        column_8_.append(message.fields.reason.get_trimmed().value());
        column_0_.null();
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        ++rows_;
    }

    void append(const iextp_deep::retail_liquidity_indicator_message& message) {
        message_.append("RetailLiquidityIndicatorMessage");
        column_9_.append(iextp_deep::retail_liquidity_indicator::to_string(message.fields.retail_liquidity_indicator.get().value()));
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.symbol.get_trimmed().value());
        column_0_.null();
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        ++rows_;
    }

    void append(const iextp_deep::operational_halt_status_message& message) {
        message_.append("OperationalHaltStatusMessage");
        column_10_.append(iextp_deep::operational_halt_status::to_string(message.fields.operational_halt_status.get().value()));
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.symbol.get_trimmed().value());
        column_0_.null();
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        ++rows_;
    }

    void append(const iextp_deep::short_sale_price_test_status_message& message) {
        message_.append("ShortSalePriceTestStatusMessage");
        column_11_.append(iextp_deep::short_sale_price_test_status::to_string(message.fields.short_sale_price_test_status.get().value()));
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.symbol.get_trimmed().value());
        column_12_.append(iextp_deep::detail::to_string(message.fields.detail.get().value()));
        column_0_.null();
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        ++rows_;
    }

    void append(const iextp_deep::security_event_message& message) {
        message_.append("SecurityEventMessage");
        column_13_.append(iextp_deep::security_event::to_string(message.fields.security_event.get().value()));
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.symbol.get_trimmed().value());
        column_0_.null();
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        ++rows_;
    }

    void append(const iextp_deep::price_level_buy_update_message& message) {
        message_.append("PriceLevelBuyUpdateMessage");
        column_14_.append(iextp_deep::event_flags::to_string(message.fields.event_flags.get().value()));
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.symbol.get_trimmed().value());
        column_15_.append(message.fields.size.get().value());
        column_16_.append(message.fields.price.get().value());
        column_0_.null();
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        ++rows_;
    }

    void append(const iextp_deep::price_level_sell_update_message& message) {
        message_.append("PriceLevelSellUpdateMessage");
        column_14_.append(iextp_deep::event_flags::to_string(message.fields.event_flags.get().value()));
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.symbol.get_trimmed().value());
        column_15_.append(message.fields.size.get().value());
        column_16_.append(message.fields.price.get().value());
        column_0_.null();
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        ++rows_;
    }

    void append(const iextp_deep::trade_report_message& message) {
        message_.append("TradeReportMessage");
        column_17_.append(message.fields.sale_condition_flags.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.symbol.get_trimmed().value());
        column_15_.append(message.fields.size.get().value());
        column_16_.append(message.fields.price.get().value());
        column_18_.append(message.fields.trade_id.get().value());
        column_0_.null();
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        ++rows_;
    }

    void append(const iextp_deep::official_price_message& message) {
        message_.append("OfficialPriceMessage");
        column_19_.append(iextp_deep::price_type::to_string(message.fields.price_type.get().value()));
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.symbol.get_trimmed().value());
        column_20_.append(message.fields.official_price.get().value());
        column_0_.null();
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        ++rows_;
    }

    void append(const iextp_deep::trade_break_message& message) {
        message_.append("TradeBreakMessage");
        column_17_.append(message.fields.sale_condition_flags.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.symbol.get_trimmed().value());
        column_15_.append(message.fields.size.get().value());
        column_16_.append(message.fields.price.get().value());
        column_18_.append(message.fields.trade_id.get().value());
        column_0_.null();
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        ++rows_;
    }

    void append(const iextp_deep::auction_information_message& message) {
        message_.append("AuctionInformationMessage");
        column_21_.append(iextp_deep::auction_type::to_string(message.fields.auction_type.get().value()));
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.symbol.get_trimmed().value());
        column_22_.append(message.fields.paired_shares.get().value());
        column_23_.append(message.fields.reference_price.get().value());
        column_24_.append(message.fields.indicative_clearing_price.get().value());
        column_25_.append(message.fields.imbalance_shares.get().value());
        column_26_.append(iextp_deep::imbalance_side::to_string(message.fields.imbalance_side.get().value()));
        column_27_.append(message.fields.extension_number.get().value());
        column_28_.append(message.fields.scheduled_auction_time.get().value());
        column_29_.append(message.fields.auction_book_clearing_price.get().value());
        column_30_.append(message.fields.collar_reference_price.get().value());
        column_31_.append(message.fields.lower_auction_collar.get().value());
        column_32_.append(message.fields.upper_auction_collar.get().value());
        column_0_.null();
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        ++rows_;
    }

    // The rows read so far, as an Arrow table
    std::shared_ptr<arrow::Table> finish() {
        std::vector<std::shared_ptr<arrow::Array>> arrays;
        arrays.push_back(message_.finish());
        arrays.push_back(column_0_.finish());
        arrays.push_back(column_1_.finish());
        arrays.push_back(column_2_.finish());
        arrays.push_back(column_3_.finish());
        arrays.push_back(column_4_.finish());
        arrays.push_back(column_5_.finish());
        arrays.push_back(column_6_.finish());
        arrays.push_back(column_7_.finish());
        arrays.push_back(column_8_.finish());
        arrays.push_back(column_9_.finish());
        arrays.push_back(column_10_.finish());
        arrays.push_back(column_11_.finish());
        arrays.push_back(column_12_.finish());
        arrays.push_back(column_13_.finish());
        arrays.push_back(column_14_.finish());
        arrays.push_back(column_15_.finish());
        arrays.push_back(column_16_.finish());
        arrays.push_back(column_17_.finish());
        arrays.push_back(column_18_.finish());
        arrays.push_back(column_19_.finish());
        arrays.push_back(column_20_.finish());
        arrays.push_back(column_21_.finish());
        arrays.push_back(column_22_.finish());
        arrays.push_back(column_23_.finish());
        arrays.push_back(column_24_.finish());
        arrays.push_back(column_25_.finish());
        arrays.push_back(column_26_.finish());
        arrays.push_back(column_27_.finish());
        arrays.push_back(column_28_.finish());
        arrays.push_back(column_29_.finish());
        arrays.push_back(column_30_.finish());
        arrays.push_back(column_31_.finish());
        arrays.push_back(column_32_.finish());
        return arrow::Table::Make(schema_, arrays, rows_);
    }

    std::int64_t rows() const { return rows_; }

  private:
    std::shared_ptr<arrow::Schema> schema_;
    std::int64_t rows_ = 0;
    omi::parquet::wide::Text message_{  };
    omi::parquet::wide::Text column_0_{  };   // system_event
    omi::parquet::wide::Signed column_1_{  };   // timestamp
    omi::parquet::wide::Unsigned column_2_{  };   // security_directory_flags
    omi::parquet::wide::Text column_3_{  };   // symbol
    omi::parquet::wide::Unsigned column_4_{  };   // round_lot_size
    omi::parquet::wide::Decimal column_5_{ arrow::decimal128(18, 4) };   // adjusted_poc_price
    omi::parquet::wide::Text column_6_{  };   // luld_tier
    omi::parquet::wide::Text column_7_{  };   // trading_status
    omi::parquet::wide::Text column_8_{  };   // reason
    omi::parquet::wide::Text column_9_{  };   // retail_liquidity_indicator
    omi::parquet::wide::Text column_10_{  };   // operational_halt_status
    omi::parquet::wide::Text column_11_{  };   // short_sale_price_test_status
    omi::parquet::wide::Text column_12_{  };   // detail
    omi::parquet::wide::Text column_13_{  };   // security_event
    omi::parquet::wide::Text column_14_{  };   // event_flags
    omi::parquet::wide::Unsigned column_15_{  };   // size
    omi::parquet::wide::Decimal column_16_{ arrow::decimal128(18, 4) };   // price
    omi::parquet::wide::Unsigned column_17_{  };   // sale_condition_flags
    omi::parquet::wide::Unsigned column_18_{  };   // trade_id
    omi::parquet::wide::Text column_19_{  };   // price_type
    omi::parquet::wide::Decimal column_20_{ arrow::decimal128(18, 4) };   // official_price
    omi::parquet::wide::Text column_21_{  };   // auction_type
    omi::parquet::wide::Unsigned column_22_{  };   // paired_shares
    omi::parquet::wide::Decimal column_23_{ arrow::decimal128(18, 4) };   // reference_price
    omi::parquet::wide::Decimal column_24_{ arrow::decimal128(18, 4) };   // indicative_clearing_price
    omi::parquet::wide::Unsigned column_25_{  };   // imbalance_shares
    omi::parquet::wide::Text column_26_{  };   // imbalance_side
    omi::parquet::wide::Text column_27_{  };   // extension_number
    omi::parquet::wide::Unsigned column_28_{  };   // scheduled_auction_time
    omi::parquet::wide::Decimal column_29_{ arrow::decimal128(18, 4) };   // auction_book_clearing_price
    omi::parquet::wide::Decimal column_30_{ arrow::decimal128(18, 4) };   // collar_reference_price
    omi::parquet::wide::Decimal column_31_{ arrow::decimal128(18, 4) };   // lower_auction_collar
    omi::parquet::wide::Decimal column_32_{ arrow::decimal128(18, 4) };   // upper_auction_collar
};

}
