// Nasdaq.NsmEquities.TotalView.Itch.v5.0.2022 messages as JSON, written through RapidJSON.
//
// Generated by CppGenerators — do not edit.

#pragma once

#include "cpp/advanced/nasdaq/nsmequities/totalview/itch/v5.0.2022/messages/Definitions.hpp"
#include "json/rapid/Values.hpp"

namespace nasdaq::nsmequities::totalview::itch::v5_0_2022::json::rapid {

namespace itch_totalview = ::nasdaq::nsmequities::totalview::itch::v5_0_2022;

// The session dispatches every message the protocol has; these are the ones written, asked
// at compile time so a program instantiates nothing for the rest.
template <typename Message>
inline constexpr bool writes = true;

template <typename Writer>
void write(Writer& writer, const itch_totalview::system_event_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("SystemEventMessage");
    writer.Key("stock_locate");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.stock_locate.get().value()));
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("event_code");
    omi::json::rapid::text(writer, itch_totalview::event_code::to_string(message.fields.event_code.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_totalview::stock_directory_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("StockDirectoryMessage");
    writer.Key("stock_locate");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.stock_locate.get().value()));
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("market_category");
    omi::json::rapid::text(writer, itch_totalview::market_category::to_string(message.fields.market_category.get().value()));
    writer.Key("financial_status_indicator");
    omi::json::rapid::text(writer, itch_totalview::financial_status_indicator::to_string(message.fields.financial_status_indicator.get().value()));
    writer.Key("round_lot_size");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.round_lot_size.get().value()));
    writer.Key("round_lots_only");
    omi::json::rapid::text(writer, itch_totalview::round_lots_only::to_string(message.fields.round_lots_only.get().value()));
    writer.Key("issue_classification");
    omi::json::rapid::text(writer, itch_totalview::issue_classification::to_string(message.fields.issue_classification.get().value()));
    writer.Key("issue_sub_type");
    omi::json::rapid::text(writer, message.fields.issue_sub_type.get_trimmed().value());
    writer.Key("authenticity");
    omi::json::rapid::text(writer, itch_totalview::authenticity::to_string(message.fields.authenticity.get().value()));
    writer.Key("short_sale_threshold_indicator");
    omi::json::rapid::text(writer, itch_totalview::short_sale_threshold_indicator::to_string(message.fields.short_sale_threshold_indicator.get().value()));
    writer.Key("ipo_flag");
    omi::json::rapid::text(writer, itch_totalview::ipo_flag::to_string(message.fields.ipo_flag.get().value()));
    writer.Key("luld_reference_price_tier");
    omi::json::rapid::text(writer, itch_totalview::luld_reference_price_tier::to_string(message.fields.luld_reference_price_tier.get().value()));
    writer.Key("etp_flag");
    omi::json::rapid::text(writer, itch_totalview::etp_flag::to_string(message.fields.etp_flag.get().value()));
    writer.Key("etp_leverage_factor");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.etp_leverage_factor.get().value()));
    writer.Key("inverse_indicator");
    omi::json::rapid::text(writer, itch_totalview::inverse_indicator::to_string(message.fields.inverse_indicator.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_totalview::stock_trading_action_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("StockTradingActionMessage");
    writer.Key("stock_locate");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.stock_locate.get().value()));
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("trading_state");
    omi::json::rapid::text(writer, itch_totalview::trading_state::to_string(message.fields.trading_state.get().value()));
    writer.Key("reason_code");
    omi::json::rapid::text(writer, message.fields.reason_code.get_trimmed().value());
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_totalview::reg_sho_short_sale_price_test_restricted_indicator_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("RegShoShortSalePriceTestRestrictedIndicatorMessage");
    writer.Key("locate_code");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.locate_code.get().value()));
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("reg_sho_action");
    omi::json::rapid::text(writer, itch_totalview::reg_sho_action::to_string(message.fields.reg_sho_action.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_totalview::market_participant_position_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("MarketParticipantPositionMessage");
    writer.Key("stock_locate");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.stock_locate.get().value()));
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("mpid");
    omi::json::rapid::text(writer, message.fields.mpid.get_trimmed().value());
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("primary_market_maker");
    omi::json::rapid::text(writer, itch_totalview::primary_market_maker::to_string(message.fields.primary_market_maker.get().value()));
    writer.Key("market_maker_mode");
    omi::json::rapid::text(writer, itch_totalview::market_maker_mode::to_string(message.fields.market_maker_mode.get().value()));
    writer.Key("market_participant_state");
    omi::json::rapid::text(writer, itch_totalview::market_participant_state::to_string(message.fields.market_participant_state.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_totalview::mwcb_decline_level_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("MwcbDeclineLevelMessage");
    writer.Key("stock_locate");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.stock_locate.get().value()));
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("level_1");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.level_1.get().value()), itch_totalview::level_1::exponent);
    writer.Key("level_2");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.level_2.get().value()), itch_totalview::level_2::exponent);
    writer.Key("level_3");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.level_3.get().value()), itch_totalview::level_3::exponent);
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_totalview::mwcb_status_level_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("MwcbStatusLevelMessage");
    writer.Key("stock_locate");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.stock_locate.get().value()));
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("breached_level");
    omi::json::rapid::text(writer, itch_totalview::breached_level::to_string(message.fields.breached_level.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_totalview::ipo_quoting_period_update& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("IpoQuotingPeriodUpdate");
    writer.Key("stock_locate");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.stock_locate.get().value()));
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("ipo_quotation_release_time");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.ipo_quotation_release_time.get().value()));
    writer.Key("ipo_quotation_release_qualifier");
    omi::json::rapid::text(writer, itch_totalview::ipo_quotation_release_qualifier::to_string(message.fields.ipo_quotation_release_qualifier.get().value()));
    writer.Key("ipo_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.ipo_price.get().value()), itch_totalview::ipo_price::exponent);
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_totalview::luld_auction_collar_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("LuldAuctionCollarMessage");
    writer.Key("stock_locate");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.stock_locate.get().value()));
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("auction_collar_reference_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.auction_collar_reference_price.get().value()), itch_totalview::auction_collar_reference_price::exponent);
    writer.Key("upper_auction_collar_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.upper_auction_collar_price.get().value()), itch_totalview::upper_auction_collar_price::exponent);
    writer.Key("lower_auction_collar_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.lower_auction_collar_price.get().value()), itch_totalview::lower_auction_collar_price::exponent);
    writer.Key("auction_collar_extension");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.auction_collar_extension.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_totalview::operational_halt_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("OperationalHaltMessage");
    writer.Key("stock_locate");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.stock_locate.get().value()));
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("market_code");
    omi::json::rapid::text(writer, itch_totalview::market_code::to_string(message.fields.market_code.get().value()));
    writer.Key("operational_halt_action");
    omi::json::rapid::text(writer, itch_totalview::operational_halt_action::to_string(message.fields.operational_halt_action.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_totalview::add_order_no_mpid_attribution_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("AddOrderNoMpidAttributionMessage");
    writer.Key("stock_locate");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.stock_locate.get().value()));
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("order_reference_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.order_reference_number.get().value()));
    writer.Key("buy_sell_indicator");
    omi::json::rapid::text(writer, itch_totalview::buy_sell_indicator::to_string(message.fields.buy_sell_indicator.get().value()));
    writer.Key("shares");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.shares.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.price.get().value()), itch_totalview::price::exponent);
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_totalview::add_order_with_mpid_attribution_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("AddOrderWithMpidAttributionMessage");
    writer.Key("stock_locate");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.stock_locate.get().value()));
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("order_reference_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.order_reference_number.get().value()));
    writer.Key("buy_sell_indicator");
    omi::json::rapid::text(writer, itch_totalview::buy_sell_indicator::to_string(message.fields.buy_sell_indicator.get().value()));
    writer.Key("shares");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.shares.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.price.get().value()), itch_totalview::price::exponent);
    writer.Key("attribution");
    omi::json::rapid::text(writer, message.fields.attribution.get_trimmed().value());
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_totalview::order_executed_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("OrderExecutedMessage");
    writer.Key("stock_locate");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.stock_locate.get().value()));
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("order_reference_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.order_reference_number.get().value()));
    writer.Key("executed_shares");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.executed_shares.get().value()));
    writer.Key("match_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.match_number.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_totalview::order_executed_with_price_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("OrderExecutedWithPriceMessage");
    writer.Key("stock_locate");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.stock_locate.get().value()));
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("order_reference_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.order_reference_number.get().value()));
    writer.Key("executed_shares");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.executed_shares.get().value()));
    writer.Key("match_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.match_number.get().value()));
    writer.Key("printable");
    omi::json::rapid::text(writer, itch_totalview::printable::to_string(message.fields.printable.get().value()));
    writer.Key("execution_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.execution_price.get().value()), itch_totalview::execution_price::exponent);
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_totalview::order_cancel_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("OrderCancelMessage");
    writer.Key("stock_locate");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.stock_locate.get().value()));
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("order_reference_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.order_reference_number.get().value()));
    writer.Key("canceled_shares");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.canceled_shares.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_totalview::order_delete_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("OrderDeleteMessage");
    writer.Key("stock_locate");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.stock_locate.get().value()));
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("order_reference_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.order_reference_number.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_totalview::order_replace_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("OrderReplaceMessage");
    writer.Key("stock_locate");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.stock_locate.get().value()));
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("original_order_reference_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.original_order_reference_number.get().value()));
    writer.Key("new_order_reference_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.new_order_reference_number.get().value()));
    writer.Key("shares");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.shares.get().value()));
    writer.Key("price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.price.get().value()), itch_totalview::price::exponent);
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_totalview::non_cross_trade_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("NonCrossTradeMessage");
    writer.Key("stock_locate");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.stock_locate.get().value()));
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("order_reference_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.order_reference_number.get().value()));
    writer.Key("buy_sell_indicator");
    omi::json::rapid::text(writer, itch_totalview::buy_sell_indicator::to_string(message.fields.buy_sell_indicator.get().value()));
    writer.Key("shares");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.shares.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.price.get().value()), itch_totalview::price::exponent);
    writer.Key("match_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.match_number.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_totalview::cross_trade_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("CrossTradeMessage");
    writer.Key("stock_locate");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.stock_locate.get().value()));
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("cross_shares");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.cross_shares.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("cross_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.cross_price.get().value()), itch_totalview::cross_price::exponent);
    writer.Key("match_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.match_number.get().value()));
    writer.Key("cross_type");
    omi::json::rapid::text(writer, itch_totalview::cross_type::to_string(message.fields.cross_type.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_totalview::broken_trade_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("BrokenTradeMessage");
    writer.Key("stock_locate");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.stock_locate.get().value()));
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("match_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.match_number.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_totalview::net_order_imbalance_indicator_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("NetOrderImbalanceIndicatorMessage");
    writer.Key("stock_locate");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.stock_locate.get().value()));
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("paired_shares");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.paired_shares.get().value()));
    writer.Key("imbalance_shares");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.imbalance_shares.get().value()));
    writer.Key("imbalance_direction");
    omi::json::rapid::text(writer, itch_totalview::imbalance_direction::to_string(message.fields.imbalance_direction.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("far_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.far_price.get().value()), itch_totalview::far_price::exponent);
    writer.Key("near_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.near_price.get().value()), itch_totalview::near_price::exponent);
    writer.Key("current_reference_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.current_reference_price.get().value()), itch_totalview::current_reference_price::exponent);
    writer.Key("cross_type");
    omi::json::rapid::text(writer, itch_totalview::cross_type::to_string(message.fields.cross_type.get().value()));
    writer.Key("price_variation_indicator");
    omi::json::rapid::text(writer, itch_totalview::price_variation_indicator::to_string(message.fields.price_variation_indicator.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_totalview::retail_price_improvement_indicator_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("RetailPriceImprovementIndicatorMessage");
    writer.Key("stock_locate");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.stock_locate.get().value()));
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("interest_flag");
    omi::json::rapid::text(writer, itch_totalview::interest_flag::to_string(message.fields.interest_flag.get().value()));
    writer.EndObject();
}

}
