// Nasdaq.NsmEquities.NlsPlus.Itch.v4.0 messages as one wide Parquet table.
//
// Generated by CppGenerators — do not edit.

#pragma once

#include "cpp/advanced/nasdaq/nsmequities/nlsplus/itch/v4.0/messages/Definitions.hpp"
#include "parquet/wide/Table.hpp"

namespace nasdaq::nsmequities::nlsplus::itch::v4_0::parquet::wide {

namespace itch_nlsplus = ::nasdaq::nsmequities::nlsplus::itch::v4_0;

// The session dispatches every message the protocol has; these are the ones written, asked
// at compile time so a program instantiates nothing for the rest.
template <typename Message>
inline constexpr bool writes = true;

// Every column any message of this protocol holds, the message's own name first.
inline std::shared_ptr<arrow::Schema> schema() {
    return arrow::schema({
        arrow::field("message", arrow::utf8()),
        arrow::field("tracking_number", arrow::uint64()),
        arrow::field("timestamp", arrow::uint64()),
        arrow::field("event_code", arrow::utf8()),
        arrow::field("client_timestamp", arrow::uint64()),
        arrow::field("originating_market_center_identifier", arrow::utf8()),
        arrow::field("issue_symbol", arrow::utf8()),
        arrow::field("security_class", arrow::utf8()),
        arrow::field("trade_control_number", arrow::utf8()),
        arrow::field("trade_price", arrow::decimal128(18, 4)),
        arrow::field("trade_size", arrow::decimal128(18, 6)),
        arrow::field("sale_condition_modifier", arrow::utf8()),
        arrow::field("consolidated_volume", arrow::decimal128(18, 6)),
        arrow::field("original_trade_control_number", arrow::utf8()),
        arrow::field("original_trade_price", arrow::decimal128(18, 4)),
        arrow::field("original_trade_size", arrow::decimal128(18, 6)),
        arrow::field("original_sale_condition_modifier", arrow::utf8()),
        arrow::field("corrected_trade_control_number", arrow::utf8()),
        arrow::field("corrected_trade_price", arrow::decimal128(18, 4)),
        arrow::field("corrected_trade_size", arrow::decimal128(18, 6)),
        arrow::field("corrected_sale_condition_modifier", arrow::utf8()),
        arrow::field("current_trading_state", arrow::utf8()),
        arrow::field("reason", arrow::utf8()),
        arrow::field("reg_sho_action", arrow::utf8()),
        arrow::field("stock", arrow::utf8()),
        arrow::field("market_category", arrow::utf8()),
        arrow::field("financial_status_indicator", arrow::utf8()),
        arrow::field("round_lot_size", arrow::uint64()),
        arrow::field("round_lots_only", arrow::utf8()),
        arrow::field("issue_classification", arrow::utf8()),
        arrow::field("issue_sub_type", arrow::utf8()),
        arrow::field("authenticity", arrow::utf8()),
        arrow::field("short_sale_threshold_indicator", arrow::utf8()),
        arrow::field("ipo_flag", arrow::utf8()),
        arrow::field("luld_reference_price_tier", arrow::utf8()),
        arrow::field("etp_flag", arrow::utf8()),
        arrow::field("etp_leverage_factor", arrow::uint64()),
        arrow::field("inverse_indicator", arrow::utf8()),
        arrow::field("bloomberg_id", arrow::utf8()),
        arrow::field("adjusted_closing_price", arrow::decimal128(18, 4)),
        arrow::field("consolidated_high_price", arrow::decimal128(18, 4)),
        arrow::field("consolidated_low_price", arrow::decimal128(18, 4)),
        arrow::field("consolidated_closing_price", arrow::decimal128(18, 4)),
        arrow::field("consolidated_open_price", arrow::decimal128(18, 4)),
        arrow::field("reference_for_net_change", arrow::utf8()),
        arrow::field("reference_price", arrow::decimal128(18, 4)),
        arrow::field("level_1", arrow::decimal128(18, 8)),
        arrow::field("level_2", arrow::decimal128(18, 8)),
        arrow::field("level_3", arrow::decimal128(18, 8)),
        arrow::field("breached_level", arrow::utf8()),
        arrow::field("ipo_quotation_release_time", arrow::uint64()),
        arrow::field("ipo_quotation_release_qualifier", arrow::utf8()),
        arrow::field("ipo_price", arrow::decimal128(18, 4)),
        arrow::field("stock_alpha_8", arrow::utf8()),
        arrow::field("market_code", arrow::utf8()),
        arrow::field("operational_halt_action", arrow::utf8()),
    });
}

// One table of every message read, written out as Parquet when it is finished.
class Table {
  public:
    Table()
      : schema_{ schema() } {}

    void append(const itch_nlsplus::system_event_message& message) {
        message_.append("SystemEventMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_2_.append(itch_nlsplus::event_code::to_string(message.fields.event_code.get().value()));
        column_3_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_39_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        ++rows_;
    }

    void append(const itch_nlsplus::trade_report_message& message) {
        message_.append("TradeReportMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.client_timestamp.get().value());
        column_4_.append(itch_nlsplus::originating_market_center_identifier::to_string(message.fields.originating_market_center_identifier.get().value()));
        column_5_.append(message.fields.issue_symbol.get_trimmed().value());
        column_6_.append(itch_nlsplus::security_class::to_string(message.fields.security_class.get().value()));
        column_7_.append(message.fields.trade_control_number.get_trimmed().value());
        column_8_.append(message.fields.trade_price.get().value());
        column_9_.append(message.fields.trade_size.get().value());
        column_10_.append(message.fields.sale_condition_modifier.get_trimmed().value());
        column_11_.append(message.fields.consolidated_volume.get().value());
        column_2_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_39_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        ++rows_;
    }

    void append(const itch_nlsplus::trade_cancel_error_message& message) {
        message_.append("TradeCancelErrorMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.client_timestamp.get().value());
        column_4_.append(itch_nlsplus::originating_market_center_identifier::to_string(message.fields.originating_market_center_identifier.get().value()));
        column_5_.append(message.fields.issue_symbol.get_trimmed().value());
        column_6_.append(itch_nlsplus::security_class::to_string(message.fields.security_class.get().value()));
        column_12_.append(message.fields.original_trade_control_number.get_trimmed().value());
        column_13_.append(message.fields.original_trade_price.get().value());
        column_14_.append(message.fields.original_trade_size.get().value());
        column_15_.append(message.fields.original_sale_condition_modifier.get_trimmed().value());
        column_11_.append(message.fields.consolidated_volume.get().value());
        column_2_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_39_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        ++rows_;
    }

    void append(const itch_nlsplus::trade_correction_message& message) {
        message_.append("TradeCorrectionMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.client_timestamp.get().value());
        column_4_.append(itch_nlsplus::originating_market_center_identifier::to_string(message.fields.originating_market_center_identifier.get().value()));
        column_5_.append(message.fields.issue_symbol.get_trimmed().value());
        column_6_.append(itch_nlsplus::security_class::to_string(message.fields.security_class.get().value()));
        column_12_.append(message.fields.original_trade_control_number.get_trimmed().value());
        column_13_.append(message.fields.original_trade_price.get().value());
        column_14_.append(message.fields.original_trade_size.get().value());
        column_15_.append(message.fields.original_sale_condition_modifier.get_trimmed().value());
        column_16_.append(message.fields.corrected_trade_control_number.get_trimmed().value());
        column_17_.append(message.fields.corrected_trade_price.get().value());
        column_18_.append(message.fields.corrected_trade_size.get().value());
        column_19_.append(message.fields.corrected_sale_condition_modifier.get_trimmed().value());
        column_11_.append(message.fields.consolidated_volume.get().value());
        column_2_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_39_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        ++rows_;
    }

    void append(const itch_nlsplus::stock_trading_action_message& message) {
        message_.append("StockTradingActionMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_5_.append(message.fields.issue_symbol.get_trimmed().value());
        column_6_.append(itch_nlsplus::security_class::to_string(message.fields.security_class.get().value()));
        column_20_.append(itch_nlsplus::current_trading_state::to_string(message.fields.current_trading_state.get().value()));
        column_21_.append(message.fields.reason.get_trimmed().value());
        column_2_.null();
        column_3_.null();
        column_4_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_39_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        ++rows_;
    }

    void append(const itch_nlsplus::reg_sho_short_sale_price_test_restricted_indicator_message& message) {
        message_.append("RegShoShortSalePriceTestRestrictedIndicatorMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_5_.append(message.fields.issue_symbol.get_trimmed().value());
        column_22_.append(itch_nlsplus::reg_sho_action::to_string(message.fields.reg_sho_action.get().value()));
        column_2_.null();
        column_3_.null();
        column_4_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_39_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        ++rows_;
    }

    void append(const itch_nlsplus::stock_directory_message& message) {
        message_.append("StockDirectoryMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_23_.append(message.fields.stock.get_trimmed().value());
        column_24_.append(itch_nlsplus::market_category::to_string(message.fields.market_category.get().value()));
        column_25_.append(itch_nlsplus::financial_status_indicator::to_string(message.fields.financial_status_indicator.get().value()));
        column_26_.append(message.fields.round_lot_size.get().value());
        column_27_.append(itch_nlsplus::round_lots_only::to_string(message.fields.round_lots_only.get().value()));
        column_28_.append(itch_nlsplus::issue_classification::to_string(message.fields.issue_classification.get().value()));
        column_29_.append(message.fields.issue_sub_type.get_trimmed().value());
        column_30_.append(itch_nlsplus::authenticity::to_string(message.fields.authenticity.get().value()));
        column_31_.append(itch_nlsplus::short_sale_threshold_indicator::to_string(message.fields.short_sale_threshold_indicator.get().value()));
        column_32_.append(itch_nlsplus::ipo_flag::to_string(message.fields.ipo_flag.get().value()));
        column_33_.append(itch_nlsplus::luld_reference_price_tier::to_string(message.fields.luld_reference_price_tier.get().value()));
        column_34_.append(itch_nlsplus::etp_flag::to_string(message.fields.etp_flag.get().value()));
        column_35_.append(message.fields.etp_leverage_factor.get().value());
        column_36_.append(itch_nlsplus::inverse_indicator::to_string(message.fields.inverse_indicator.get().value()));
        column_37_.append(message.fields.bloomberg_id.get_trimmed().value());
        column_2_.null();
        column_3_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_38_.null();
        column_39_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        ++rows_;
    }

    void append(const itch_nlsplus::adjusted_closing_price_message& message) {
        message_.append("AdjustedClosingPriceMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_5_.append(message.fields.issue_symbol.get_trimmed().value());
        column_6_.append(itch_nlsplus::security_class::to_string(message.fields.security_class.get().value()));
        column_38_.append(message.fields.adjusted_closing_price.get().value());
        column_2_.null();
        column_3_.null();
        column_4_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_39_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        ++rows_;
    }

    void append(const itch_nlsplus::end_of_day_trade_summary_message& message) {
        message_.append("EndOfDayTradeSummaryMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_5_.append(message.fields.issue_symbol.get_trimmed().value());
        column_6_.append(itch_nlsplus::security_class::to_string(message.fields.security_class.get().value()));
        column_39_.append(message.fields.consolidated_high_price.get().value());
        column_40_.append(message.fields.consolidated_low_price.get().value());
        column_41_.append(message.fields.consolidated_closing_price.get().value());
        column_11_.append(message.fields.consolidated_volume.get().value());
        column_42_.append(message.fields.consolidated_open_price.get().value());
        column_2_.null();
        column_3_.null();
        column_4_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_43_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        ++rows_;
    }

    void append(const itch_nlsplus::ipo_information_message& message) {
        message_.append("IpoInformationMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_5_.append(message.fields.issue_symbol.get_trimmed().value());
        column_6_.append(itch_nlsplus::security_class::to_string(message.fields.security_class.get().value()));
        column_43_.append(itch_nlsplus::reference_for_net_change::to_string(message.fields.reference_for_net_change.get().value()));
        column_44_.append(message.fields.reference_price.get().value());
        column_2_.null();
        column_3_.null();
        column_4_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_39_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        ++rows_;
    }

    void append(const itch_nlsplus::mwcb_decline_level_message& message) {
        message_.append("MwcbDeclineLevelMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_45_.append(message.fields.level_1.get().value());
        column_46_.append(message.fields.level_2.get().value());
        column_47_.append(message.fields.level_3.get().value());
        column_2_.null();
        column_3_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_39_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_44_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        ++rows_;
    }

    void append(const itch_nlsplus::mwcb_status_message& message) {
        message_.append("MwcbStatusMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_48_.append(itch_nlsplus::breached_level::to_string(message.fields.breached_level.get().value()));
        column_2_.null();
        column_3_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_39_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        ++rows_;
    }

    void append(const itch_nlsplus::ipo_quoting_period_update_message& message) {
        message_.append("IpoQuotingPeriodUpdateMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_23_.append(message.fields.stock.get_trimmed().value());
        column_49_.append(message.fields.ipo_quotation_release_time.get().value());
        column_50_.append(itch_nlsplus::ipo_quotation_release_qualifier::to_string(message.fields.ipo_quotation_release_qualifier.get().value()));
        column_51_.append(message.fields.ipo_price.get().value());
        column_2_.null();
        column_3_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_39_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        ++rows_;
    }

    void append(const itch_nlsplus::operational_halt_message& message) {
        message_.append("OperationalHaltMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_52_.append(message.fields.stock_alpha_8.get_trimmed().value());
        column_53_.append(itch_nlsplus::market_code::to_string(message.fields.market_code.get().value()));
        column_54_.append(itch_nlsplus::operational_halt_action::to_string(message.fields.operational_halt_action.get().value()));
        column_2_.null();
        column_3_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_39_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        ++rows_;
    }

    // The rows read so far, as an Arrow table
    std::shared_ptr<arrow::Table> finish() {
        std::vector<std::shared_ptr<arrow::Array>> arrays;
        arrays.push_back(message_.finish());
        arrays.push_back(column_0_.finish());
        arrays.push_back(column_1_.finish());
        arrays.push_back(column_2_.finish());
        arrays.push_back(column_3_.finish());
        arrays.push_back(column_4_.finish());
        arrays.push_back(column_5_.finish());
        arrays.push_back(column_6_.finish());
        arrays.push_back(column_7_.finish());
        arrays.push_back(column_8_.finish());
        arrays.push_back(column_9_.finish());
        arrays.push_back(column_10_.finish());
        arrays.push_back(column_11_.finish());
        arrays.push_back(column_12_.finish());
        arrays.push_back(column_13_.finish());
        arrays.push_back(column_14_.finish());
        arrays.push_back(column_15_.finish());
        arrays.push_back(column_16_.finish());
        arrays.push_back(column_17_.finish());
        arrays.push_back(column_18_.finish());
        arrays.push_back(column_19_.finish());
        arrays.push_back(column_20_.finish());
        arrays.push_back(column_21_.finish());
        arrays.push_back(column_22_.finish());
        arrays.push_back(column_23_.finish());
        arrays.push_back(column_24_.finish());
        arrays.push_back(column_25_.finish());
        arrays.push_back(column_26_.finish());
        arrays.push_back(column_27_.finish());
        arrays.push_back(column_28_.finish());
        arrays.push_back(column_29_.finish());
        arrays.push_back(column_30_.finish());
        arrays.push_back(column_31_.finish());
        arrays.push_back(column_32_.finish());
        arrays.push_back(column_33_.finish());
        arrays.push_back(column_34_.finish());
        arrays.push_back(column_35_.finish());
        arrays.push_back(column_36_.finish());
        arrays.push_back(column_37_.finish());
        arrays.push_back(column_38_.finish());
        arrays.push_back(column_39_.finish());
        arrays.push_back(column_40_.finish());
        arrays.push_back(column_41_.finish());
        arrays.push_back(column_42_.finish());
        arrays.push_back(column_43_.finish());
        arrays.push_back(column_44_.finish());
        arrays.push_back(column_45_.finish());
        arrays.push_back(column_46_.finish());
        arrays.push_back(column_47_.finish());
        arrays.push_back(column_48_.finish());
        arrays.push_back(column_49_.finish());
        arrays.push_back(column_50_.finish());
        arrays.push_back(column_51_.finish());
        arrays.push_back(column_52_.finish());
        arrays.push_back(column_53_.finish());
        arrays.push_back(column_54_.finish());
        return arrow::Table::Make(schema_, arrays, rows_);
    }

    std::int64_t rows() const { return rows_; }

  private:
    std::shared_ptr<arrow::Schema> schema_;
    std::int64_t rows_ = 0;
    omi::parquet::wide::Text message_{  };
    omi::parquet::wide::Unsigned column_0_{  };   // tracking_number
    omi::parquet::wide::Unsigned column_1_{  };   // timestamp
    omi::parquet::wide::Text column_2_{  };   // event_code
    omi::parquet::wide::Unsigned column_3_{  };   // client_timestamp
    omi::parquet::wide::Text column_4_{  };   // originating_market_center_identifier
    omi::parquet::wide::Text column_5_{  };   // issue_symbol
    omi::parquet::wide::Text column_6_{  };   // security_class
    omi::parquet::wide::Text column_7_{  };   // trade_control_number
    omi::parquet::wide::Decimal column_8_{ arrow::decimal128(18, 4) };   // trade_price
    omi::parquet::wide::Decimal column_9_{ arrow::decimal128(18, 6) };   // trade_size
    omi::parquet::wide::Text column_10_{  };   // sale_condition_modifier
    omi::parquet::wide::Decimal column_11_{ arrow::decimal128(18, 6) };   // consolidated_volume
    omi::parquet::wide::Text column_12_{  };   // original_trade_control_number
    omi::parquet::wide::Decimal column_13_{ arrow::decimal128(18, 4) };   // original_trade_price
    omi::parquet::wide::Decimal column_14_{ arrow::decimal128(18, 6) };   // original_trade_size
    omi::parquet::wide::Text column_15_{  };   // original_sale_condition_modifier
    omi::parquet::wide::Text column_16_{  };   // corrected_trade_control_number
    omi::parquet::wide::Decimal column_17_{ arrow::decimal128(18, 4) };   // corrected_trade_price
    omi::parquet::wide::Decimal column_18_{ arrow::decimal128(18, 6) };   // corrected_trade_size
    omi::parquet::wide::Text column_19_{  };   // corrected_sale_condition_modifier
    omi::parquet::wide::Text column_20_{  };   // current_trading_state
    omi::parquet::wide::Text column_21_{  };   // reason
    omi::parquet::wide::Text column_22_{  };   // reg_sho_action
    omi::parquet::wide::Text column_23_{  };   // stock
    omi::parquet::wide::Text column_24_{  };   // market_category
    omi::parquet::wide::Text column_25_{  };   // financial_status_indicator
    omi::parquet::wide::Unsigned column_26_{  };   // round_lot_size
    omi::parquet::wide::Text column_27_{  };   // round_lots_only
    omi::parquet::wide::Text column_28_{  };   // issue_classification
    omi::parquet::wide::Text column_29_{  };   // issue_sub_type
    omi::parquet::wide::Text column_30_{  };   // authenticity
    omi::parquet::wide::Text column_31_{  };   // short_sale_threshold_indicator
    omi::parquet::wide::Text column_32_{  };   // ipo_flag
    omi::parquet::wide::Text column_33_{  };   // luld_reference_price_tier
    omi::parquet::wide::Text column_34_{  };   // etp_flag
    omi::parquet::wide::Unsigned column_35_{  };   // etp_leverage_factor
    omi::parquet::wide::Text column_36_{  };   // inverse_indicator
    omi::parquet::wide::Text column_37_{  };   // bloomberg_id
    omi::parquet::wide::Decimal column_38_{ arrow::decimal128(18, 4) };   // adjusted_closing_price
    omi::parquet::wide::Decimal column_39_{ arrow::decimal128(18, 4) };   // consolidated_high_price
    omi::parquet::wide::Decimal column_40_{ arrow::decimal128(18, 4) };   // consolidated_low_price
    omi::parquet::wide::Decimal column_41_{ arrow::decimal128(18, 4) };   // consolidated_closing_price
    omi::parquet::wide::Decimal column_42_{ arrow::decimal128(18, 4) };   // consolidated_open_price
    omi::parquet::wide::Text column_43_{  };   // reference_for_net_change
    omi::parquet::wide::Decimal column_44_{ arrow::decimal128(18, 4) };   // reference_price
    omi::parquet::wide::Decimal column_45_{ arrow::decimal128(18, 8) };   // level_1
    omi::parquet::wide::Decimal column_46_{ arrow::decimal128(18, 8) };   // level_2
    omi::parquet::wide::Decimal column_47_{ arrow::decimal128(18, 8) };   // level_3
    omi::parquet::wide::Text column_48_{  };   // breached_level
    omi::parquet::wide::Unsigned column_49_{  };   // ipo_quotation_release_time
    omi::parquet::wide::Text column_50_{  };   // ipo_quotation_release_qualifier
    omi::parquet::wide::Decimal column_51_{ arrow::decimal128(18, 4) };   // ipo_price
    omi::parquet::wide::Text column_52_{  };   // stock_alpha_8
    omi::parquet::wide::Text column_53_{  };   // market_code
    omi::parquet::wide::Text column_54_{  };   // operational_halt_action
};

}
