// The column builders every generated table is filled through, and how one is written out.
//
// Generated by CppGenerators — do not edit.

#pragma once

#include <cstdint>
#include <memory>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

#include <arrow/api.h>
#include <arrow/io/file.h>
#include <parquet/arrow/writer.h>

namespace omi::parquet::wide {

// An Arrow call that failed says why, as an exception rather than a status nobody read.
inline void check(const arrow::Status& status, std::string_view what) {
    if (!status.ok()) {
        throw std::runtime_error(std::string{ what } + ": " + status.ToString());
    }
}

// One column of a table. Every column is nullable, because a message that does not hold a value
// leaves it null, and every message of a protocol shares one table.
template <typename Builder, typename Array>
class Column {
  public:
    Column() = default;

    explicit Column(std::shared_ptr<arrow::DataType> type)
      : builder_{ std::move(type), arrow::default_memory_pool() } {}

    void null() {
        check(builder_.AppendNull(), "append null");
    }

    std::shared_ptr<arrow::Array> finish() {
        std::shared_ptr<arrow::Array> array;
        check(builder_.Finish(&array), "finish column");
        return array;
    }

  protected:
    Builder builder_{};
};

// Text: a string, from trimmed ASCII, a character, or an enumeration's value named.
class Text : public Column<arrow::StringBuilder, arrow::StringArray> {
  public:
    using Column::Column;

    void append(std::string_view value) {
        check(builder_.Append(value.data(), static_cast<std::int32_t>(value.size())), "append text");
    }

    void append(char value) {
        check(builder_.Append(&value, 1), "append character");
    }
};

// A signed integer.
class Signed : public Column<arrow::Int64Builder, arrow::Int64Array> {
  public:
    using Column::Column;

    template <typename Value>
    void append(Value value) {
        check(builder_.Append(static_cast<std::int64_t>(value)), "append signed");
    }
};

// An unsigned integer.
class Unsigned : public Column<arrow::UInt64Builder, arrow::UInt64Array> {
  public:
    using Column::Column;

    template <typename Value>
    void append(Value value) {
        check(builder_.Append(static_cast<std::uint64_t>(value)), "append unsigned");
    }
};

// A floating point number.
class Real : public Column<arrow::DoubleBuilder, arrow::DoubleArray> {
  public:
    using Column::Column;

    template <typename Value>
    void append(Value value) {
        check(builder_.Append(static_cast<double>(value)), "append real");
    }
};

// A decimal: the mantissa exactly as the wire carried it, with the point its scale places.
class Decimal : public Column<arrow::Decimal128Builder, arrow::Decimal128Array> {
  public:
    using Column::Column;

    template <typename Value>
    void append(Value value) {
        check(builder_.Append(arrow::Decimal128(static_cast<std::int64_t>(value))), "append decimal");
    }
};

// Write a finished table to a Parquet file.
inline void write(const std::shared_ptr<arrow::Table>& table, const std::string& path) {
    std::shared_ptr<arrow::io::FileOutputStream> file;
    auto opened = arrow::io::FileOutputStream::Open(path);
    check(opened.status(), "open " + path);
    file = *opened;

    check(::parquet::arrow::WriteTable(*table, arrow::default_memory_pool(), file, table->num_rows() > 0 ? table->num_rows() : 1024),
        "write " + path);

    check(file->Close(), "close " + path);
}

}
