// Nasdaq.NsmEquities.Level2.Itch.v2.0 messages as one wide Parquet table.
//
// Generated by CppGenerators — do not edit.

#pragma once

#include "cpp/advanced/nasdaq/nsmequities/level2/itch/v2.0/messages/Definitions.hpp"
#include "parquet/wide/Table.hpp"

namespace nasdaq::nsmequities::level2::itch::v2_0::parquet::wide {

namespace itch_level2 = ::nasdaq::nsmequities::level2::itch::v2_0;

// The session dispatches every message the protocol has; these are the ones written, asked
// at compile time so a program instantiates nothing for the rest.
template <typename Message>
inline constexpr bool writes = true;

// Every column any message of this protocol holds, the message's own name first.
inline std::shared_ptr<arrow::Schema> schema() {
    return arrow::schema({
        arrow::field("message", arrow::utf8()),
        arrow::field("tracking_number", arrow::uint64()),
        arrow::field("timestamp", arrow::uint64()),
        arrow::field("event_code", arrow::utf8()),
        arrow::field("stock", arrow::utf8()),
        arrow::field("market_category", arrow::utf8()),
        arrow::field("financial_status_indicator", arrow::utf8()),
        arrow::field("round_lot_size", arrow::uint64()),
        arrow::field("round_lots_only", arrow::utf8()),
        arrow::field("issue_classification", arrow::utf8()),
        arrow::field("issue_subtype", arrow::utf8()),
        arrow::field("authenticity", arrow::utf8()),
        arrow::field("short_sale_threshold_indicator", arrow::utf8()),
        arrow::field("ipo_flag", arrow::utf8()),
        arrow::field("luld_reference_price_tier", arrow::utf8()),
        arrow::field("etp_flag", arrow::utf8()),
        arrow::field("etp_leverage_factor", arrow::uint64()),
        arrow::field("inverse_indicator", arrow::utf8()),
        arrow::field("current_trading_state", arrow::utf8()),
        arrow::field("reason", arrow::utf8()),
        arrow::field("reg_sho_action", arrow::utf8()),
        arrow::field("mpid", arrow::utf8()),
        arrow::field("primary_market_maker", arrow::utf8()),
        arrow::field("market_maker_mode", arrow::utf8()),
        arrow::field("market_participant_state", arrow::utf8()),
        arrow::field("market_code", arrow::utf8()),
        arrow::field("operational_halt_action", arrow::utf8()),
        arrow::field("market_side", arrow::utf8()),
        arrow::field("participant_shares", arrow::uint64()),
        arrow::field("price", arrow::decimal128(10, 4)),
        arrow::field("interest_flag", arrow::utf8()),
        arrow::field("level_1", arrow::decimal128(18, 8)),
        arrow::field("level_2", arrow::decimal128(18, 8)),
        arrow::field("level_3", arrow::decimal128(18, 8)),
        arrow::field("breached_level", arrow::utf8()),
        arrow::field("ipo_quotation_release_time", arrow::uint64()),
        arrow::field("ipo_quotation_release_qualifier", arrow::utf8()),
        arrow::field("ipo_price", arrow::decimal128(10, 4)),
    });
}

// One table of every message read, written out as Parquet when it is finished.
class Table {
  public:
    Table()
      : schema_{ schema() } {}

    void append(const itch_level2::system_event_message& message) {
        message_.append("SystemEventMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_2_.append(itch_level2::event_code::to_string(message.fields.event_code.get().value()));
        column_3_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        ++rows_;
    }

    void append(const itch_level2::stock_directory_message& message) {
        message_.append("StockDirectoryMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.stock.get_trimmed().value());
        column_4_.append(itch_level2::market_category::to_string(message.fields.market_category.get().value()));
        column_5_.append(itch_level2::financial_status_indicator::to_string(message.fields.financial_status_indicator.get().value()));
        column_6_.append(message.fields.round_lot_size.get().value());
        column_7_.append(itch_level2::round_lots_only::to_string(message.fields.round_lots_only.get().value()));
        column_8_.append(itch_level2::issue_classification::to_string(message.fields.issue_classification.get().value()));
        column_9_.append(message.fields.issue_subtype.get_trimmed().value());
        column_10_.append(itch_level2::authenticity::to_string(message.fields.authenticity.get().value()));
        column_11_.append(itch_level2::short_sale_threshold_indicator::to_string(message.fields.short_sale_threshold_indicator.get().value()));
        column_12_.append(itch_level2::ipo_flag::to_string(message.fields.ipo_flag.get().value()));
        column_13_.append(itch_level2::luld_reference_price_tier::to_string(message.fields.luld_reference_price_tier.get().value()));
        column_14_.append(itch_level2::etp_flag::to_string(message.fields.etp_flag.get().value()));
        column_15_.append(message.fields.etp_leverage_factor.get().value());
        column_16_.append(itch_level2::inverse_indicator::to_string(message.fields.inverse_indicator.get().value()));
        column_2_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        ++rows_;
    }

    void append(const itch_level2::stock_trading_action_message& message) {
        message_.append("StockTradingActionMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.stock.get_trimmed().value());
        column_17_.append(itch_level2::current_trading_state::to_string(message.fields.current_trading_state.get().value()));
        column_18_.append(message.fields.reason.get_trimmed().value());
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        ++rows_;
    }

    void append(const itch_level2::reg_sho_short_sale_price_test_restricted_indicator_message& message) {
        message_.append("RegShoShortSalePriceTestRestrictedIndicatorMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.stock.get_trimmed().value());
        column_19_.append(itch_level2::reg_sho_action::to_string(message.fields.reg_sho_action.get().value()));
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        ++rows_;
    }

    void append(const itch_level2::market_participant_position_message& message) {
        message_.append("MarketParticipantPositionMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_20_.append(message.fields.mpid.get_trimmed().value());
        column_3_.append(message.fields.stock.get_trimmed().value());
        column_21_.append(itch_level2::primary_market_maker::to_string(message.fields.primary_market_maker.get().value()));
        column_22_.append(itch_level2::market_maker_mode::to_string(message.fields.market_maker_mode.get().value()));
        column_23_.append(itch_level2::market_participant_state::to_string(message.fields.market_participant_state.get().value()));
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        ++rows_;
    }

    void append(const itch_level2::operational_halt_message& message) {
        message_.append("OperationalHaltMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.stock.get_trimmed().value());
        column_24_.append(itch_level2::market_code::to_string(message.fields.market_code.get().value()));
        column_25_.append(itch_level2::operational_halt_action::to_string(message.fields.operational_halt_action.get().value()));
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        ++rows_;
    }

    void append(const itch_level2::market_participant_bid_ask_update_message& message) {
        message_.append("MarketParticipantBidAskUpdateMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_26_.append(itch_level2::market_side::to_string(message.fields.market_side.get().value()));
        column_27_.append(message.fields.participant_shares.get().value());
        column_3_.append(message.fields.stock.get_trimmed().value());
        column_28_.append(message.fields.price.get().value());
        column_20_.append(message.fields.mpid.get_trimmed().value());
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        ++rows_;
    }

    void append(const itch_level2::retail_price_interest_indicator_message& message) {
        message_.append("RetailPriceInterestIndicatorMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.stock.get_trimmed().value());
        column_29_.append(itch_level2::interest_flag::to_string(message.fields.interest_flag.get().value()));
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        ++rows_;
    }

    void append(const itch_level2::market_wide_circuit_breaker_decline_level_message& message) {
        message_.append("MarketWideCircuitBreakerDeclineLevelMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_30_.append(message.fields.level_1.get().value());
        column_31_.append(message.fields.level_2.get().value());
        column_32_.append(message.fields.level_3.get().value());
        column_2_.null();
        column_3_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        ++rows_;
    }

    void append(const itch_level2::market_wide_circuit_breaker_status_message& message) {
        message_.append("MarketWideCircuitBreakerStatusMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_33_.append(itch_level2::breached_level::to_string(message.fields.breached_level.get().value()));
        column_2_.null();
        column_3_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        ++rows_;
    }

    void append(const itch_level2::ipo_quoting_period_update_message& message) {
        message_.append("IpoQuotingPeriodUpdateMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.stock.get_trimmed().value());
        column_34_.append(message.fields.ipo_quotation_release_time.get().value());
        column_35_.append(itch_level2::ipo_quotation_release_qualifier::to_string(message.fields.ipo_quotation_release_qualifier.get().value()));
        column_36_.append(message.fields.ipo_price.get().value());
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        ++rows_;
    }

    // The rows read so far, as an Arrow table
    std::shared_ptr<arrow::Table> finish() {
        std::vector<std::shared_ptr<arrow::Array>> arrays;
        arrays.push_back(message_.finish());
        arrays.push_back(column_0_.finish());
        arrays.push_back(column_1_.finish());
        arrays.push_back(column_2_.finish());
        arrays.push_back(column_3_.finish());
        arrays.push_back(column_4_.finish());
        arrays.push_back(column_5_.finish());
        arrays.push_back(column_6_.finish());
        arrays.push_back(column_7_.finish());
        arrays.push_back(column_8_.finish());
        arrays.push_back(column_9_.finish());
        arrays.push_back(column_10_.finish());
        arrays.push_back(column_11_.finish());
        arrays.push_back(column_12_.finish());
        arrays.push_back(column_13_.finish());
        arrays.push_back(column_14_.finish());
        arrays.push_back(column_15_.finish());
        arrays.push_back(column_16_.finish());
        arrays.push_back(column_17_.finish());
        arrays.push_back(column_18_.finish());
        arrays.push_back(column_19_.finish());
        arrays.push_back(column_20_.finish());
        arrays.push_back(column_21_.finish());
        arrays.push_back(column_22_.finish());
        arrays.push_back(column_23_.finish());
        arrays.push_back(column_24_.finish());
        arrays.push_back(column_25_.finish());
        arrays.push_back(column_26_.finish());
        arrays.push_back(column_27_.finish());
        arrays.push_back(column_28_.finish());
        arrays.push_back(column_29_.finish());
        arrays.push_back(column_30_.finish());
        arrays.push_back(column_31_.finish());
        arrays.push_back(column_32_.finish());
        arrays.push_back(column_33_.finish());
        arrays.push_back(column_34_.finish());
        arrays.push_back(column_35_.finish());
        arrays.push_back(column_36_.finish());
        return arrow::Table::Make(schema_, arrays, rows_);
    }

    std::int64_t rows() const { return rows_; }

  private:
    std::shared_ptr<arrow::Schema> schema_;
    std::int64_t rows_ = 0;
    omi::parquet::wide::Text message_{  };
    omi::parquet::wide::Unsigned column_0_{  };   // tracking_number
    omi::parquet::wide::Unsigned column_1_{  };   // timestamp
    omi::parquet::wide::Text column_2_{  };   // event_code
    omi::parquet::wide::Text column_3_{  };   // stock
    omi::parquet::wide::Text column_4_{  };   // market_category
    omi::parquet::wide::Text column_5_{  };   // financial_status_indicator
    omi::parquet::wide::Unsigned column_6_{  };   // round_lot_size
    omi::parquet::wide::Text column_7_{  };   // round_lots_only
    omi::parquet::wide::Text column_8_{  };   // issue_classification
    omi::parquet::wide::Text column_9_{  };   // issue_subtype
    omi::parquet::wide::Text column_10_{  };   // authenticity
    omi::parquet::wide::Text column_11_{  };   // short_sale_threshold_indicator
    omi::parquet::wide::Text column_12_{  };   // ipo_flag
    omi::parquet::wide::Text column_13_{  };   // luld_reference_price_tier
    omi::parquet::wide::Text column_14_{  };   // etp_flag
    omi::parquet::wide::Unsigned column_15_{  };   // etp_leverage_factor
    omi::parquet::wide::Text column_16_{  };   // inverse_indicator
    omi::parquet::wide::Text column_17_{  };   // current_trading_state
    omi::parquet::wide::Text column_18_{  };   // reason
    omi::parquet::wide::Text column_19_{  };   // reg_sho_action
    omi::parquet::wide::Text column_20_{  };   // mpid
    omi::parquet::wide::Text column_21_{  };   // primary_market_maker
    omi::parquet::wide::Text column_22_{  };   // market_maker_mode
    omi::parquet::wide::Text column_23_{  };   // market_participant_state
    omi::parquet::wide::Text column_24_{  };   // market_code
    omi::parquet::wide::Text column_25_{  };   // operational_halt_action
    omi::parquet::wide::Text column_26_{  };   // market_side
    omi::parquet::wide::Unsigned column_27_{  };   // participant_shares
    omi::parquet::wide::Decimal column_28_{ arrow::decimal128(10, 4) };   // price
    omi::parquet::wide::Text column_29_{  };   // interest_flag
    omi::parquet::wide::Decimal column_30_{ arrow::decimal128(18, 8) };   // level_1
    omi::parquet::wide::Decimal column_31_{ arrow::decimal128(18, 8) };   // level_2
    omi::parquet::wide::Decimal column_32_{ arrow::decimal128(18, 8) };   // level_3
    omi::parquet::wide::Text column_33_{  };   // breached_level
    omi::parquet::wide::Unsigned column_34_{  };   // ipo_quotation_release_time
    omi::parquet::wide::Text column_35_{  };   // ipo_quotation_release_qualifier
    omi::parquet::wide::Decimal column_36_{ arrow::decimal128(10, 4) };   // ipo_price
};

}
