// Nasdaq.NsmEquities.Level2.Itch.v2.0 messages as JSON, written without a JSON library.
//
// Generated by CppGenerators — do not edit.

#pragma once

#include "cpp/advanced/nasdaq/nsmequities/level2/itch/v2.0/messages/Definitions.hpp"
#include "json/native/Writer.hpp"

namespace nasdaq::nsmequities::level2::itch::v2_0::json::native {

namespace itch_level2 = ::nasdaq::nsmequities::level2::itch::v2_0;

// The session dispatches every message the protocol has; these are the ones written, asked
// at compile time so a program instantiates nothing for the rest.
template <typename Message>
inline constexpr bool writes = true;

inline void write(omi::json::native::Writer& writer, const itch_level2::system_event_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("SystemEventMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("event_code");
    writer.string(itch_level2::event_code::to_string(message.fields.event_code.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_level2::stock_directory_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("StockDirectoryMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("market_category");
    writer.string(itch_level2::market_category::to_string(message.fields.market_category.get().value()));
    writer.key("financial_status_indicator");
    writer.string(itch_level2::financial_status_indicator::to_string(message.fields.financial_status_indicator.get().value()));
    writer.key("round_lot_size");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.round_lot_size.get().value()));
    writer.key("round_lots_only");
    writer.string(itch_level2::round_lots_only::to_string(message.fields.round_lots_only.get().value()));
    writer.key("issue_classification");
    writer.string(itch_level2::issue_classification::to_string(message.fields.issue_classification.get().value()));
    writer.key("issue_subtype");
    writer.string(message.fields.issue_subtype.get_trimmed().value());
    writer.key("authenticity");
    writer.string(itch_level2::authenticity::to_string(message.fields.authenticity.get().value()));
    writer.key("short_sale_threshold_indicator");
    writer.string(itch_level2::short_sale_threshold_indicator::to_string(message.fields.short_sale_threshold_indicator.get().value()));
    writer.key("ipo_flag");
    writer.string(itch_level2::ipo_flag::to_string(message.fields.ipo_flag.get().value()));
    writer.key("luld_reference_price_tier");
    writer.string(itch_level2::luld_reference_price_tier::to_string(message.fields.luld_reference_price_tier.get().value()));
    writer.key("etp_flag");
    writer.string(itch_level2::etp_flag::to_string(message.fields.etp_flag.get().value()));
    writer.key("etp_leverage_factor");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.etp_leverage_factor.get().value()));
    writer.key("inverse_indicator");
    writer.string(itch_level2::inverse_indicator::to_string(message.fields.inverse_indicator.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_level2::stock_trading_action_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("StockTradingActionMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("current_trading_state");
    writer.string(itch_level2::current_trading_state::to_string(message.fields.current_trading_state.get().value()));
    writer.key("reason");
    writer.string(message.fields.reason.get_trimmed().value());
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_level2::reg_sho_short_sale_price_test_restricted_indicator_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("RegShoShortSalePriceTestRestrictedIndicatorMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("reg_sho_action");
    writer.string(itch_level2::reg_sho_action::to_string(message.fields.reg_sho_action.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_level2::market_participant_position_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("MarketParticipantPositionMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("mpid");
    writer.string(message.fields.mpid.get_trimmed().value());
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("primary_market_maker");
    writer.string(itch_level2::primary_market_maker::to_string(message.fields.primary_market_maker.get().value()));
    writer.key("market_maker_mode");
    writer.string(itch_level2::market_maker_mode::to_string(message.fields.market_maker_mode.get().value()));
    writer.key("market_participant_state");
    writer.string(itch_level2::market_participant_state::to_string(message.fields.market_participant_state.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_level2::operational_halt_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("OperationalHaltMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("market_code");
    writer.string(itch_level2::market_code::to_string(message.fields.market_code.get().value()));
    writer.key("operational_halt_action");
    writer.string(itch_level2::operational_halt_action::to_string(message.fields.operational_halt_action.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_level2::market_participant_bid_ask_update_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("MarketParticipantBidAskUpdateMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("market_side");
    writer.string(itch_level2::market_side::to_string(message.fields.market_side.get().value()));
    writer.key("participant_shares");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.participant_shares.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("price");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.price.get().value()), itch_level2::price::exponent);
    writer.key("mpid");
    writer.string(message.fields.mpid.get_trimmed().value());
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_level2::retail_price_interest_indicator_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("RetailPriceInterestIndicatorMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("interest_flag");
    writer.string(itch_level2::interest_flag::to_string(message.fields.interest_flag.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_level2::market_wide_circuit_breaker_decline_level_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("MarketWideCircuitBreakerDeclineLevelMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("level_1");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.level_1.get().value()), itch_level2::level_1::exponent);
    writer.key("level_2");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.level_2.get().value()), itch_level2::level_2::exponent);
    writer.key("level_3");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.level_3.get().value()), itch_level2::level_3::exponent);
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_level2::market_wide_circuit_breaker_status_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("MarketWideCircuitBreakerStatusMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("breached_level");
    writer.string(itch_level2::breached_level::to_string(message.fields.breached_level.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_level2::ipo_quoting_period_update_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("IpoQuotingPeriodUpdateMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("ipo_quotation_release_time");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.ipo_quotation_release_time.get().value()));
    writer.key("ipo_quotation_release_qualifier");
    writer.string(itch_level2::ipo_quotation_release_qualifier::to_string(message.fields.ipo_quotation_release_qualifier.get().value()));
    writer.key("ipo_price");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.ipo_price.get().value()), itch_level2::ipo_price::exponent);
    writer.end_object();
}

}
