// Iex.IexEquities.DeepPlus.IexTp.v1.01 messages as JSON, written without a JSON library.
//
// Generated by CppGenerators — do not edit.

#pragma once

#include "cpp/advanced/iex/iexequities/deepplus/iextp/v1.01/messages/Definitions.hpp"
#include "json/native/Writer.hpp"

namespace iex::iexequities::deepplus::iextp::v1_01::json::native {

namespace iextp_deepplus = ::iex::iexequities::deepplus::iextp::v1_01;

// The session dispatches every message the protocol has; these are the ones written, asked
// at compile time so a program instantiates nothing for the rest.
template <typename Message>
inline constexpr bool writes = true;

inline void write(omi::json::native::Writer& writer, const iextp_deepplus::system_event_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("SystemEventMessage");
    writer.key("system_event");
    writer.string(iextp_deepplus::system_event::to_string(message.fields.system_event.get().value()));
    writer.key("timestamp");
    writer.signed_integer(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const iextp_deepplus::security_directory_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("SecurityDirectoryMessage");
    writer.key("security_directory_flags");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.security_directory_flags.get().value()));
    writer.key("timestamp");
    writer.signed_integer(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.key("symbol");
    writer.string(message.fields.symbol.get_trimmed().value());
    writer.key("round_lot_size");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.round_lot_size.get().value()));
    writer.key("adjusted_poc_price");
    writer.decimal(static_cast<std::int64_t>(message.fields.adjusted_poc_price.get().value()), iextp_deepplus::adjusted_poc_price::exponent);
    writer.key("luld_tier");
    writer.string(iextp_deepplus::luld_tier::to_string(message.fields.luld_tier.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const iextp_deepplus::trading_status_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("TradingStatusMessage");
    writer.key("trading_status");
    writer.string(iextp_deepplus::trading_status::to_string(message.fields.trading_status.get().value()));
    writer.key("timestamp");
    writer.signed_integer(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.key("symbol");
    writer.string(message.fields.symbol.get_trimmed().value());
    writer.key("reason");
    writer.string(message.fields.reason.get_trimmed().value());
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const iextp_deepplus::retail_liquidity_indicator_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("RetailLiquidityIndicatorMessage");
    writer.key("retail_liquidity_indicator");
    writer.string(iextp_deepplus::retail_liquidity_indicator::to_string(message.fields.retail_liquidity_indicator.get().value()));
    writer.key("timestamp");
    writer.signed_integer(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.key("symbol");
    writer.string(message.fields.symbol.get_trimmed().value());
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const iextp_deepplus::operational_halt_status_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("OperationalHaltStatusMessage");
    writer.key("operational_halt_status");
    writer.string(iextp_deepplus::operational_halt_status::to_string(message.fields.operational_halt_status.get().value()));
    writer.key("timestamp");
    writer.signed_integer(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.key("symbol");
    writer.string(message.fields.symbol.get_trimmed().value());
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const iextp_deepplus::short_sale_price_test_status_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("ShortSalePriceTestStatusMessage");
    writer.key("short_sale_price_test_status");
    writer.string(iextp_deepplus::short_sale_price_test_status::to_string(message.fields.short_sale_price_test_status.get().value()));
    writer.key("timestamp");
    writer.signed_integer(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.key("symbol");
    writer.string(message.fields.symbol.get_trimmed().value());
    writer.key("detail");
    writer.string(iextp_deepplus::detail::to_string(message.fields.detail.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const iextp_deepplus::security_event_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("SecurityEventMessage");
    writer.key("security_event");
    writer.string(iextp_deepplus::security_event::to_string(message.fields.security_event.get().value()));
    writer.key("timestamp");
    writer.signed_integer(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.key("symbol");
    writer.string(message.fields.symbol.get_trimmed().value());
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const iextp_deepplus::add_order_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("AddOrderMessage");
    writer.key("side");
    writer.string(iextp_deepplus::side::to_string(message.fields.side.get().value()));
    writer.key("timestamp");
    writer.signed_integer(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.key("symbol");
    writer.string(message.fields.symbol.get_trimmed().value());
    writer.key("order_id");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.order_id.get().value()));
    writer.key("size");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.size.get().value()));
    writer.key("price");
    writer.decimal(static_cast<std::int64_t>(message.fields.price.get().value()), iextp_deepplus::price::exponent);
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const iextp_deepplus::order_modify_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("OrderModifyMessage");
    writer.key("modify_flags");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.modify_flags.get().value()));
    writer.key("timestamp");
    writer.signed_integer(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.key("symbol");
    writer.string(message.fields.symbol.get_trimmed().value());
    writer.key("order_id_reference");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.order_id_reference.get().value()));
    writer.key("size");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.size.get().value()));
    writer.key("price");
    writer.decimal(static_cast<std::int64_t>(message.fields.price.get().value()), iextp_deepplus::price::exponent);
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const iextp_deepplus::order_delete_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("OrderDeleteMessage");
    writer.key("timestamp");
    writer.signed_integer(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.key("symbol");
    writer.string(message.fields.symbol.get_trimmed().value());
    writer.key("order_id_reference");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.order_id_reference.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const iextp_deepplus::order_executed_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("OrderExecutedMessage");
    writer.key("sale_condition_flags");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.sale_condition_flags.get().value()));
    writer.key("timestamp");
    writer.signed_integer(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.key("symbol");
    writer.string(message.fields.symbol.get_trimmed().value());
    writer.key("order_id_reference");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.order_id_reference.get().value()));
    writer.key("size");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.size.get().value()));
    writer.key("price");
    writer.decimal(static_cast<std::int64_t>(message.fields.price.get().value()), iextp_deepplus::price::exponent);
    writer.key("trade_id");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.trade_id.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const iextp_deepplus::trade_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("TradeMessage");
    writer.key("sale_condition_flags");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.sale_condition_flags.get().value()));
    writer.key("timestamp");
    writer.signed_integer(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.key("symbol");
    writer.string(message.fields.symbol.get_trimmed().value());
    writer.key("size");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.size.get().value()));
    writer.key("price");
    writer.decimal(static_cast<std::int64_t>(message.fields.price.get().value()), iextp_deepplus::price::exponent);
    writer.key("trade_id");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.trade_id.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const iextp_deepplus::trade_break_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("TradeBreakMessage");
    writer.key("sale_condition_flags");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.sale_condition_flags.get().value()));
    writer.key("timestamp");
    writer.signed_integer(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.key("symbol");
    writer.string(message.fields.symbol.get_trimmed().value());
    writer.key("size");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.size.get().value()));
    writer.key("price");
    writer.decimal(static_cast<std::int64_t>(message.fields.price.get().value()), iextp_deepplus::price::exponent);
    writer.key("trade_id");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.trade_id.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const iextp_deepplus::clear_book_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("ClearBookMessage");
    writer.key("timestamp");
    writer.signed_integer(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.key("symbol");
    writer.string(message.fields.symbol.get_trimmed().value());
    writer.end_object();
}

}
