// Nasdaq.NsmEquities.NoiView.Itch.v3.0.2026 messages as JSON, written through RapidJSON.
//
// Generated by CppGenerators — do not edit.

#pragma once

#include "cpp/advanced/nasdaq/nsmequities/noiview/itch/v3.0.2026/messages/Definitions.hpp"
#include "json/rapid/Values.hpp"

namespace nasdaq::nsmequities::noiview::itch::v3_0_2026::json::rapid {

namespace itch_noiview = ::nasdaq::nsmequities::noiview::itch::v3_0_2026;

// The session dispatches every message the protocol has; these are the ones written, asked
// at compile time so a program instantiates nothing for the rest.
template <typename Message>
inline constexpr bool writes = true;

template <typename Writer>
void write(Writer& writer, const itch_noiview::system_event& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("SystemEvent");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("event_code");
    omi::json::rapid::character(writer, message.fields.event_code.get().value());
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_noiview::stock_directory_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("StockDirectoryMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("market_category");
    omi::json::rapid::text(writer, itch_noiview::market_category::to_string(message.fields.market_category.get().value()));
    writer.Key("financial_status_indicator");
    omi::json::rapid::text(writer, itch_noiview::financial_status_indicator::to_string(message.fields.financial_status_indicator.get().value()));
    writer.Key("round_lot_size");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.round_lot_size.get().value()));
    writer.Key("round_lots_only");
    omi::json::rapid::text(writer, itch_noiview::round_lots_only::to_string(message.fields.round_lots_only.get().value()));
    writer.Key("issue_classification");
    omi::json::rapid::text(writer, itch_noiview::issue_classification::to_string(message.fields.issue_classification.get().value()));
    writer.Key("issue_sub_type");
    omi::json::rapid::text(writer, message.fields.issue_sub_type.get_trimmed().value());
    writer.Key("authenticity");
    omi::json::rapid::text(writer, itch_noiview::authenticity::to_string(message.fields.authenticity.get().value()));
    writer.Key("short_sale_threshold_indicator");
    omi::json::rapid::text(writer, itch_noiview::short_sale_threshold_indicator::to_string(message.fields.short_sale_threshold_indicator.get().value()));
    writer.Key("ipo_flag");
    omi::json::rapid::text(writer, itch_noiview::ipo_flag::to_string(message.fields.ipo_flag.get().value()));
    writer.Key("luld_reference_price_tier");
    omi::json::rapid::text(writer, itch_noiview::luld_reference_price_tier::to_string(message.fields.luld_reference_price_tier.get().value()));
    writer.Key("etp_flag");
    omi::json::rapid::text(writer, itch_noiview::etp_flag::to_string(message.fields.etp_flag.get().value()));
    writer.Key("etp_leverage_factor");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.etp_leverage_factor.get().value()));
    writer.Key("inverse_indicator");
    omi::json::rapid::text(writer, itch_noiview::inverse_indicator::to_string(message.fields.inverse_indicator.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_noiview::stock_trading_action_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("StockTradingActionMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("current_trading_state");
    omi::json::rapid::text(writer, itch_noiview::current_trading_state::to_string(message.fields.current_trading_state.get().value()));
    writer.Key("reason");
    omi::json::rapid::text(writer, message.fields.reason.get_trimmed().value());
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_noiview::reg_sho_short_sale_price_test_restricted_indicator_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("RegShoShortSalePriceTestRestrictedIndicatorMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("reg_sho_action");
    omi::json::rapid::text(writer, itch_noiview::reg_sho_action::to_string(message.fields.reg_sho_action.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_noiview::net_order_imbalance_indicator_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("NetOrderImbalanceIndicatorMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("paired_shares");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.paired_shares.get().value()));
    writer.Key("imbalance_shares");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.imbalance_shares.get().value()));
    writer.Key("imbalance_direction");
    omi::json::rapid::text(writer, itch_noiview::imbalance_direction::to_string(message.fields.imbalance_direction.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("far_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.far_price.get().value()), itch_noiview::far_price::exponent);
    writer.Key("near_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.near_price.get().value()), itch_noiview::near_price::exponent);
    writer.Key("current_reference_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.current_reference_price.get().value()), itch_noiview::current_reference_price::exponent);
    writer.Key("cross_type");
    omi::json::rapid::text(writer, itch_noiview::cross_type::to_string(message.fields.cross_type.get().value()));
    writer.Key("price_variation_indicator");
    omi::json::rapid::text(writer, itch_noiview::price_variation_indicator::to_string(message.fields.price_variation_indicator.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_noiview::cross_trade_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("CrossTradeMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("shares");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.shares.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("cross_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.cross_price.get().value()), itch_noiview::cross_price::exponent);
    writer.Key("match_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.match_number.get().value()));
    writer.Key("cross_type");
    omi::json::rapid::text(writer, itch_noiview::cross_type::to_string(message.fields.cross_type.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_noiview::ipo_quoting_period_update_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("IpoQuotingPeriodUpdateMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("ipo_quotation_release_time");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.ipo_quotation_release_time.get().value()));
    writer.Key("ipo_quotation_release_qualifier");
    omi::json::rapid::text(writer, itch_noiview::ipo_quotation_release_qualifier::to_string(message.fields.ipo_quotation_release_qualifier.get().value()));
    writer.Key("ipo_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.ipo_price.get().value()), itch_noiview::ipo_price::exponent);
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_noiview::direct_listing_with_capital_raise_price_discovery_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("DirectListingWithCapitalRaisePriceDiscoveryMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("open_eligibility_status");
    omi::json::rapid::character(writer, message.fields.open_eligibility_status.get().value());
    writer.Key("minimum_allowable_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.minimum_allowable_price.get().value()), itch_noiview::minimum_allowable_price::exponent);
    writer.Key("maximum_allowable_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.maximum_allowable_price.get().value()), itch_noiview::maximum_allowable_price::exponent);
    writer.Key("near_execution_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.near_execution_price.get().value()), itch_noiview::near_execution_price::exponent);
    writer.Key("near_execution_time");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.near_execution_time.get().value()));
    writer.Key("lower_price_range_collar");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.lower_price_range_collar.get().value()), itch_noiview::lower_price_range_collar::exponent);
    writer.Key("upper_price_range_collar");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.upper_price_range_collar.get().value()), itch_noiview::upper_price_range_collar::exponent);
    writer.EndObject();
}

}
