// Nasdaq.NsmEquities.NlsPlus.Itch.v4.0 messages as JSON, written through RapidJSON.
//
// Generated by CppGenerators — do not edit.

#pragma once

#include "cpp/advanced/nasdaq/nsmequities/nlsplus/itch/v4.0/messages/Definitions.hpp"
#include "json/rapid/Values.hpp"

namespace nasdaq::nsmequities::nlsplus::itch::v4_0::json::rapid {

namespace itch_nlsplus = ::nasdaq::nsmequities::nlsplus::itch::v4_0;

// The session dispatches every message the protocol has; these are the ones written, asked
// at compile time so a program instantiates nothing for the rest.
template <typename Message>
inline constexpr bool writes = true;

template <typename Writer>
void write(Writer& writer, const itch_nlsplus::system_event_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("SystemEventMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("event_code");
    omi::json::rapid::text(writer, itch_nlsplus::event_code::to_string(message.fields.event_code.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_nlsplus::trade_report_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("TradeReportMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("client_timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.client_timestamp.get().value()));
    writer.Key("originating_market_center_identifier");
    omi::json::rapid::text(writer, itch_nlsplus::originating_market_center_identifier::to_string(message.fields.originating_market_center_identifier.get().value()));
    writer.Key("issue_symbol");
    omi::json::rapid::text(writer, message.fields.issue_symbol.get_trimmed().value());
    writer.Key("security_class");
    omi::json::rapid::text(writer, itch_nlsplus::security_class::to_string(message.fields.security_class.get().value()));
    writer.Key("trade_control_number");
    omi::json::rapid::text(writer, message.fields.trade_control_number.get_trimmed().value());
    writer.Key("trade_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.trade_price.get().value()), itch_nlsplus::trade_price::exponent);
    writer.Key("trade_size");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.trade_size.get().value()), itch_nlsplus::trade_size::exponent);
    writer.Key("sale_condition_modifier");
    omi::json::rapid::text(writer, message.fields.sale_condition_modifier.get_trimmed().value());
    writer.Key("consolidated_volume");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.consolidated_volume.get().value()), itch_nlsplus::consolidated_volume::exponent);
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_nlsplus::trade_cancel_error_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("TradeCancelErrorMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("client_timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.client_timestamp.get().value()));
    writer.Key("originating_market_center_identifier");
    omi::json::rapid::text(writer, itch_nlsplus::originating_market_center_identifier::to_string(message.fields.originating_market_center_identifier.get().value()));
    writer.Key("issue_symbol");
    omi::json::rapid::text(writer, message.fields.issue_symbol.get_trimmed().value());
    writer.Key("security_class");
    omi::json::rapid::text(writer, itch_nlsplus::security_class::to_string(message.fields.security_class.get().value()));
    writer.Key("original_trade_control_number");
    omi::json::rapid::text(writer, message.fields.original_trade_control_number.get_trimmed().value());
    writer.Key("original_trade_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.original_trade_price.get().value()), itch_nlsplus::original_trade_price::exponent);
    writer.Key("original_trade_size");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.original_trade_size.get().value()), itch_nlsplus::original_trade_size::exponent);
    writer.Key("original_sale_condition_modifier");
    omi::json::rapid::text(writer, message.fields.original_sale_condition_modifier.get_trimmed().value());
    writer.Key("consolidated_volume");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.consolidated_volume.get().value()), itch_nlsplus::consolidated_volume::exponent);
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_nlsplus::trade_correction_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("TradeCorrectionMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("client_timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.client_timestamp.get().value()));
    writer.Key("originating_market_center_identifier");
    omi::json::rapid::text(writer, itch_nlsplus::originating_market_center_identifier::to_string(message.fields.originating_market_center_identifier.get().value()));
    writer.Key("issue_symbol");
    omi::json::rapid::text(writer, message.fields.issue_symbol.get_trimmed().value());
    writer.Key("security_class");
    omi::json::rapid::text(writer, itch_nlsplus::security_class::to_string(message.fields.security_class.get().value()));
    writer.Key("original_trade_control_number");
    omi::json::rapid::text(writer, message.fields.original_trade_control_number.get_trimmed().value());
    writer.Key("original_trade_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.original_trade_price.get().value()), itch_nlsplus::original_trade_price::exponent);
    writer.Key("original_trade_size");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.original_trade_size.get().value()), itch_nlsplus::original_trade_size::exponent);
    writer.Key("original_sale_condition_modifier");
    omi::json::rapid::text(writer, message.fields.original_sale_condition_modifier.get_trimmed().value());
    writer.Key("corrected_trade_control_number");
    omi::json::rapid::text(writer, message.fields.corrected_trade_control_number.get_trimmed().value());
    writer.Key("corrected_trade_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.corrected_trade_price.get().value()), itch_nlsplus::corrected_trade_price::exponent);
    writer.Key("corrected_trade_size");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.corrected_trade_size.get().value()), itch_nlsplus::corrected_trade_size::exponent);
    writer.Key("corrected_sale_condition_modifier");
    omi::json::rapid::text(writer, message.fields.corrected_sale_condition_modifier.get_trimmed().value());
    writer.Key("consolidated_volume");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.consolidated_volume.get().value()), itch_nlsplus::consolidated_volume::exponent);
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_nlsplus::stock_trading_action_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("StockTradingActionMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("issue_symbol");
    omi::json::rapid::text(writer, message.fields.issue_symbol.get_trimmed().value());
    writer.Key("security_class");
    omi::json::rapid::text(writer, itch_nlsplus::security_class::to_string(message.fields.security_class.get().value()));
    writer.Key("current_trading_state");
    omi::json::rapid::text(writer, itch_nlsplus::current_trading_state::to_string(message.fields.current_trading_state.get().value()));
    writer.Key("reason");
    omi::json::rapid::text(writer, message.fields.reason.get_trimmed().value());
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_nlsplus::reg_sho_short_sale_price_test_restricted_indicator_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("RegShoShortSalePriceTestRestrictedIndicatorMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("issue_symbol");
    omi::json::rapid::text(writer, message.fields.issue_symbol.get_trimmed().value());
    writer.Key("reg_sho_action");
    omi::json::rapid::text(writer, itch_nlsplus::reg_sho_action::to_string(message.fields.reg_sho_action.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_nlsplus::stock_directory_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("StockDirectoryMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("market_category");
    omi::json::rapid::text(writer, itch_nlsplus::market_category::to_string(message.fields.market_category.get().value()));
    writer.Key("financial_status_indicator");
    omi::json::rapid::text(writer, itch_nlsplus::financial_status_indicator::to_string(message.fields.financial_status_indicator.get().value()));
    writer.Key("round_lot_size");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.round_lot_size.get().value()));
    writer.Key("round_lots_only");
    omi::json::rapid::text(writer, itch_nlsplus::round_lots_only::to_string(message.fields.round_lots_only.get().value()));
    writer.Key("issue_classification");
    omi::json::rapid::text(writer, itch_nlsplus::issue_classification::to_string(message.fields.issue_classification.get().value()));
    writer.Key("issue_sub_type");
    omi::json::rapid::text(writer, message.fields.issue_sub_type.get_trimmed().value());
    writer.Key("authenticity");
    omi::json::rapid::text(writer, itch_nlsplus::authenticity::to_string(message.fields.authenticity.get().value()));
    writer.Key("short_sale_threshold_indicator");
    omi::json::rapid::text(writer, itch_nlsplus::short_sale_threshold_indicator::to_string(message.fields.short_sale_threshold_indicator.get().value()));
    writer.Key("ipo_flag");
    omi::json::rapid::text(writer, itch_nlsplus::ipo_flag::to_string(message.fields.ipo_flag.get().value()));
    writer.Key("luld_reference_price_tier");
    omi::json::rapid::text(writer, itch_nlsplus::luld_reference_price_tier::to_string(message.fields.luld_reference_price_tier.get().value()));
    writer.Key("etp_flag");
    omi::json::rapid::text(writer, itch_nlsplus::etp_flag::to_string(message.fields.etp_flag.get().value()));
    writer.Key("etp_leverage_factor");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.etp_leverage_factor.get().value()));
    writer.Key("inverse_indicator");
    omi::json::rapid::text(writer, itch_nlsplus::inverse_indicator::to_string(message.fields.inverse_indicator.get().value()));
    writer.Key("bloomberg_id");
    omi::json::rapid::text(writer, message.fields.bloomberg_id.get_trimmed().value());
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_nlsplus::adjusted_closing_price_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("AdjustedClosingPriceMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("issue_symbol");
    omi::json::rapid::text(writer, message.fields.issue_symbol.get_trimmed().value());
    writer.Key("security_class");
    omi::json::rapid::text(writer, itch_nlsplus::security_class::to_string(message.fields.security_class.get().value()));
    writer.Key("adjusted_closing_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.adjusted_closing_price.get().value()), itch_nlsplus::adjusted_closing_price::exponent);
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_nlsplus::end_of_day_trade_summary_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("EndOfDayTradeSummaryMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("issue_symbol");
    omi::json::rapid::text(writer, message.fields.issue_symbol.get_trimmed().value());
    writer.Key("security_class");
    omi::json::rapid::text(writer, itch_nlsplus::security_class::to_string(message.fields.security_class.get().value()));
    writer.Key("consolidated_high_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.consolidated_high_price.get().value()), itch_nlsplus::consolidated_high_price::exponent);
    writer.Key("consolidated_low_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.consolidated_low_price.get().value()), itch_nlsplus::consolidated_low_price::exponent);
    writer.Key("consolidated_closing_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.consolidated_closing_price.get().value()), itch_nlsplus::consolidated_closing_price::exponent);
    writer.Key("consolidated_volume");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.consolidated_volume.get().value()), itch_nlsplus::consolidated_volume::exponent);
    writer.Key("consolidated_open_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.consolidated_open_price.get().value()), itch_nlsplus::consolidated_open_price::exponent);
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_nlsplus::ipo_information_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("IpoInformationMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("issue_symbol");
    omi::json::rapid::text(writer, message.fields.issue_symbol.get_trimmed().value());
    writer.Key("security_class");
    omi::json::rapid::text(writer, itch_nlsplus::security_class::to_string(message.fields.security_class.get().value()));
    writer.Key("reference_for_net_change");
    omi::json::rapid::text(writer, itch_nlsplus::reference_for_net_change::to_string(message.fields.reference_for_net_change.get().value()));
    writer.Key("reference_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.reference_price.get().value()), itch_nlsplus::reference_price::exponent);
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_nlsplus::mwcb_decline_level_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("MwcbDeclineLevelMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("level_1");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.level_1.get().value()), itch_nlsplus::level_1::exponent);
    writer.Key("level_2");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.level_2.get().value()), itch_nlsplus::level_2::exponent);
    writer.Key("level_3");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.level_3.get().value()), itch_nlsplus::level_3::exponent);
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_nlsplus::mwcb_status_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("MwcbStatusMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("breached_level");
    omi::json::rapid::text(writer, itch_nlsplus::breached_level::to_string(message.fields.breached_level.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_nlsplus::ipo_quoting_period_update_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("IpoQuotingPeriodUpdateMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("ipo_quotation_release_time");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.ipo_quotation_release_time.get().value()));
    writer.Key("ipo_quotation_release_qualifier");
    omi::json::rapid::text(writer, itch_nlsplus::ipo_quotation_release_qualifier::to_string(message.fields.ipo_quotation_release_qualifier.get().value()));
    writer.Key("ipo_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.ipo_price.get().value()), itch_nlsplus::ipo_price::exponent);
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_nlsplus::operational_halt_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("OperationalHaltMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock_alpha_8");
    omi::json::rapid::text(writer, message.fields.stock_alpha_8.get_trimmed().value());
    writer.Key("market_code");
    omi::json::rapid::text(writer, itch_nlsplus::market_code::to_string(message.fields.market_code.get().value()));
    writer.Key("operational_halt_action");
    omi::json::rapid::text(writer, itch_nlsplus::operational_halt_action::to_string(message.fields.operational_halt_action.get().value()));
    writer.EndObject();
}

}
