// Nasdaq.NsmEquities.TotalView.Itch.v4.1 messages as JSON, written without a JSON library.
//
// Generated by CppGenerators — do not edit.

#pragma once

#include "cpp/advanced/nasdaq/nsmequities/totalview/itch/v4.1/messages/Definitions.hpp"
#include "json/native/Writer.hpp"

namespace nasdaq::nsmequities::totalview::itch::v4_1::json::native {

namespace itch_totalview = ::nasdaq::nsmequities::totalview::itch::v4_1;

// The session dispatches every message the protocol has; these are the ones written, asked
// at compile time so a program instantiates nothing for the rest.
template <typename Message>
inline constexpr bool writes = true;

inline void write(omi::json::native::Writer& writer, const itch_totalview::debug_packet& message) {
    writer.start_object();
    writer.key("message");
    writer.string("DebugPacket");
    writer.key("text");
    writer.character(message.fields.text.get().value());
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_totalview::login_request_packet& message) {
    writer.start_object();
    writer.key("message");
    writer.string("LoginRequestPacket");
    writer.key("username");
    writer.string(message.fields.username.get_trimmed().value());
    writer.key("password");
    writer.string(message.fields.password.get_trimmed().value());
    writer.key("requested_session");
    writer.string(message.fields.requested_session.get_trimmed().value());
    writer.key("requested_sequence_number");
    writer.string(message.fields.requested_sequence_number.get_trimmed().value());
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_totalview::unsequenced_data_packet& message) {
    writer.start_object();
    writer.key("message");
    writer.string("UnsequencedDataPacket");
    writer.key("unsequenced_message_type");
    writer.character(message.fields.unsequenced_message_type.get().value());
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_totalview::login_accepted_packet& message) {
    writer.start_object();
    writer.key("message");
    writer.string("LoginAcceptedPacket");
    writer.key("accepted_session");
    writer.string(message.fields.accepted_session.get_trimmed().value());
    writer.key("accepted_sequence_number");
    writer.string(message.fields.accepted_sequence_number.get_trimmed().value());
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_totalview::login_rejected_packet& message) {
    writer.start_object();
    writer.key("message");
    writer.string("LoginRejectedPacket");
    writer.key("reject_reason_code");
    writer.string(itch_totalview::reject_reason_code::to_string(message.fields.reject_reason_code.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_totalview::sequenced_data_packet& message) {
    writer.start_object();
    writer.key("message");
    writer.string("SequencedDataPacket");
    writer.key("sequenced_message_type");
    writer.character(message.fields.sequenced_message_type.get().value());
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_totalview::timestamp_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("TimestampMessage");
    writer.key("second");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.second.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_totalview::system_event_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("SystemEventMessage");
    writer.key("nanoseconds");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.nanoseconds.get().value()));
    writer.key("event_code");
    writer.string(itch_totalview::event_code::to_string(message.fields.event_code.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_totalview::stock_directory_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("StockDirectoryMessage");
    writer.key("nanoseconds");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.nanoseconds.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("market_category");
    writer.string(itch_totalview::market_category::to_string(message.fields.market_category.get().value()));
    writer.key("financial_status_indicator");
    writer.string(itch_totalview::financial_status_indicator::to_string(message.fields.financial_status_indicator.get().value()));
    writer.key("round_lot_size");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.round_lot_size.get().value()));
    writer.key("round_lots_only");
    writer.string(itch_totalview::round_lots_only::to_string(message.fields.round_lots_only.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_totalview::stock_trading_action_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("StockTradingActionMessage");
    writer.key("nanoseconds");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.nanoseconds.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("trading_state");
    writer.string(itch_totalview::trading_state::to_string(message.fields.trading_state.get().value()));
    writer.key("reason");
    writer.string(message.fields.reason.get_trimmed().value());
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_totalview::reg_sho_short_sale_price_test_restricted_indicator_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("RegShoShortSalePriceTestRestrictedIndicatorMessage");
    writer.key("nanoseconds");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.nanoseconds.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("reg_sho_action");
    writer.string(itch_totalview::reg_sho_action::to_string(message.fields.reg_sho_action.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_totalview::market_participant_position_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("MarketParticipantPositionMessage");
    writer.key("nanoseconds");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.nanoseconds.get().value()));
    writer.key("mpid");
    writer.string(message.fields.mpid.get_trimmed().value());
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("primary_market_maker");
    writer.string(itch_totalview::primary_market_maker::to_string(message.fields.primary_market_maker.get().value()));
    writer.key("market_maker_mode");
    writer.string(itch_totalview::market_maker_mode::to_string(message.fields.market_maker_mode.get().value()));
    writer.key("market_participant_state");
    writer.string(itch_totalview::market_participant_state::to_string(message.fields.market_participant_state.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_totalview::add_order_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("AddOrderMessage");
    writer.key("nanoseconds");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.nanoseconds.get().value()));
    writer.key("order_reference_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.order_reference_number.get().value()));
    writer.key("side");
    writer.string(itch_totalview::side::to_string(message.fields.side.get().value()));
    writer.key("shares");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.shares.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("price");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.price.get().value()), itch_totalview::price::exponent);
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_totalview::add_order_with_mpid_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("AddOrderWithMpidMessage");
    writer.key("nanoseconds");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.nanoseconds.get().value()));
    writer.key("order_reference_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.order_reference_number.get().value()));
    writer.key("side");
    writer.string(itch_totalview::side::to_string(message.fields.side.get().value()));
    writer.key("shares");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.shares.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("price");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.price.get().value()), itch_totalview::price::exponent);
    writer.key("attribution");
    writer.string(message.fields.attribution.get_trimmed().value());
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_totalview::order_executed_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("OrderExecutedMessage");
    writer.key("nanoseconds");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.nanoseconds.get().value()));
    writer.key("order_reference_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.order_reference_number.get().value()));
    writer.key("executed_shares");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.executed_shares.get().value()));
    writer.key("match_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.match_number.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_totalview::order_executed_with_price_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("OrderExecutedWithPriceMessage");
    writer.key("nanoseconds");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.nanoseconds.get().value()));
    writer.key("order_reference_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.order_reference_number.get().value()));
    writer.key("executed_shares");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.executed_shares.get().value()));
    writer.key("match_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.match_number.get().value()));
    writer.key("printable");
    writer.string(itch_totalview::printable::to_string(message.fields.printable.get().value()));
    writer.key("execution_price");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.execution_price.get().value()), itch_totalview::execution_price::exponent);
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_totalview::order_cancel_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("OrderCancelMessage");
    writer.key("nanoseconds");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.nanoseconds.get().value()));
    writer.key("order_reference_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.order_reference_number.get().value()));
    writer.key("canceled_shares");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.canceled_shares.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_totalview::order_delete_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("OrderDeleteMessage");
    writer.key("nanoseconds");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.nanoseconds.get().value()));
    writer.key("order_reference_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.order_reference_number.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_totalview::order_replace_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("OrderReplaceMessage");
    writer.key("nanoseconds");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.nanoseconds.get().value()));
    writer.key("original_order_reference_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.original_order_reference_number.get().value()));
    writer.key("new_order_reference_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.new_order_reference_number.get().value()));
    writer.key("shares");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.shares.get().value()));
    writer.key("price");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.price.get().value()), itch_totalview::price::exponent);
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_totalview::trade_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("TradeMessage");
    writer.key("nanoseconds");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.nanoseconds.get().value()));
    writer.key("order_reference_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.order_reference_number.get().value()));
    writer.key("side");
    writer.string(itch_totalview::side::to_string(message.fields.side.get().value()));
    writer.key("shares");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.shares.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("price");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.price.get().value()), itch_totalview::price::exponent);
    writer.key("match_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.match_number.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_totalview::cross_trade_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("CrossTradeMessage");
    writer.key("nanoseconds");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.nanoseconds.get().value()));
    writer.key("cross_shares");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.cross_shares.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("cross_price");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.cross_price.get().value()), itch_totalview::cross_price::exponent);
    writer.key("match_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.match_number.get().value()));
    writer.key("cross_type");
    writer.string(itch_totalview::cross_type::to_string(message.fields.cross_type.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_totalview::broken_trade_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("BrokenTradeMessage");
    writer.key("nanoseconds");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.nanoseconds.get().value()));
    writer.key("match_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.match_number.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_totalview::net_order_imbalance_indicator_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("NetOrderImbalanceIndicatorMessage");
    writer.key("nanoseconds");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.nanoseconds.get().value()));
    writer.key("paired_shares");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.paired_shares.get().value()));
    writer.key("imbalance_shares");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.imbalance_shares.get().value()));
    writer.key("imbalance_direction");
    writer.string(itch_totalview::imbalance_direction::to_string(message.fields.imbalance_direction.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("far_price");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.far_price.get().value()), itch_totalview::far_price::exponent);
    writer.key("near_price");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.near_price.get().value()), itch_totalview::near_price::exponent);
    writer.key("current_reference_price");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.current_reference_price.get().value()), itch_totalview::current_reference_price::exponent);
    writer.key("cross_type");
    writer.string(itch_totalview::cross_type::to_string(message.fields.cross_type.get().value()));
    writer.key("price_variation_indicator");
    writer.string(itch_totalview::price_variation_indicator::to_string(message.fields.price_variation_indicator.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_totalview::retail_price_improvement_indicator_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("RetailPriceImprovementIndicatorMessage");
    writer.key("nanoseconds");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.nanoseconds.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("interest_flag");
    writer.string(itch_totalview::interest_flag::to_string(message.fields.interest_flag.get().value()));
    writer.end_object();
}

}
