// Iex.IexEquities.DeepPlus.IexTp.v1.05 messages as JSON, written through RapidJSON.
//
// Generated by CppGenerators — do not edit.

#pragma once

#include "cpp/advanced/iex/iexequities/deepplus/iextp/v1.05/messages/Definitions.hpp"
#include "json/rapid/Values.hpp"

namespace iex::iexequities::deepplus::iextp::v1_05::json::rapid {

namespace iextp_deepplus = ::iex::iexequities::deepplus::iextp::v1_05;

// The session dispatches every message the protocol has; these are the ones written, asked
// at compile time so a program instantiates nothing for the rest.
template <typename Message>
inline constexpr bool writes = true;

template <typename Writer>
void write(Writer& writer, const iextp_deepplus::system_event_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("SystemEventMessage");
    writer.Key("system_event");
    omi::json::rapid::text(writer, iextp_deepplus::system_event::to_string(message.fields.system_event.get().value()));
    writer.Key("timestamp");
    writer.Int64(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const iextp_deepplus::security_directory_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("SecurityDirectoryMessage");
    writer.Key("security_directory_flags");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.security_directory_flags.get().value()));
    writer.Key("timestamp");
    writer.Int64(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.Key("symbol");
    omi::json::rapid::text(writer, message.fields.symbol.get_trimmed().value());
    writer.Key("round_lot_size");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.round_lot_size.get().value()));
    writer.Key("adjusted_poc_price");
    omi::json::rapid::decimal(writer, static_cast<std::int64_t>(message.fields.adjusted_poc_price.get().value()), iextp_deepplus::adjusted_poc_price::exponent);
    writer.Key("luld_tier");
    omi::json::rapid::text(writer, iextp_deepplus::luld_tier::to_string(message.fields.luld_tier.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const iextp_deepplus::trading_status_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("TradingStatusMessage");
    writer.Key("trading_status");
    omi::json::rapid::text(writer, iextp_deepplus::trading_status::to_string(message.fields.trading_status.get().value()));
    writer.Key("timestamp");
    writer.Int64(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.Key("symbol");
    omi::json::rapid::text(writer, message.fields.symbol.get_trimmed().value());
    writer.Key("reason");
    omi::json::rapid::text(writer, message.fields.reason.get_trimmed().value());
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const iextp_deepplus::retail_liquidity_indicator_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("RetailLiquidityIndicatorMessage");
    writer.Key("retail_liquidity_indicator");
    omi::json::rapid::text(writer, iextp_deepplus::retail_liquidity_indicator::to_string(message.fields.retail_liquidity_indicator.get().value()));
    writer.Key("timestamp");
    writer.Int64(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.Key("symbol");
    omi::json::rapid::text(writer, message.fields.symbol.get_trimmed().value());
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const iextp_deepplus::operational_halt_status_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("OperationalHaltStatusMessage");
    writer.Key("operational_halt_status");
    omi::json::rapid::text(writer, iextp_deepplus::operational_halt_status::to_string(message.fields.operational_halt_status.get().value()));
    writer.Key("timestamp");
    writer.Int64(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.Key("symbol");
    omi::json::rapid::text(writer, message.fields.symbol.get_trimmed().value());
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const iextp_deepplus::short_sale_price_test_status_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("ShortSalePriceTestStatusMessage");
    writer.Key("short_sale_price_test_status");
    omi::json::rapid::text(writer, iextp_deepplus::short_sale_price_test_status::to_string(message.fields.short_sale_price_test_status.get().value()));
    writer.Key("timestamp");
    writer.Int64(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.Key("symbol");
    omi::json::rapid::text(writer, message.fields.symbol.get_trimmed().value());
    writer.Key("detail");
    omi::json::rapid::text(writer, iextp_deepplus::detail::to_string(message.fields.detail.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const iextp_deepplus::security_event_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("SecurityEventMessage");
    writer.Key("security_event");
    omi::json::rapid::text(writer, iextp_deepplus::security_event::to_string(message.fields.security_event.get().value()));
    writer.Key("timestamp");
    writer.Int64(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.Key("symbol");
    omi::json::rapid::text(writer, message.fields.symbol.get_trimmed().value());
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const iextp_deepplus::add_order_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("AddOrderMessage");
    writer.Key("side");
    omi::json::rapid::text(writer, iextp_deepplus::side::to_string(message.fields.side.get().value()));
    writer.Key("timestamp");
    writer.Int64(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.Key("symbol");
    omi::json::rapid::text(writer, message.fields.symbol.get_trimmed().value());
    writer.Key("order_id");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.order_id.get().value()));
    writer.Key("size");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.size.get().value()));
    writer.Key("price");
    omi::json::rapid::decimal(writer, static_cast<std::int64_t>(message.fields.price.get().value()), iextp_deepplus::price::exponent);
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const iextp_deepplus::order_modify_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("OrderModifyMessage");
    writer.Key("modify_flags");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.modify_flags.get().value()));
    writer.Key("timestamp");
    writer.Int64(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.Key("symbol");
    omi::json::rapid::text(writer, message.fields.symbol.get_trimmed().value());
    writer.Key("order_id_reference");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.order_id_reference.get().value()));
    writer.Key("size");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.size.get().value()));
    writer.Key("price");
    omi::json::rapid::decimal(writer, static_cast<std::int64_t>(message.fields.price.get().value()), iextp_deepplus::price::exponent);
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const iextp_deepplus::order_delete_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("OrderDeleteMessage");
    writer.Key("timestamp");
    writer.Int64(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.Key("symbol");
    omi::json::rapid::text(writer, message.fields.symbol.get_trimmed().value());
    writer.Key("order_id_reference");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.order_id_reference.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const iextp_deepplus::order_executed_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("OrderExecutedMessage");
    writer.Key("sale_condition_flags");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.sale_condition_flags.get().value()));
    writer.Key("timestamp");
    writer.Int64(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.Key("symbol");
    omi::json::rapid::text(writer, message.fields.symbol.get_trimmed().value());
    writer.Key("order_id_reference");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.order_id_reference.get().value()));
    writer.Key("size");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.size.get().value()));
    writer.Key("price");
    omi::json::rapid::decimal(writer, static_cast<std::int64_t>(message.fields.price.get().value()), iextp_deepplus::price::exponent);
    writer.Key("trade_id");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.trade_id.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const iextp_deepplus::trade_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("TradeMessage");
    writer.Key("sale_condition_flags");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.sale_condition_flags.get().value()));
    writer.Key("timestamp");
    writer.Int64(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.Key("symbol");
    omi::json::rapid::text(writer, message.fields.symbol.get_trimmed().value());
    writer.Key("size");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.size.get().value()));
    writer.Key("price");
    omi::json::rapid::decimal(writer, static_cast<std::int64_t>(message.fields.price.get().value()), iextp_deepplus::price::exponent);
    writer.Key("trade_id");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.trade_id.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const iextp_deepplus::trade_break_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("TradeBreakMessage");
    writer.Key("sale_condition_flags");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.sale_condition_flags.get().value()));
    writer.Key("timestamp");
    writer.Int64(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.Key("symbol");
    omi::json::rapid::text(writer, message.fields.symbol.get_trimmed().value());
    writer.Key("size");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.size.get().value()));
    writer.Key("price");
    omi::json::rapid::decimal(writer, static_cast<std::int64_t>(message.fields.price.get().value()), iextp_deepplus::price::exponent);
    writer.Key("trade_id");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.trade_id.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const iextp_deepplus::clear_book_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("ClearBookMessage");
    writer.Key("timestamp");
    writer.Int64(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.Key("symbol");
    omi::json::rapid::text(writer, message.fields.symbol.get_trimmed().value());
    writer.EndObject();
}

}
