// Iex.IexEquities.DeepPlus.IexTp.v1.01 to JSON: every message of a capture as one JSON object per line, written
// through RapidJSON.
//
// Generated by CppGenerators — do not edit.

#include <cstdint>
#include <cstdio>
#include <string>
#include <utility>
#include <vector>

#include <rapidjson/stringbuffer.h>
#include <rapidjson/writer.h>

#include "PcapIterator.hpp"
#include "Frame.hpp"
#include "cpp/advanced/iex/iexequities/deepplus/iextp/v1.01/messages/session.hpp"
#include "json/rapid/iex/iexequities/deepplus/iextp/v1.01/Json.hpp"

namespace protocol = ::iex::iexequities::deepplus::iextp::v1_01;

namespace {

// The handler the session layer dispatches into: each message becomes one line of JSON.
struct Lines {
    std::FILE* out;
    rapidjson::StringBuffer buffer{};
    rapidjson::Writer<rapidjson::StringBuffer> writer{ buffer };
    std::uint64_t messages = 0;

    protocol::seq_action on_transport_header(const protocol::iextp_header&, const packet::Frame&) {
        return protocol::seq_action::process;
    }

    template <typename Message>
    void on_message(const Message& message, std::uint64_t, const protocol::iextp_header&) {
        if constexpr (protocol::json::rapid::writes<Message>) {
            buffer.Clear();
            writer.Reset(buffer);
            protocol::json::rapid::write(writer, message);
            buffer.Put('\n');
            std::fwrite(buffer.GetString(), 1, buffer.GetSize(), out);
            ++messages;
        }
    }
};

}

int main(int argc, char** argv) {
    if (argc < 2 || argc > 3) {
        std::fprintf(stderr, "usage: %s <capture.pcap> [output.jsonl]\n", argv[0]);
        return 2;
    }

    std::FILE* out = argc == 3 ? std::fopen(argv[2], "wb") : stdout;

    if (out == nullptr) {
        std::fprintf(stderr, "cannot open %s\n", argv[2]);
        return 1;
    }

    std::vector<std::pair<std::string, std::int64_t>> sources;
    sources.emplace_back(argv[1], 0);

    packet::PcapIterator captures(sources);
    Lines lines{ out };

    while (captures.advance()) {
        const packet::Frame frame(captures.data(), captures.length());

        if (!frame.valid()) { continue; }

        protocol::process_segment(lines, frame.payload, frame.payload_len, captures.timestamp_ns(), frame);
    }

    if (out != stdout) { std::fclose(out); }

    std::fprintf(stderr, "wrote %llu messages\n", static_cast<unsigned long long>(lines.messages));
    return 0;
}
