// Nasdaq.NsmEquities.NoiView.Itch.v3.0.2017 messages as JSON, written without a JSON library.
//
// Generated by CppGenerators — do not edit.

#pragma once

#include "cpp/advanced/nasdaq/nsmequities/noiview/itch/v3.0.2017/messages/Definitions.hpp"
#include "json/native/Writer.hpp"

namespace nasdaq::nsmequities::noiview::itch::v3_0_2017::json::native {

namespace itch_noiview = ::nasdaq::nsmequities::noiview::itch::v3_0_2017;

// The session dispatches every message the protocol has; these are the ones written, asked
// at compile time so a program instantiates nothing for the rest.
template <typename Message>
inline constexpr bool writes = true;

inline void write(omi::json::native::Writer& writer, const itch_noiview::system_event_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("SystemEventMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("event_code");
    writer.string(itch_noiview::event_code::to_string(message.fields.event_code.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_noiview::stock_directory_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("StockDirectoryMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("market_category");
    writer.string(itch_noiview::market_category::to_string(message.fields.market_category.get().value()));
    writer.key("financial_status_indicator");
    writer.string(itch_noiview::financial_status_indicator::to_string(message.fields.financial_status_indicator.get().value()));
    writer.key("round_lot_size");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.round_lot_size.get().value()));
    writer.key("round_lots_only");
    writer.string(itch_noiview::round_lots_only::to_string(message.fields.round_lots_only.get().value()));
    writer.key("issue_classification");
    writer.character(message.fields.issue_classification.get().value());
    writer.key("issue_sub_type");
    writer.string(message.fields.issue_sub_type.get_trimmed().value());
    writer.key("authenticity");
    writer.string(itch_noiview::authenticity::to_string(message.fields.authenticity.get().value()));
    writer.key("short_sale_threshold_indicator");
    writer.string(itch_noiview::short_sale_threshold_indicator::to_string(message.fields.short_sale_threshold_indicator.get().value()));
    writer.key("ipo_flag");
    writer.string(itch_noiview::ipo_flag::to_string(message.fields.ipo_flag.get().value()));
    writer.key("luld_reference_price_tier");
    writer.string(itch_noiview::luld_reference_price_tier::to_string(message.fields.luld_reference_price_tier.get().value()));
    writer.key("etp_flag");
    writer.string(itch_noiview::etp_flag::to_string(message.fields.etp_flag.get().value()));
    writer.key("etp_leverage_factor");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.etp_leverage_factor.get().value()));
    writer.key("inverse_indicator");
    writer.string(itch_noiview::inverse_indicator::to_string(message.fields.inverse_indicator.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_noiview::stock_trading_action_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("StockTradingActionMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("current_trading_state");
    writer.string(itch_noiview::current_trading_state::to_string(message.fields.current_trading_state.get().value()));
    writer.key("reason");
    writer.string(message.fields.reason.get_trimmed().value());
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_noiview::reg_sho_restriction_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("RegShoRestrictionMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("reg_sho_action");
    writer.string(itch_noiview::reg_sho_action::to_string(message.fields.reg_sho_action.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_noiview::noii_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("NoiiMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("paired_shares");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.paired_shares.get().value()));
    writer.key("imbalance_shares");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.imbalance_shares.get().value()));
    writer.key("imbalance_direction");
    writer.string(itch_noiview::imbalance_direction::to_string(message.fields.imbalance_direction.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("far_price");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.far_price.get().value()), itch_noiview::far_price::exponent);
    writer.key("near_price");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.near_price.get().value()), itch_noiview::near_price::exponent);
    writer.key("current_reference_price");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.current_reference_price.get().value()), itch_noiview::current_reference_price::exponent);
    writer.key("cross_type");
    writer.string(itch_noiview::cross_type::to_string(message.fields.cross_type.get().value()));
    writer.key("price_variation_indicator");
    writer.string(itch_noiview::price_variation_indicator::to_string(message.fields.price_variation_indicator.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_noiview::cross_trade_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("CrossTradeMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("shares");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.shares.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("cross_price");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.cross_price.get().value()), itch_noiview::cross_price::exponent);
    writer.key("match_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.match_number.get().value()));
    writer.key("cross_type");
    writer.string(itch_noiview::cross_type::to_string(message.fields.cross_type.get().value()));
    writer.end_object();
}

inline void write(omi::json::native::Writer& writer, const itch_noiview::ipo_quoting_period_update_message& message) {
    writer.start_object();
    writer.key("message");
    writer.string("IpoQuotingPeriodUpdateMessage");
    writer.key("tracking_number");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.key("timestamp");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.key("stock");
    writer.string(message.fields.stock.get_trimmed().value());
    writer.key("ipo_quotation_release_time");
    writer.unsigned_integer(static_cast<std::uint64_t>(message.fields.ipo_quotation_release_time.get().value()));
    writer.key("ipo_quotation_release_qualifier");
    writer.string(itch_noiview::ipo_quotation_release_qualifier::to_string(message.fields.ipo_quotation_release_qualifier.get().value()));
    writer.key("ipo_price");
    writer.unsigned_decimal(static_cast<std::uint64_t>(message.fields.ipo_price.get().value()), itch_noiview::ipo_price::exponent);
    writer.end_object();
}

}
