// Nasdaq.NsmEquities.TotalView.Itch.v5.0.2022 messages as one wide Parquet table.
//
// Generated by CppGenerators — do not edit.

#pragma once

#include "cpp/advanced/nasdaq/nsmequities/totalview/itch/v5.0.2022/messages/Definitions.hpp"
#include "parquet/wide/Table.hpp"

namespace nasdaq::nsmequities::totalview::itch::v5_0_2022::parquet::wide {

namespace itch_totalview = ::nasdaq::nsmequities::totalview::itch::v5_0_2022;

// The session dispatches every message the protocol has; these are the ones written, asked
// at compile time so a program instantiates nothing for the rest.
template <typename Message>
inline constexpr bool writes = true;

// Every column any message of this protocol holds, the message's own name first.
inline std::shared_ptr<arrow::Schema> schema() {
    return arrow::schema({
        arrow::field("message", arrow::utf8()),
        arrow::field("stock_locate", arrow::uint64()),
        arrow::field("tracking_number", arrow::uint64()),
        arrow::field("timestamp", arrow::uint64()),
        arrow::field("event_code", arrow::utf8()),
        arrow::field("stock", arrow::utf8()),
        arrow::field("market_category", arrow::utf8()),
        arrow::field("financial_status_indicator", arrow::utf8()),
        arrow::field("round_lot_size", arrow::uint64()),
        arrow::field("round_lots_only", arrow::utf8()),
        arrow::field("issue_classification", arrow::utf8()),
        arrow::field("issue_sub_type", arrow::utf8()),
        arrow::field("authenticity", arrow::utf8()),
        arrow::field("short_sale_threshold_indicator", arrow::utf8()),
        arrow::field("ipo_flag", arrow::utf8()),
        arrow::field("luld_reference_price_tier", arrow::utf8()),
        arrow::field("etp_flag", arrow::utf8()),
        arrow::field("etp_leverage_factor", arrow::uint64()),
        arrow::field("inverse_indicator", arrow::utf8()),
        arrow::field("trading_state", arrow::utf8()),
        arrow::field("reason_code", arrow::utf8()),
        arrow::field("locate_code", arrow::uint64()),
        arrow::field("reg_sho_action", arrow::utf8()),
        arrow::field("mpid", arrow::utf8()),
        arrow::field("primary_market_maker", arrow::utf8()),
        arrow::field("market_maker_mode", arrow::utf8()),
        arrow::field("market_participant_state", arrow::utf8()),
        arrow::field("level_1", arrow::decimal128(18, 8)),
        arrow::field("level_2", arrow::decimal128(18, 8)),
        arrow::field("level_3", arrow::decimal128(18, 8)),
        arrow::field("breached_level", arrow::utf8()),
        arrow::field("ipo_quotation_release_time", arrow::uint64()),
        arrow::field("ipo_quotation_release_qualifier", arrow::utf8()),
        arrow::field("ipo_price", arrow::decimal128(10, 4)),
        arrow::field("auction_collar_reference_price", arrow::decimal128(10, 4)),
        arrow::field("upper_auction_collar_price", arrow::decimal128(10, 4)),
        arrow::field("lower_auction_collar_price", arrow::decimal128(10, 4)),
        arrow::field("auction_collar_extension", arrow::uint64()),
        arrow::field("market_code", arrow::utf8()),
        arrow::field("operational_halt_action", arrow::utf8()),
        arrow::field("order_reference_number", arrow::uint64()),
        arrow::field("buy_sell_indicator", arrow::utf8()),
        arrow::field("shares", arrow::uint64()),
        arrow::field("price", arrow::decimal128(10, 4)),
        arrow::field("attribution", arrow::utf8()),
        arrow::field("executed_shares", arrow::uint64()),
        arrow::field("match_number", arrow::uint64()),
        arrow::field("printable", arrow::utf8()),
        arrow::field("execution_price", arrow::decimal128(10, 4)),
        arrow::field("canceled_shares", arrow::uint64()),
        arrow::field("original_order_reference_number", arrow::uint64()),
        arrow::field("new_order_reference_number", arrow::uint64()),
        arrow::field("cross_shares", arrow::uint64()),
        arrow::field("cross_price", arrow::decimal128(10, 4)),
        arrow::field("cross_type", arrow::utf8()),
        arrow::field("paired_shares", arrow::uint64()),
        arrow::field("imbalance_shares", arrow::uint64()),
        arrow::field("imbalance_direction", arrow::utf8()),
        arrow::field("far_price", arrow::decimal128(10, 4)),
        arrow::field("near_price", arrow::decimal128(10, 4)),
        arrow::field("current_reference_price", arrow::decimal128(10, 4)),
        arrow::field("price_variation_indicator", arrow::utf8()),
        arrow::field("interest_flag", arrow::utf8()),
    });
}

// One table of every message read, written out as Parquet when it is finished.
class Table {
  public:
    Table()
      : schema_{ schema() } {}

    void append(const itch_totalview::system_event_message& message) {
        message_.append("SystemEventMessage");
        column_0_.append(message.fields.stock_locate.get().value());
        column_1_.append(message.fields.tracking_number.get().value());
        column_2_.append(message.fields.timestamp.get().value());
        column_3_.append(itch_totalview::event_code::to_string(message.fields.event_code.get().value()));
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_39_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        column_55_.null();
        column_56_.null();
        column_57_.null();
        column_58_.null();
        column_59_.null();
        column_60_.null();
        column_61_.null();
        ++rows_;
    }

    void append(const itch_totalview::stock_directory_message& message) {
        message_.append("StockDirectoryMessage");
        column_0_.append(message.fields.stock_locate.get().value());
        column_1_.append(message.fields.tracking_number.get().value());
        column_2_.append(message.fields.timestamp.get().value());
        column_4_.append(message.fields.stock.get_trimmed().value());
        column_5_.append(itch_totalview::market_category::to_string(message.fields.market_category.get().value()));
        column_6_.append(itch_totalview::financial_status_indicator::to_string(message.fields.financial_status_indicator.get().value()));
        column_7_.append(message.fields.round_lot_size.get().value());
        column_8_.append(itch_totalview::round_lots_only::to_string(message.fields.round_lots_only.get().value()));
        column_9_.append(itch_totalview::issue_classification::to_string(message.fields.issue_classification.get().value()));
        column_10_.append(message.fields.issue_sub_type.get_trimmed().value());
        column_11_.append(itch_totalview::authenticity::to_string(message.fields.authenticity.get().value()));
        column_12_.append(itch_totalview::short_sale_threshold_indicator::to_string(message.fields.short_sale_threshold_indicator.get().value()));
        column_13_.append(itch_totalview::ipo_flag::to_string(message.fields.ipo_flag.get().value()));
        column_14_.append(itch_totalview::luld_reference_price_tier::to_string(message.fields.luld_reference_price_tier.get().value()));
        column_15_.append(itch_totalview::etp_flag::to_string(message.fields.etp_flag.get().value()));
        column_16_.append(message.fields.etp_leverage_factor.get().value());
        column_17_.append(itch_totalview::inverse_indicator::to_string(message.fields.inverse_indicator.get().value()));
        column_3_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_39_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        column_55_.null();
        column_56_.null();
        column_57_.null();
        column_58_.null();
        column_59_.null();
        column_60_.null();
        column_61_.null();
        ++rows_;
    }

    void append(const itch_totalview::stock_trading_action_message& message) {
        message_.append("StockTradingActionMessage");
        column_0_.append(message.fields.stock_locate.get().value());
        column_1_.append(message.fields.tracking_number.get().value());
        column_2_.append(message.fields.timestamp.get().value());
        column_4_.append(message.fields.stock.get_trimmed().value());
        column_18_.append(itch_totalview::trading_state::to_string(message.fields.trading_state.get().value()));
        column_19_.append(message.fields.reason_code.get_trimmed().value());
        column_3_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_39_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        column_55_.null();
        column_56_.null();
        column_57_.null();
        column_58_.null();
        column_59_.null();
        column_60_.null();
        column_61_.null();
        ++rows_;
    }

    void append(const itch_totalview::reg_sho_short_sale_price_test_restricted_indicator_message& message) {
        message_.append("RegShoShortSalePriceTestRestrictedIndicatorMessage");
        column_20_.append(message.fields.locate_code.get().value());
        column_1_.append(message.fields.tracking_number.get().value());
        column_2_.append(message.fields.timestamp.get().value());
        column_4_.append(message.fields.stock.get_trimmed().value());
        column_21_.append(itch_totalview::reg_sho_action::to_string(message.fields.reg_sho_action.get().value()));
        column_0_.null();
        column_3_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_39_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        column_55_.null();
        column_56_.null();
        column_57_.null();
        column_58_.null();
        column_59_.null();
        column_60_.null();
        column_61_.null();
        ++rows_;
    }

    void append(const itch_totalview::market_participant_position_message& message) {
        message_.append("MarketParticipantPositionMessage");
        column_0_.append(message.fields.stock_locate.get().value());
        column_1_.append(message.fields.tracking_number.get().value());
        column_2_.append(message.fields.timestamp.get().value());
        column_22_.append(message.fields.mpid.get_trimmed().value());
        column_4_.append(message.fields.stock.get_trimmed().value());
        column_23_.append(itch_totalview::primary_market_maker::to_string(message.fields.primary_market_maker.get().value()));
        column_24_.append(itch_totalview::market_maker_mode::to_string(message.fields.market_maker_mode.get().value()));
        column_25_.append(itch_totalview::market_participant_state::to_string(message.fields.market_participant_state.get().value()));
        column_3_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_39_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        column_55_.null();
        column_56_.null();
        column_57_.null();
        column_58_.null();
        column_59_.null();
        column_60_.null();
        column_61_.null();
        ++rows_;
    }

    void append(const itch_totalview::mwcb_decline_level_message& message) {
        message_.append("MwcbDeclineLevelMessage");
        column_0_.append(message.fields.stock_locate.get().value());
        column_1_.append(message.fields.tracking_number.get().value());
        column_2_.append(message.fields.timestamp.get().value());
        column_26_.append(message.fields.level_1.get().value());
        column_27_.append(message.fields.level_2.get().value());
        column_28_.append(message.fields.level_3.get().value());
        column_3_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_39_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        column_55_.null();
        column_56_.null();
        column_57_.null();
        column_58_.null();
        column_59_.null();
        column_60_.null();
        column_61_.null();
        ++rows_;
    }

    void append(const itch_totalview::mwcb_status_level_message& message) {
        message_.append("MwcbStatusLevelMessage");
        column_0_.append(message.fields.stock_locate.get().value());
        column_1_.append(message.fields.tracking_number.get().value());
        column_2_.append(message.fields.timestamp.get().value());
        column_29_.append(itch_totalview::breached_level::to_string(message.fields.breached_level.get().value()));
        column_3_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_39_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        column_55_.null();
        column_56_.null();
        column_57_.null();
        column_58_.null();
        column_59_.null();
        column_60_.null();
        column_61_.null();
        ++rows_;
    }

    void append(const itch_totalview::ipo_quoting_period_update& message) {
        message_.append("IpoQuotingPeriodUpdate");
        column_0_.append(message.fields.stock_locate.get().value());
        column_1_.append(message.fields.tracking_number.get().value());
        column_2_.append(message.fields.timestamp.get().value());
        column_4_.append(message.fields.stock.get_trimmed().value());
        column_30_.append(message.fields.ipo_quotation_release_time.get().value());
        column_31_.append(itch_totalview::ipo_quotation_release_qualifier::to_string(message.fields.ipo_quotation_release_qualifier.get().value()));
        column_32_.append(message.fields.ipo_price.get().value());
        column_3_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_39_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        column_55_.null();
        column_56_.null();
        column_57_.null();
        column_58_.null();
        column_59_.null();
        column_60_.null();
        column_61_.null();
        ++rows_;
    }

    void append(const itch_totalview::luld_auction_collar_message& message) {
        message_.append("LuldAuctionCollarMessage");
        column_0_.append(message.fields.stock_locate.get().value());
        column_1_.append(message.fields.tracking_number.get().value());
        column_2_.append(message.fields.timestamp.get().value());
        column_4_.append(message.fields.stock.get_trimmed().value());
        column_33_.append(message.fields.auction_collar_reference_price.get().value());
        column_34_.append(message.fields.upper_auction_collar_price.get().value());
        column_35_.append(message.fields.lower_auction_collar_price.get().value());
        column_36_.append(message.fields.auction_collar_extension.get().value());
        column_3_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_37_.null();
        column_38_.null();
        column_39_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        column_55_.null();
        column_56_.null();
        column_57_.null();
        column_58_.null();
        column_59_.null();
        column_60_.null();
        column_61_.null();
        ++rows_;
    }

    void append(const itch_totalview::operational_halt_message& message) {
        message_.append("OperationalHaltMessage");
        column_0_.append(message.fields.stock_locate.get().value());
        column_1_.append(message.fields.tracking_number.get().value());
        column_2_.append(message.fields.timestamp.get().value());
        column_4_.append(message.fields.stock.get_trimmed().value());
        column_37_.append(itch_totalview::market_code::to_string(message.fields.market_code.get().value()));
        column_38_.append(itch_totalview::operational_halt_action::to_string(message.fields.operational_halt_action.get().value()));
        column_3_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_39_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        column_55_.null();
        column_56_.null();
        column_57_.null();
        column_58_.null();
        column_59_.null();
        column_60_.null();
        column_61_.null();
        ++rows_;
    }

    void append(const itch_totalview::add_order_no_mpid_attribution_message& message) {
        message_.append("AddOrderNoMpidAttributionMessage");
        column_0_.append(message.fields.stock_locate.get().value());
        column_1_.append(message.fields.tracking_number.get().value());
        column_2_.append(message.fields.timestamp.get().value());
        column_39_.append(message.fields.order_reference_number.get().value());
        column_40_.append(itch_totalview::buy_sell_indicator::to_string(message.fields.buy_sell_indicator.get().value()));
        column_41_.append(message.fields.shares.get().value());
        column_4_.append(message.fields.stock.get_trimmed().value());
        column_42_.append(message.fields.price.get().value());
        column_3_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_43_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        column_55_.null();
        column_56_.null();
        column_57_.null();
        column_58_.null();
        column_59_.null();
        column_60_.null();
        column_61_.null();
        ++rows_;
    }

    void append(const itch_totalview::add_order_with_mpid_attribution_message& message) {
        message_.append("AddOrderWithMpidAttributionMessage");
        column_0_.append(message.fields.stock_locate.get().value());
        column_1_.append(message.fields.tracking_number.get().value());
        column_2_.append(message.fields.timestamp.get().value());
        column_39_.append(message.fields.order_reference_number.get().value());
        column_40_.append(itch_totalview::buy_sell_indicator::to_string(message.fields.buy_sell_indicator.get().value()));
        column_41_.append(message.fields.shares.get().value());
        column_4_.append(message.fields.stock.get_trimmed().value());
        column_42_.append(message.fields.price.get().value());
        column_43_.append(message.fields.attribution.get_trimmed().value());
        column_3_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        column_55_.null();
        column_56_.null();
        column_57_.null();
        column_58_.null();
        column_59_.null();
        column_60_.null();
        column_61_.null();
        ++rows_;
    }

    void append(const itch_totalview::order_executed_message& message) {
        message_.append("OrderExecutedMessage");
        column_0_.append(message.fields.stock_locate.get().value());
        column_1_.append(message.fields.tracking_number.get().value());
        column_2_.append(message.fields.timestamp.get().value());
        column_39_.append(message.fields.order_reference_number.get().value());
        column_44_.append(message.fields.executed_shares.get().value());
        column_45_.append(message.fields.match_number.get().value());
        column_3_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        column_55_.null();
        column_56_.null();
        column_57_.null();
        column_58_.null();
        column_59_.null();
        column_60_.null();
        column_61_.null();
        ++rows_;
    }

    void append(const itch_totalview::order_executed_with_price_message& message) {
        message_.append("OrderExecutedWithPriceMessage");
        column_0_.append(message.fields.stock_locate.get().value());
        column_1_.append(message.fields.tracking_number.get().value());
        column_2_.append(message.fields.timestamp.get().value());
        column_39_.append(message.fields.order_reference_number.get().value());
        column_44_.append(message.fields.executed_shares.get().value());
        column_45_.append(message.fields.match_number.get().value());
        column_46_.append(itch_totalview::printable::to_string(message.fields.printable.get().value()));
        column_47_.append(message.fields.execution_price.get().value());
        column_3_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        column_55_.null();
        column_56_.null();
        column_57_.null();
        column_58_.null();
        column_59_.null();
        column_60_.null();
        column_61_.null();
        ++rows_;
    }

    void append(const itch_totalview::order_cancel_message& message) {
        message_.append("OrderCancelMessage");
        column_0_.append(message.fields.stock_locate.get().value());
        column_1_.append(message.fields.tracking_number.get().value());
        column_2_.append(message.fields.timestamp.get().value());
        column_39_.append(message.fields.order_reference_number.get().value());
        column_48_.append(message.fields.canceled_shares.get().value());
        column_3_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        column_55_.null();
        column_56_.null();
        column_57_.null();
        column_58_.null();
        column_59_.null();
        column_60_.null();
        column_61_.null();
        ++rows_;
    }

    void append(const itch_totalview::order_delete_message& message) {
        message_.append("OrderDeleteMessage");
        column_0_.append(message.fields.stock_locate.get().value());
        column_1_.append(message.fields.tracking_number.get().value());
        column_2_.append(message.fields.timestamp.get().value());
        column_39_.append(message.fields.order_reference_number.get().value());
        column_3_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        column_55_.null();
        column_56_.null();
        column_57_.null();
        column_58_.null();
        column_59_.null();
        column_60_.null();
        column_61_.null();
        ++rows_;
    }

    void append(const itch_totalview::order_replace_message& message) {
        message_.append("OrderReplaceMessage");
        column_0_.append(message.fields.stock_locate.get().value());
        column_1_.append(message.fields.tracking_number.get().value());
        column_2_.append(message.fields.timestamp.get().value());
        column_49_.append(message.fields.original_order_reference_number.get().value());
        column_50_.append(message.fields.new_order_reference_number.get().value());
        column_41_.append(message.fields.shares.get().value());
        column_42_.append(message.fields.price.get().value());
        column_3_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_39_.null();
        column_40_.null();
        column_43_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        column_55_.null();
        column_56_.null();
        column_57_.null();
        column_58_.null();
        column_59_.null();
        column_60_.null();
        column_61_.null();
        ++rows_;
    }

    void append(const itch_totalview::non_cross_trade_message& message) {
        message_.append("NonCrossTradeMessage");
        column_0_.append(message.fields.stock_locate.get().value());
        column_1_.append(message.fields.tracking_number.get().value());
        column_2_.append(message.fields.timestamp.get().value());
        column_39_.append(message.fields.order_reference_number.get().value());
        column_40_.append(itch_totalview::buy_sell_indicator::to_string(message.fields.buy_sell_indicator.get().value()));
        column_41_.append(message.fields.shares.get().value());
        column_4_.append(message.fields.stock.get_trimmed().value());
        column_42_.append(message.fields.price.get().value());
        column_45_.append(message.fields.match_number.get().value());
        column_3_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_43_.null();
        column_44_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        column_55_.null();
        column_56_.null();
        column_57_.null();
        column_58_.null();
        column_59_.null();
        column_60_.null();
        column_61_.null();
        ++rows_;
    }

    void append(const itch_totalview::cross_trade_message& message) {
        message_.append("CrossTradeMessage");
        column_0_.append(message.fields.stock_locate.get().value());
        column_1_.append(message.fields.tracking_number.get().value());
        column_2_.append(message.fields.timestamp.get().value());
        column_51_.append(message.fields.cross_shares.get().value());
        column_4_.append(message.fields.stock.get_trimmed().value());
        column_52_.append(message.fields.cross_price.get().value());
        column_45_.append(message.fields.match_number.get().value());
        column_53_.append(itch_totalview::cross_type::to_string(message.fields.cross_type.get().value()));
        column_3_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_39_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_44_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_54_.null();
        column_55_.null();
        column_56_.null();
        column_57_.null();
        column_58_.null();
        column_59_.null();
        column_60_.null();
        column_61_.null();
        ++rows_;
    }

    void append(const itch_totalview::broken_trade_message& message) {
        message_.append("BrokenTradeMessage");
        column_0_.append(message.fields.stock_locate.get().value());
        column_1_.append(message.fields.tracking_number.get().value());
        column_2_.append(message.fields.timestamp.get().value());
        column_45_.append(message.fields.match_number.get().value());
        column_3_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_39_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_44_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        column_55_.null();
        column_56_.null();
        column_57_.null();
        column_58_.null();
        column_59_.null();
        column_60_.null();
        column_61_.null();
        ++rows_;
    }

    void append(const itch_totalview::net_order_imbalance_indicator_message& message) {
        message_.append("NetOrderImbalanceIndicatorMessage");
        column_0_.append(message.fields.stock_locate.get().value());
        column_1_.append(message.fields.tracking_number.get().value());
        column_2_.append(message.fields.timestamp.get().value());
        column_54_.append(message.fields.paired_shares.get().value());
        column_55_.append(message.fields.imbalance_shares.get().value());
        column_56_.append(itch_totalview::imbalance_direction::to_string(message.fields.imbalance_direction.get().value()));
        column_4_.append(message.fields.stock.get_trimmed().value());
        column_57_.append(message.fields.far_price.get().value());
        column_58_.append(message.fields.near_price.get().value());
        column_59_.append(message.fields.current_reference_price.get().value());
        column_53_.append(itch_totalview::cross_type::to_string(message.fields.cross_type.get().value()));
        column_60_.append(itch_totalview::price_variation_indicator::to_string(message.fields.price_variation_indicator.get().value()));
        column_3_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_39_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_61_.null();
        ++rows_;
    }

    void append(const itch_totalview::retail_price_improvement_indicator_message& message) {
        message_.append("RetailPriceImprovementIndicatorMessage");
        column_0_.append(message.fields.stock_locate.get().value());
        column_1_.append(message.fields.tracking_number.get().value());
        column_2_.append(message.fields.timestamp.get().value());
        column_4_.append(message.fields.stock.get_trimmed().value());
        column_61_.append(itch_totalview::interest_flag::to_string(message.fields.interest_flag.get().value()));
        column_3_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        column_34_.null();
        column_35_.null();
        column_36_.null();
        column_37_.null();
        column_38_.null();
        column_39_.null();
        column_40_.null();
        column_41_.null();
        column_42_.null();
        column_43_.null();
        column_44_.null();
        column_45_.null();
        column_46_.null();
        column_47_.null();
        column_48_.null();
        column_49_.null();
        column_50_.null();
        column_51_.null();
        column_52_.null();
        column_53_.null();
        column_54_.null();
        column_55_.null();
        column_56_.null();
        column_57_.null();
        column_58_.null();
        column_59_.null();
        column_60_.null();
        ++rows_;
    }

    // The rows read so far, as an Arrow table
    std::shared_ptr<arrow::Table> finish() {
        std::vector<std::shared_ptr<arrow::Array>> arrays;
        arrays.push_back(message_.finish());
        arrays.push_back(column_0_.finish());
        arrays.push_back(column_1_.finish());
        arrays.push_back(column_2_.finish());
        arrays.push_back(column_3_.finish());
        arrays.push_back(column_4_.finish());
        arrays.push_back(column_5_.finish());
        arrays.push_back(column_6_.finish());
        arrays.push_back(column_7_.finish());
        arrays.push_back(column_8_.finish());
        arrays.push_back(column_9_.finish());
        arrays.push_back(column_10_.finish());
        arrays.push_back(column_11_.finish());
        arrays.push_back(column_12_.finish());
        arrays.push_back(column_13_.finish());
        arrays.push_back(column_14_.finish());
        arrays.push_back(column_15_.finish());
        arrays.push_back(column_16_.finish());
        arrays.push_back(column_17_.finish());
        arrays.push_back(column_18_.finish());
        arrays.push_back(column_19_.finish());
        arrays.push_back(column_20_.finish());
        arrays.push_back(column_21_.finish());
        arrays.push_back(column_22_.finish());
        arrays.push_back(column_23_.finish());
        arrays.push_back(column_24_.finish());
        arrays.push_back(column_25_.finish());
        arrays.push_back(column_26_.finish());
        arrays.push_back(column_27_.finish());
        arrays.push_back(column_28_.finish());
        arrays.push_back(column_29_.finish());
        arrays.push_back(column_30_.finish());
        arrays.push_back(column_31_.finish());
        arrays.push_back(column_32_.finish());
        arrays.push_back(column_33_.finish());
        arrays.push_back(column_34_.finish());
        arrays.push_back(column_35_.finish());
        arrays.push_back(column_36_.finish());
        arrays.push_back(column_37_.finish());
        arrays.push_back(column_38_.finish());
        arrays.push_back(column_39_.finish());
        arrays.push_back(column_40_.finish());
        arrays.push_back(column_41_.finish());
        arrays.push_back(column_42_.finish());
        arrays.push_back(column_43_.finish());
        arrays.push_back(column_44_.finish());
        arrays.push_back(column_45_.finish());
        arrays.push_back(column_46_.finish());
        arrays.push_back(column_47_.finish());
        arrays.push_back(column_48_.finish());
        arrays.push_back(column_49_.finish());
        arrays.push_back(column_50_.finish());
        arrays.push_back(column_51_.finish());
        arrays.push_back(column_52_.finish());
        arrays.push_back(column_53_.finish());
        arrays.push_back(column_54_.finish());
        arrays.push_back(column_55_.finish());
        arrays.push_back(column_56_.finish());
        arrays.push_back(column_57_.finish());
        arrays.push_back(column_58_.finish());
        arrays.push_back(column_59_.finish());
        arrays.push_back(column_60_.finish());
        arrays.push_back(column_61_.finish());
        return arrow::Table::Make(schema_, arrays, rows_);
    }

    std::int64_t rows() const { return rows_; }

  private:
    std::shared_ptr<arrow::Schema> schema_;
    std::int64_t rows_ = 0;
    omi::parquet::wide::Text message_{  };
    omi::parquet::wide::Unsigned column_0_{  };   // stock_locate
    omi::parquet::wide::Unsigned column_1_{  };   // tracking_number
    omi::parquet::wide::Unsigned column_2_{  };   // timestamp
    omi::parquet::wide::Text column_3_{  };   // event_code
    omi::parquet::wide::Text column_4_{  };   // stock
    omi::parquet::wide::Text column_5_{  };   // market_category
    omi::parquet::wide::Text column_6_{  };   // financial_status_indicator
    omi::parquet::wide::Unsigned column_7_{  };   // round_lot_size
    omi::parquet::wide::Text column_8_{  };   // round_lots_only
    omi::parquet::wide::Text column_9_{  };   // issue_classification
    omi::parquet::wide::Text column_10_{  };   // issue_sub_type
    omi::parquet::wide::Text column_11_{  };   // authenticity
    omi::parquet::wide::Text column_12_{  };   // short_sale_threshold_indicator
    omi::parquet::wide::Text column_13_{  };   // ipo_flag
    omi::parquet::wide::Text column_14_{  };   // luld_reference_price_tier
    omi::parquet::wide::Text column_15_{  };   // etp_flag
    omi::parquet::wide::Unsigned column_16_{  };   // etp_leverage_factor
    omi::parquet::wide::Text column_17_{  };   // inverse_indicator
    omi::parquet::wide::Text column_18_{  };   // trading_state
    omi::parquet::wide::Text column_19_{  };   // reason_code
    omi::parquet::wide::Unsigned column_20_{  };   // locate_code
    omi::parquet::wide::Text column_21_{  };   // reg_sho_action
    omi::parquet::wide::Text column_22_{  };   // mpid
    omi::parquet::wide::Text column_23_{  };   // primary_market_maker
    omi::parquet::wide::Text column_24_{  };   // market_maker_mode
    omi::parquet::wide::Text column_25_{  };   // market_participant_state
    omi::parquet::wide::Decimal column_26_{ arrow::decimal128(18, 8) };   // level_1
    omi::parquet::wide::Decimal column_27_{ arrow::decimal128(18, 8) };   // level_2
    omi::parquet::wide::Decimal column_28_{ arrow::decimal128(18, 8) };   // level_3
    omi::parquet::wide::Text column_29_{  };   // breached_level
    omi::parquet::wide::Unsigned column_30_{  };   // ipo_quotation_release_time
    omi::parquet::wide::Text column_31_{  };   // ipo_quotation_release_qualifier
    omi::parquet::wide::Decimal column_32_{ arrow::decimal128(10, 4) };   // ipo_price
    omi::parquet::wide::Decimal column_33_{ arrow::decimal128(10, 4) };   // auction_collar_reference_price
    omi::parquet::wide::Decimal column_34_{ arrow::decimal128(10, 4) };   // upper_auction_collar_price
    omi::parquet::wide::Decimal column_35_{ arrow::decimal128(10, 4) };   // lower_auction_collar_price
    omi::parquet::wide::Unsigned column_36_{  };   // auction_collar_extension
    omi::parquet::wide::Text column_37_{  };   // market_code
    omi::parquet::wide::Text column_38_{  };   // operational_halt_action
    omi::parquet::wide::Unsigned column_39_{  };   // order_reference_number
    omi::parquet::wide::Text column_40_{  };   // buy_sell_indicator
    omi::parquet::wide::Unsigned column_41_{  };   // shares
    omi::parquet::wide::Decimal column_42_{ arrow::decimal128(10, 4) };   // price
    omi::parquet::wide::Text column_43_{  };   // attribution
    omi::parquet::wide::Unsigned column_44_{  };   // executed_shares
    omi::parquet::wide::Unsigned column_45_{  };   // match_number
    omi::parquet::wide::Text column_46_{  };   // printable
    omi::parquet::wide::Decimal column_47_{ arrow::decimal128(10, 4) };   // execution_price
    omi::parquet::wide::Unsigned column_48_{  };   // canceled_shares
    omi::parquet::wide::Unsigned column_49_{  };   // original_order_reference_number
    omi::parquet::wide::Unsigned column_50_{  };   // new_order_reference_number
    omi::parquet::wide::Unsigned column_51_{  };   // cross_shares
    omi::parquet::wide::Decimal column_52_{ arrow::decimal128(10, 4) };   // cross_price
    omi::parquet::wide::Text column_53_{  };   // cross_type
    omi::parquet::wide::Unsigned column_54_{  };   // paired_shares
    omi::parquet::wide::Unsigned column_55_{  };   // imbalance_shares
    omi::parquet::wide::Text column_56_{  };   // imbalance_direction
    omi::parquet::wide::Decimal column_57_{ arrow::decimal128(10, 4) };   // far_price
    omi::parquet::wide::Decimal column_58_{ arrow::decimal128(10, 4) };   // near_price
    omi::parquet::wide::Decimal column_59_{ arrow::decimal128(10, 4) };   // current_reference_price
    omi::parquet::wide::Text column_60_{  };   // price_variation_indicator
    omi::parquet::wide::Text column_61_{  };   // interest_flag
};

}
