// Iex.IexEquities.DeepPlus.IexTp.v1.01 messages as one wide Parquet table.
//
// Generated by CppGenerators — do not edit.

#pragma once

#include "cpp/advanced/iex/iexequities/deepplus/iextp/v1.01/messages/Definitions.hpp"
#include "parquet/wide/Table.hpp"

namespace iex::iexequities::deepplus::iextp::v1_01::parquet::wide {

namespace iextp_deepplus = ::iex::iexequities::deepplus::iextp::v1_01;

// The session dispatches every message the protocol has; these are the ones written, asked
// at compile time so a program instantiates nothing for the rest.
template <typename Message>
inline constexpr bool writes = true;

// Every column any message of this protocol holds, the message's own name first.
inline std::shared_ptr<arrow::Schema> schema() {
    return arrow::schema({
        arrow::field("message", arrow::utf8()),
        arrow::field("system_event", arrow::utf8()),
        arrow::field("timestamp", arrow::int64()),
        arrow::field("security_directory_flags", arrow::uint64()),
        arrow::field("symbol", arrow::utf8()),
        arrow::field("round_lot_size", arrow::uint64()),
        arrow::field("adjusted_poc_price", arrow::decimal128(18, 4)),
        arrow::field("luld_tier", arrow::utf8()),
        arrow::field("trading_status", arrow::utf8()),
        arrow::field("reason", arrow::utf8()),
        arrow::field("retail_liquidity_indicator", arrow::utf8()),
        arrow::field("operational_halt_status", arrow::utf8()),
        arrow::field("short_sale_price_test_status", arrow::utf8()),
        arrow::field("detail", arrow::utf8()),
        arrow::field("security_event", arrow::utf8()),
        arrow::field("side", arrow::utf8()),
        arrow::field("order_id", arrow::uint64()),
        arrow::field("size", arrow::uint64()),
        arrow::field("price", arrow::decimal128(18, 4)),
        arrow::field("modify_flags", arrow::uint64()),
        arrow::field("order_id_reference", arrow::uint64()),
        arrow::field("sale_condition_flags", arrow::uint64()),
        arrow::field("trade_id", arrow::uint64()),
    });
}

// One table of every message read, written out as Parquet when it is finished.
class Table {
  public:
    Table()
      : schema_{ schema() } {}

    void append(const iextp_deepplus::system_event_message& message) {
        message_.append("SystemEventMessage");
        column_0_.append(iextp_deepplus::system_event::to_string(message.fields.system_event.get().value()));
        column_1_.append(message.fields.timestamp.get().value());
        column_2_.null();
        column_3_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        ++rows_;
    }

    void append(const iextp_deepplus::security_directory_message& message) {
        message_.append("SecurityDirectoryMessage");
        column_2_.append(message.fields.security_directory_flags.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.symbol.get_trimmed().value());
        column_4_.append(message.fields.round_lot_size.get().value());
        column_5_.append(message.fields.adjusted_poc_price.get().value());
        column_6_.append(iextp_deepplus::luld_tier::to_string(message.fields.luld_tier.get().value()));
        column_0_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        ++rows_;
    }

    void append(const iextp_deepplus::trading_status_message& message) {
        message_.append("TradingStatusMessage");
        column_7_.append(iextp_deepplus::trading_status::to_string(message.fields.trading_status.get().value()));
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.symbol.get_trimmed().value());
        column_8_.append(message.fields.reason.get_trimmed().value());
        column_0_.null();
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        ++rows_;
    }

    void append(const iextp_deepplus::retail_liquidity_indicator_message& message) {
        message_.append("RetailLiquidityIndicatorMessage");
        column_9_.append(iextp_deepplus::retail_liquidity_indicator::to_string(message.fields.retail_liquidity_indicator.get().value()));
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.symbol.get_trimmed().value());
        column_0_.null();
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        ++rows_;
    }

    void append(const iextp_deepplus::operational_halt_status_message& message) {
        message_.append("OperationalHaltStatusMessage");
        column_10_.append(iextp_deepplus::operational_halt_status::to_string(message.fields.operational_halt_status.get().value()));
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.symbol.get_trimmed().value());
        column_0_.null();
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        ++rows_;
    }

    void append(const iextp_deepplus::short_sale_price_test_status_message& message) {
        message_.append("ShortSalePriceTestStatusMessage");
        column_11_.append(iextp_deepplus::short_sale_price_test_status::to_string(message.fields.short_sale_price_test_status.get().value()));
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.symbol.get_trimmed().value());
        column_12_.append(iextp_deepplus::detail::to_string(message.fields.detail.get().value()));
        column_0_.null();
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        ++rows_;
    }

    void append(const iextp_deepplus::security_event_message& message) {
        message_.append("SecurityEventMessage");
        column_13_.append(iextp_deepplus::security_event::to_string(message.fields.security_event.get().value()));
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.symbol.get_trimmed().value());
        column_0_.null();
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        ++rows_;
    }

    void append(const iextp_deepplus::add_order_message& message) {
        message_.append("AddOrderMessage");
        column_14_.append(iextp_deepplus::side::to_string(message.fields.side.get().value()));
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.symbol.get_trimmed().value());
        column_15_.append(message.fields.order_id.get().value());
        column_16_.append(message.fields.size.get().value());
        column_17_.append(message.fields.price.get().value());
        column_0_.null();
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        ++rows_;
    }

    void append(const iextp_deepplus::order_modify_message& message) {
        message_.append("OrderModifyMessage");
        column_18_.append(message.fields.modify_flags.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.symbol.get_trimmed().value());
        column_19_.append(message.fields.order_id_reference.get().value());
        column_16_.append(message.fields.size.get().value());
        column_17_.append(message.fields.price.get().value());
        column_0_.null();
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_20_.null();
        column_21_.null();
        ++rows_;
    }

    void append(const iextp_deepplus::order_delete_message& message) {
        message_.append("OrderDeleteMessage");
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.symbol.get_trimmed().value());
        column_19_.append(message.fields.order_id_reference.get().value());
        column_0_.null();
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_20_.null();
        column_21_.null();
        ++rows_;
    }

    void append(const iextp_deepplus::order_executed_message& message) {
        message_.append("OrderExecutedMessage");
        column_20_.append(message.fields.sale_condition_flags.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.symbol.get_trimmed().value());
        column_19_.append(message.fields.order_id_reference.get().value());
        column_16_.append(message.fields.size.get().value());
        column_17_.append(message.fields.price.get().value());
        column_21_.append(message.fields.trade_id.get().value());
        column_0_.null();
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_18_.null();
        ++rows_;
    }

    void append(const iextp_deepplus::trade_message& message) {
        message_.append("TradeMessage");
        column_20_.append(message.fields.sale_condition_flags.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.symbol.get_trimmed().value());
        column_16_.append(message.fields.size.get().value());
        column_17_.append(message.fields.price.get().value());
        column_21_.append(message.fields.trade_id.get().value());
        column_0_.null();
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_18_.null();
        column_19_.null();
        ++rows_;
    }

    void append(const iextp_deepplus::trade_break_message& message) {
        message_.append("TradeBreakMessage");
        column_20_.append(message.fields.sale_condition_flags.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.symbol.get_trimmed().value());
        column_16_.append(message.fields.size.get().value());
        column_17_.append(message.fields.price.get().value());
        column_21_.append(message.fields.trade_id.get().value());
        column_0_.null();
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_18_.null();
        column_19_.null();
        ++rows_;
    }

    void append(const iextp_deepplus::clear_book_message& message) {
        message_.append("ClearBookMessage");
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.symbol.get_trimmed().value());
        column_0_.null();
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        ++rows_;
    }

    // The rows read so far, as an Arrow table
    std::shared_ptr<arrow::Table> finish() {
        std::vector<std::shared_ptr<arrow::Array>> arrays;
        arrays.push_back(message_.finish());
        arrays.push_back(column_0_.finish());
        arrays.push_back(column_1_.finish());
        arrays.push_back(column_2_.finish());
        arrays.push_back(column_3_.finish());
        arrays.push_back(column_4_.finish());
        arrays.push_back(column_5_.finish());
        arrays.push_back(column_6_.finish());
        arrays.push_back(column_7_.finish());
        arrays.push_back(column_8_.finish());
        arrays.push_back(column_9_.finish());
        arrays.push_back(column_10_.finish());
        arrays.push_back(column_11_.finish());
        arrays.push_back(column_12_.finish());
        arrays.push_back(column_13_.finish());
        arrays.push_back(column_14_.finish());
        arrays.push_back(column_15_.finish());
        arrays.push_back(column_16_.finish());
        arrays.push_back(column_17_.finish());
        arrays.push_back(column_18_.finish());
        arrays.push_back(column_19_.finish());
        arrays.push_back(column_20_.finish());
        arrays.push_back(column_21_.finish());
        return arrow::Table::Make(schema_, arrays, rows_);
    }

    std::int64_t rows() const { return rows_; }

  private:
    std::shared_ptr<arrow::Schema> schema_;
    std::int64_t rows_ = 0;
    omi::parquet::wide::Text message_{  };
    omi::parquet::wide::Text column_0_{  };   // system_event
    omi::parquet::wide::Signed column_1_{  };   // timestamp
    omi::parquet::wide::Unsigned column_2_{  };   // security_directory_flags
    omi::parquet::wide::Text column_3_{  };   // symbol
    omi::parquet::wide::Unsigned column_4_{  };   // round_lot_size
    omi::parquet::wide::Decimal column_5_{ arrow::decimal128(18, 4) };   // adjusted_poc_price
    omi::parquet::wide::Text column_6_{  };   // luld_tier
    omi::parquet::wide::Text column_7_{  };   // trading_status
    omi::parquet::wide::Text column_8_{  };   // reason
    omi::parquet::wide::Text column_9_{  };   // retail_liquidity_indicator
    omi::parquet::wide::Text column_10_{  };   // operational_halt_status
    omi::parquet::wide::Text column_11_{  };   // short_sale_price_test_status
    omi::parquet::wide::Text column_12_{  };   // detail
    omi::parquet::wide::Text column_13_{  };   // security_event
    omi::parquet::wide::Text column_14_{  };   // side
    omi::parquet::wide::Unsigned column_15_{  };   // order_id
    omi::parquet::wide::Unsigned column_16_{  };   // size
    omi::parquet::wide::Decimal column_17_{ arrow::decimal128(18, 4) };   // price
    omi::parquet::wide::Unsigned column_18_{  };   // modify_flags
    omi::parquet::wide::Unsigned column_19_{  };   // order_id_reference
    omi::parquet::wide::Unsigned column_20_{  };   // sale_condition_flags
    omi::parquet::wide::Unsigned column_21_{  };   // trade_id
};

}
