// Nasdaq.NsmEquities.Qbbo.Itch.v2.1 messages as JSON, written through RapidJSON.
//
// Generated by CppGenerators — do not edit.

#pragma once

#include "cpp/advanced/nasdaq/nsmequities/qbbo/itch/v2.1/messages/Definitions.hpp"
#include "json/rapid/Values.hpp"

namespace nasdaq::nsmequities::qbbo::itch::v2_1::json::rapid {

namespace itch_qbbo = ::nasdaq::nsmequities::qbbo::itch::v2_1;

// The session dispatches every message the protocol has; these are the ones written, asked
// at compile time so a program instantiates nothing for the rest.
template <typename Message>
inline constexpr bool writes = true;

template <typename Writer>
void write(Writer& writer, const itch_qbbo::system_event_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("SystemEventMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("time_stamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.time_stamp.get().value()));
    writer.Key("event_code");
    omi::json::rapid::text(writer, itch_qbbo::event_code::to_string(message.fields.event_code.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_qbbo::stock_directory_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("StockDirectoryMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("time_stamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.time_stamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("market_category");
    omi::json::rapid::text(writer, itch_qbbo::market_category::to_string(message.fields.market_category.get().value()));
    writer.Key("financial_status_indicator");
    omi::json::rapid::text(writer, itch_qbbo::financial_status_indicator::to_string(message.fields.financial_status_indicator.get().value()));
    writer.Key("round_lot_size");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.round_lot_size.get().value()));
    writer.Key("round_lots_only");
    omi::json::rapid::text(writer, itch_qbbo::round_lots_only::to_string(message.fields.round_lots_only.get().value()));
    writer.Key("issue_classification");
    omi::json::rapid::text(writer, itch_qbbo::issue_classification::to_string(message.fields.issue_classification.get().value()));
    writer.Key("issue_subtype");
    omi::json::rapid::text(writer, message.fields.issue_subtype.get_trimmed().value());
    writer.Key("authenticity");
    omi::json::rapid::text(writer, itch_qbbo::authenticity::to_string(message.fields.authenticity.get().value()));
    writer.Key("short_sale_threshold_indicator");
    omi::json::rapid::text(writer, itch_qbbo::short_sale_threshold_indicator::to_string(message.fields.short_sale_threshold_indicator.get().value()));
    writer.Key("ipo_flag");
    omi::json::rapid::text(writer, itch_qbbo::ipo_flag::to_string(message.fields.ipo_flag.get().value()));
    writer.Key("luld_reference_price_tier");
    omi::json::rapid::text(writer, itch_qbbo::luld_reference_price_tier::to_string(message.fields.luld_reference_price_tier.get().value()));
    writer.Key("etp_flag");
    omi::json::rapid::text(writer, itch_qbbo::etp_flag::to_string(message.fields.etp_flag.get().value()));
    writer.Key("etp_leverage_factor");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.etp_leverage_factor.get().value()));
    writer.Key("inverse_indicator");
    omi::json::rapid::text(writer, itch_qbbo::inverse_indicator::to_string(message.fields.inverse_indicator.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_qbbo::stock_trading_action_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("StockTradingActionMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("time_stamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.time_stamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("security_class");
    omi::json::rapid::text(writer, itch_qbbo::security_class::to_string(message.fields.security_class.get().value()));
    writer.Key("current_trading_state");
    omi::json::rapid::text(writer, itch_qbbo::current_trading_state::to_string(message.fields.current_trading_state.get().value()));
    writer.Key("reason");
    omi::json::rapid::text(writer, message.fields.reason.get_trimmed().value());
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_qbbo::reg_sho_restriction_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("RegShoRestrictionMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("time_stamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.time_stamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("reg_sho_action");
    omi::json::rapid::text(writer, itch_qbbo::reg_sho_action::to_string(message.fields.reg_sho_action.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_qbbo::mwcb_decline_level_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("MwcbDeclineLevelMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("time_stamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.time_stamp.get().value()));
    writer.Key("level_1");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.level_1.get().value()), itch_qbbo::level_1::exponent);
    writer.Key("level_2");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.level_2.get().value()), itch_qbbo::level_2::exponent);
    writer.Key("level_3");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.level_3.get().value()), itch_qbbo::level_3::exponent);
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_qbbo::mwcb_breach_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("MwcbBreachMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("time_stamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.time_stamp.get().value()));
    writer.Key("breached_level");
    omi::json::rapid::text(writer, itch_qbbo::breached_level::to_string(message.fields.breached_level.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_qbbo::operational_halt_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("OperationalHaltMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("time_stamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.time_stamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("market_code");
    omi::json::rapid::text(writer, itch_qbbo::market_code::to_string(message.fields.market_code.get().value()));
    writer.Key("operational_halt_action");
    omi::json::rapid::text(writer, itch_qbbo::operational_halt_action::to_string(message.fields.operational_halt_action.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_qbbo::bbo_quotation_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("BboQuotationMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("time_stamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.time_stamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("security_class");
    omi::json::rapid::text(writer, itch_qbbo::security_class::to_string(message.fields.security_class.get().value()));
    writer.Key("best_bid_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.best_bid_price.get().value()), itch_qbbo::best_bid_price::exponent);
    writer.Key("best_bid_size");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.best_bid_size.get().value()));
    writer.Key("best_offer_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.best_offer_price.get().value()), itch_qbbo::best_offer_price::exponent);
    writer.Key("best_offer_size");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.best_offer_size.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_qbbo::price_improvement_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("PriceImprovementMessage");
    writer.Key("tracking");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking.get().value()));
    writer.Key("time_stamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.time_stamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("interest_flag");
    omi::json::rapid::text(writer, itch_qbbo::interest_flag::to_string(message.fields.interest_flag.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_qbbo::ipo_quoting_period_update_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("IpoQuotingPeriodUpdateMessage");
    writer.Key("tracking");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking.get().value()));
    writer.Key("time_stamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.time_stamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("ipo_quotation_release_time");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.ipo_quotation_release_time.get().value()));
    writer.Key("ipo_quotation_release_qualifier");
    omi::json::rapid::text(writer, itch_qbbo::ipo_quotation_release_qualifier::to_string(message.fields.ipo_quotation_release_qualifier.get().value()));
    writer.Key("ipo_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.ipo_price.get().value()), itch_qbbo::ipo_price::exponent);
    writer.EndObject();
}

}
