// Iex.IexEquities.Deep.IexTp.v1.08 native json tests over the packet corpus.
//
// Generated by CppGenerators — do not edit.

#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

#include "PcapIterator.hpp"
#include "Frame.hpp"
#include "cpp/advanced/iex/iexequities/deep/iextp/v1.08/messages/session.hpp"
#include "json/native/iex/iexequities/deep/iextp/v1.08/Json.hpp"

namespace protocol = ::iex::iexequities::deep::iextp::v1_08;

namespace {

int failures = 0;

// Corpus checkout the captures are read from.
std::string root() {
    const char* value = std::getenv("OMI_PACKETS_DIR");

    if (value == nullptr) {
        std::printf("FAIL: OMI_PACKETS_DIR is not set\n");
        std::exit(1);
    }

    return std::string{ value };
}

// A validator for the one shape the writer produces, a flat object of keyed strings, numbers and
// nulls: it accepts exactly what RFC 8259 allows of that shape, and nothing trailing.
class Validator {
  public:
    explicit Validator(std::string_view text)
      : text_{ text } {}

    bool object() {
        if (!take('{')) { return false; }
        if (take('}')) { return at_end(); }

        do {
            if (!string() || !take(':') || !value()) { return false; }
        } while (take(','));

        return take('}') && at_end();
    }

  private:
    bool value() {
        if (peek() == '"') { return string(); }
        if (text_.substr(position_, 4) == "null") { position_ += 4; return true; }
        return number();
    }

    bool string() {
        if (!take('"')) { return false; }

        while (position_ < text_.size()) {
            const auto character = static_cast<unsigned char>(text_[position_++]);

            if (character == '"') { return true; }
            if (character < 0x20) { return false; }

            if (character == '\\') {
                if (position_ >= text_.size()) { return false; }

                const char escaped = text_[position_++];

                if (escaped == 'u') {
                    for (int digit = 0; digit < 4; ++digit) {
                        if (position_ >= text_.size() || !hex(text_[position_++])) { return false; }
                    }
                } else if (std::string_view{ "\"\\/bfnrt" }.find(escaped) == std::string_view::npos) {
                    return false;
                }
            }
        }

        return false;
    }

    bool number() {
        take('-');

        if (take('0')) {
        } else if (!digits()) {
            return false;
        }

        if (take('.') && !digits()) { return false; }

        if (peek() == 'e' || peek() == 'E') {
            ++position_;
            if (!take('+')) { take('-'); }
            if (!digits()) { return false; }
        }

        return true;
    }

    bool digits() {
        const auto start = position_;
        while (position_ < text_.size() && text_[position_] >= '0' && text_[position_] <= '9') { ++position_; }
        return position_ > start;
    }

    static bool hex(char character) {
        return (character >= '0' && character <= '9') || (character >= 'a' && character <= 'f') || (character >= 'A' && character <= 'F');
    }

    char peek() const { return position_ < text_.size() ? text_[position_] : '\0'; }
    bool take(char expected) { if (peek() != expected) { return false; } ++position_; return true; }
    bool at_end() const { return position_ == text_.size(); }

    std::string_view text_;
    std::size_t position_ = 0;
};

bool valid(std::string_view line) {
    return Validator{ line }.object();
}

// The handler the session layer dispatches into: each message is written, validated and counted.
struct Checker {
    std::string expected;
    std::string text{};
    std::size_t messages = 0;
    std::size_t matched = 0;
    std::size_t invalid = 0;

    protocol::seq_action on_transport_header(const protocol::iextp_header&, const packet::Frame&) {
        return protocol::seq_action::process;
    }

    template <typename Message>
    void on_message(const Message& message, std::uint64_t, const protocol::iextp_header&) {
        if constexpr (protocol::json::native::writes<Message>) {
            text.clear();
            omi::json::native::Writer writer{ text };
            protocol::json::native::write(writer, message);
            const std::string_view line{ text };
            ++messages;

            if (!valid(line)) {
                ++invalid;
                std::printf("    invalid JSON: %.*s\n", static_cast<int>(line.size()), line.data());
            }

            if (line.starts_with(expected)) { ++matched; }
        }
    }
};

// Write every message of a capture and require it all to be valid JSON, with the expected message in it.
void expect(const char* name, const char* relative) {
    std::vector<std::pair<std::string, std::int64_t>> sources;
    sources.emplace_back(root() + "/" + relative, 0);

    packet::PcapIterator captures(sources);
    Checker checker{ std::string{ "{\"message\":\"" } + name + "\"" };
    std::size_t frames = 0;

    while (captures.advance()) {
        const packet::Frame frame(captures.data(), captures.length());

        if (!frame.valid()) { continue; }

        ++frames;
        protocol::process_segment(checker, frame.payload, frame.payload_len, 0, frame);
    }

    if (frames == 0 || checker.messages == 0) {
        std::printf("FAIL %s: no messages written from capture\n", name);
        ++failures;
        return;
    }

    if (checker.invalid > 0 || checker.matched == 0) {
        std::printf("FAIL %s: %zu of %zu messages valid JSON, %zu of the expected message\n",
            name, checker.messages - checker.invalid, checker.messages, checker.matched);
        ++failures;
        return;
    }

    std::printf("ok   %s: %zu messages written as valid JSON, %zu of them the expected message\n", name, checker.messages, checker.matched);
}

}

int main() {
    std::printf("== Iex.IexEquities.Deep.IexTp.v1.08 (native json)\n");
    expect("AuctionInformationMessage", "Iex/IexEquities.Deep.IexTp.v1.08/AuctionInformationMessage.pcap");
    expect("OperationalHaltStatusMessage", "Iex/IexEquities.Deep.IexTp.v1.08/OperationalHaltStatusMessage.pcap");
    expect("PriceLevelBuyUpdateMessage", "Iex/IexEquities.Deep.IexTp.v1.08/PriceLevelBuyUpdateMessage.pcap");
    expect("PriceLevelSellUpdateMessage", "Iex/IexEquities.Deep.IexTp.v1.08/PriceLevelSellUpdateMessage.pcap");
    expect("RetailLiquidityIndicatorMessage", "Iex/IexEquities.Deep.IexTp.v1.08/RetailLiquidityIndicatorMessage.pcap");
    expect("SecurityEventMessage", "Iex/IexEquities.Deep.IexTp.v1.08/SecurityEventMessage.pcap");
    expect("ShortSalePriceTestStatusMessage", "Iex/IexEquities.Deep.IexTp.v1.08/ShortSalePriceTestStatusMessage.pcap");
    expect("SystemEventMessage", "Iex/IexEquities.Deep.IexTp.v1.08/SystemEventMessage.pcap");
    expect("TradeReportMessage", "Iex/IexEquities.Deep.IexTp.v1.08/TradeReportMessage.pcap");
    expect("TradingStatusMessage", "Iex/IexEquities.Deep.IexTp.v1.08/TradingStatusMessage.pcap");
    return failures == 0 ? 0 : 1;
}
