// Nasdaq.NsmEquities.NoiView.Itch.v3.0.2017 messages as one wide Parquet table.
//
// Generated by CppGenerators — do not edit.

#pragma once

#include "cpp/advanced/nasdaq/nsmequities/noiview/itch/v3.0.2017/messages/Definitions.hpp"
#include "parquet/wide/Table.hpp"

namespace nasdaq::nsmequities::noiview::itch::v3_0_2017::parquet::wide {

namespace itch_noiview = ::nasdaq::nsmequities::noiview::itch::v3_0_2017;

// The session dispatches every message the protocol has; these are the ones written, asked
// at compile time so a program instantiates nothing for the rest.
template <typename Message>
inline constexpr bool writes = true;

// Every column any message of this protocol holds, the message's own name first.
inline std::shared_ptr<arrow::Schema> schema() {
    return arrow::schema({
        arrow::field("message", arrow::utf8()),
        arrow::field("tracking_number", arrow::uint64()),
        arrow::field("timestamp", arrow::uint64()),
        arrow::field("event_code", arrow::utf8()),
        arrow::field("stock", arrow::utf8()),
        arrow::field("market_category", arrow::utf8()),
        arrow::field("financial_status_indicator", arrow::utf8()),
        arrow::field("round_lot_size", arrow::uint64()),
        arrow::field("round_lots_only", arrow::utf8()),
        arrow::field("issue_classification", arrow::utf8()),
        arrow::field("issue_sub_type", arrow::utf8()),
        arrow::field("authenticity", arrow::utf8()),
        arrow::field("short_sale_threshold_indicator", arrow::utf8()),
        arrow::field("ipo_flag", arrow::utf8()),
        arrow::field("luld_reference_price_tier", arrow::utf8()),
        arrow::field("etp_flag", arrow::utf8()),
        arrow::field("etp_leverage_factor", arrow::uint64()),
        arrow::field("inverse_indicator", arrow::utf8()),
        arrow::field("current_trading_state", arrow::utf8()),
        arrow::field("reason", arrow::utf8()),
        arrow::field("reg_sho_action", arrow::utf8()),
        arrow::field("paired_shares", arrow::uint64()),
        arrow::field("imbalance_shares", arrow::uint64()),
        arrow::field("imbalance_direction", arrow::utf8()),
        arrow::field("far_price", arrow::decimal128(10, 4)),
        arrow::field("near_price", arrow::decimal128(10, 4)),
        arrow::field("current_reference_price", arrow::decimal128(10, 4)),
        arrow::field("cross_type", arrow::utf8()),
        arrow::field("price_variation_indicator", arrow::utf8()),
        arrow::field("shares", arrow::uint64()),
        arrow::field("cross_price", arrow::decimal128(10, 4)),
        arrow::field("match_number", arrow::uint64()),
        arrow::field("ipo_quotation_release_time", arrow::uint64()),
        arrow::field("ipo_quotation_release_qualifier", arrow::utf8()),
        arrow::field("ipo_price", arrow::decimal128(10, 4)),
    });
}

// One table of every message read, written out as Parquet when it is finished.
class Table {
  public:
    Table()
      : schema_{ schema() } {}

    void append(const itch_noiview::system_event_message& message) {
        message_.append("SystemEventMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_2_.append(itch_noiview::event_code::to_string(message.fields.event_code.get().value()));
        column_3_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        ++rows_;
    }

    void append(const itch_noiview::stock_directory_message& message) {
        message_.append("StockDirectoryMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.stock.get_trimmed().value());
        column_4_.append(itch_noiview::market_category::to_string(message.fields.market_category.get().value()));
        column_5_.append(itch_noiview::financial_status_indicator::to_string(message.fields.financial_status_indicator.get().value()));
        column_6_.append(message.fields.round_lot_size.get().value());
        column_7_.append(itch_noiview::round_lots_only::to_string(message.fields.round_lots_only.get().value()));
        column_8_.append(message.fields.issue_classification.get().value());
        column_9_.append(message.fields.issue_sub_type.get_trimmed().value());
        column_10_.append(itch_noiview::authenticity::to_string(message.fields.authenticity.get().value()));
        column_11_.append(itch_noiview::short_sale_threshold_indicator::to_string(message.fields.short_sale_threshold_indicator.get().value()));
        column_12_.append(itch_noiview::ipo_flag::to_string(message.fields.ipo_flag.get().value()));
        column_13_.append(itch_noiview::luld_reference_price_tier::to_string(message.fields.luld_reference_price_tier.get().value()));
        column_14_.append(itch_noiview::etp_flag::to_string(message.fields.etp_flag.get().value()));
        column_15_.append(message.fields.etp_leverage_factor.get().value());
        column_16_.append(itch_noiview::inverse_indicator::to_string(message.fields.inverse_indicator.get().value()));
        column_2_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        ++rows_;
    }

    void append(const itch_noiview::stock_trading_action_message& message) {
        message_.append("StockTradingActionMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.stock.get_trimmed().value());
        column_17_.append(itch_noiview::current_trading_state::to_string(message.fields.current_trading_state.get().value()));
        column_18_.append(message.fields.reason.get_trimmed().value());
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        ++rows_;
    }

    void append(const itch_noiview::reg_sho_restriction_message& message) {
        message_.append("RegShoRestrictionMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.stock.get_trimmed().value());
        column_19_.append(itch_noiview::reg_sho_action::to_string(message.fields.reg_sho_action.get().value()));
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        ++rows_;
    }

    void append(const itch_noiview::noii_message& message) {
        message_.append("NoiiMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_20_.append(message.fields.paired_shares.get().value());
        column_21_.append(message.fields.imbalance_shares.get().value());
        column_22_.append(itch_noiview::imbalance_direction::to_string(message.fields.imbalance_direction.get().value()));
        column_3_.append(message.fields.stock.get_trimmed().value());
        column_23_.append(message.fields.far_price.get().value());
        column_24_.append(message.fields.near_price.get().value());
        column_25_.append(message.fields.current_reference_price.get().value());
        column_26_.append(itch_noiview::cross_type::to_string(message.fields.cross_type.get().value()));
        column_27_.append(itch_noiview::price_variation_indicator::to_string(message.fields.price_variation_indicator.get().value()));
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        ++rows_;
    }

    void append(const itch_noiview::cross_trade_message& message) {
        message_.append("CrossTradeMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_28_.append(message.fields.shares.get().value());
        column_3_.append(message.fields.stock.get_trimmed().value());
        column_29_.append(message.fields.cross_price.get().value());
        column_30_.append(message.fields.match_number.get().value());
        column_26_.append(itch_noiview::cross_type::to_string(message.fields.cross_type.get().value()));
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_27_.null();
        column_31_.null();
        column_32_.null();
        column_33_.null();
        ++rows_;
    }

    void append(const itch_noiview::ipo_quoting_period_update_message& message) {
        message_.append("IpoQuotingPeriodUpdateMessage");
        column_0_.append(message.fields.tracking_number.get().value());
        column_1_.append(message.fields.timestamp.get().value());
        column_3_.append(message.fields.stock.get_trimmed().value());
        column_31_.append(message.fields.ipo_quotation_release_time.get().value());
        column_32_.append(itch_noiview::ipo_quotation_release_qualifier::to_string(message.fields.ipo_quotation_release_qualifier.get().value()));
        column_33_.append(message.fields.ipo_price.get().value());
        column_2_.null();
        column_4_.null();
        column_5_.null();
        column_6_.null();
        column_7_.null();
        column_8_.null();
        column_9_.null();
        column_10_.null();
        column_11_.null();
        column_12_.null();
        column_13_.null();
        column_14_.null();
        column_15_.null();
        column_16_.null();
        column_17_.null();
        column_18_.null();
        column_19_.null();
        column_20_.null();
        column_21_.null();
        column_22_.null();
        column_23_.null();
        column_24_.null();
        column_25_.null();
        column_26_.null();
        column_27_.null();
        column_28_.null();
        column_29_.null();
        column_30_.null();
        ++rows_;
    }

    // The rows read so far, as an Arrow table
    std::shared_ptr<arrow::Table> finish() {
        std::vector<std::shared_ptr<arrow::Array>> arrays;
        arrays.push_back(message_.finish());
        arrays.push_back(column_0_.finish());
        arrays.push_back(column_1_.finish());
        arrays.push_back(column_2_.finish());
        arrays.push_back(column_3_.finish());
        arrays.push_back(column_4_.finish());
        arrays.push_back(column_5_.finish());
        arrays.push_back(column_6_.finish());
        arrays.push_back(column_7_.finish());
        arrays.push_back(column_8_.finish());
        arrays.push_back(column_9_.finish());
        arrays.push_back(column_10_.finish());
        arrays.push_back(column_11_.finish());
        arrays.push_back(column_12_.finish());
        arrays.push_back(column_13_.finish());
        arrays.push_back(column_14_.finish());
        arrays.push_back(column_15_.finish());
        arrays.push_back(column_16_.finish());
        arrays.push_back(column_17_.finish());
        arrays.push_back(column_18_.finish());
        arrays.push_back(column_19_.finish());
        arrays.push_back(column_20_.finish());
        arrays.push_back(column_21_.finish());
        arrays.push_back(column_22_.finish());
        arrays.push_back(column_23_.finish());
        arrays.push_back(column_24_.finish());
        arrays.push_back(column_25_.finish());
        arrays.push_back(column_26_.finish());
        arrays.push_back(column_27_.finish());
        arrays.push_back(column_28_.finish());
        arrays.push_back(column_29_.finish());
        arrays.push_back(column_30_.finish());
        arrays.push_back(column_31_.finish());
        arrays.push_back(column_32_.finish());
        arrays.push_back(column_33_.finish());
        return arrow::Table::Make(schema_, arrays, rows_);
    }

    std::int64_t rows() const { return rows_; }

  private:
    std::shared_ptr<arrow::Schema> schema_;
    std::int64_t rows_ = 0;
    omi::parquet::wide::Text message_{  };
    omi::parquet::wide::Unsigned column_0_{  };   // tracking_number
    omi::parquet::wide::Unsigned column_1_{  };   // timestamp
    omi::parquet::wide::Text column_2_{  };   // event_code
    omi::parquet::wide::Text column_3_{  };   // stock
    omi::parquet::wide::Text column_4_{  };   // market_category
    omi::parquet::wide::Text column_5_{  };   // financial_status_indicator
    omi::parquet::wide::Unsigned column_6_{  };   // round_lot_size
    omi::parquet::wide::Text column_7_{  };   // round_lots_only
    omi::parquet::wide::Text column_8_{  };   // issue_classification
    omi::parquet::wide::Text column_9_{  };   // issue_sub_type
    omi::parquet::wide::Text column_10_{  };   // authenticity
    omi::parquet::wide::Text column_11_{  };   // short_sale_threshold_indicator
    omi::parquet::wide::Text column_12_{  };   // ipo_flag
    omi::parquet::wide::Text column_13_{  };   // luld_reference_price_tier
    omi::parquet::wide::Text column_14_{  };   // etp_flag
    omi::parquet::wide::Unsigned column_15_{  };   // etp_leverage_factor
    omi::parquet::wide::Text column_16_{  };   // inverse_indicator
    omi::parquet::wide::Text column_17_{  };   // current_trading_state
    omi::parquet::wide::Text column_18_{  };   // reason
    omi::parquet::wide::Text column_19_{  };   // reg_sho_action
    omi::parquet::wide::Unsigned column_20_{  };   // paired_shares
    omi::parquet::wide::Unsigned column_21_{  };   // imbalance_shares
    omi::parquet::wide::Text column_22_{  };   // imbalance_direction
    omi::parquet::wide::Decimal column_23_{ arrow::decimal128(10, 4) };   // far_price
    omi::parquet::wide::Decimal column_24_{ arrow::decimal128(10, 4) };   // near_price
    omi::parquet::wide::Decimal column_25_{ arrow::decimal128(10, 4) };   // current_reference_price
    omi::parquet::wide::Text column_26_{  };   // cross_type
    omi::parquet::wide::Text column_27_{  };   // price_variation_indicator
    omi::parquet::wide::Unsigned column_28_{  };   // shares
    omi::parquet::wide::Decimal column_29_{ arrow::decimal128(10, 4) };   // cross_price
    omi::parquet::wide::Unsigned column_30_{  };   // match_number
    omi::parquet::wide::Unsigned column_31_{  };   // ipo_quotation_release_time
    omi::parquet::wide::Text column_32_{  };   // ipo_quotation_release_qualifier
    omi::parquet::wide::Decimal column_33_{ arrow::decimal128(10, 4) };   // ipo_price
};

}
