// Iex.IexEquities.Tops.IexTp.v1.64 messages as JSON, written through RapidJSON.
//
// Generated by CppGenerators — do not edit.

#pragma once

#include "cpp/advanced/iex/iexequities/tops/iextp/v1.64/messages/Definitions.hpp"
#include "json/rapid/Values.hpp"

namespace iex::iexequities::tops::iextp::v1_64::json::rapid {

namespace iextp_tops = ::iex::iexequities::tops::iextp::v1_64;

// The session dispatches every message the protocol has; these are the ones written, asked
// at compile time so a program instantiates nothing for the rest.
template <typename Message>
inline constexpr bool writes = true;

template <typename Writer>
void write(Writer& writer, const iextp_tops::system_event_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("SystemEventMessage");
    writer.Key("system_event");
    omi::json::rapid::text(writer, iextp_tops::system_event::to_string(message.fields.system_event.get().value()));
    writer.Key("timestamp");
    writer.Int64(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const iextp_tops::security_directory_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("SecurityDirectoryMessage");
    writer.Key("security_directory_flags");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.security_directory_flags.get().value()));
    writer.Key("timestamp");
    writer.Int64(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.Key("symbol");
    omi::json::rapid::text(writer, message.fields.symbol.get_trimmed().value());
    writer.Key("round_lot_size");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.round_lot_size.get().value()));
    writer.Key("adjusted_poc_price");
    omi::json::rapid::decimal(writer, static_cast<std::int64_t>(message.fields.adjusted_poc_price.get().value()), iextp_tops::adjusted_poc_price::exponent);
    writer.Key("luld_tier");
    omi::json::rapid::text(writer, iextp_tops::luld_tier::to_string(message.fields.luld_tier.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const iextp_tops::trading_status_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("TradingStatusMessage");
    writer.Key("trading_status");
    omi::json::rapid::text(writer, iextp_tops::trading_status::to_string(message.fields.trading_status.get().value()));
    writer.Key("timestamp");
    writer.Int64(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.Key("symbol");
    omi::json::rapid::text(writer, message.fields.symbol.get_trimmed().value());
    writer.Key("reason");
    omi::json::rapid::text(writer, message.fields.reason.get_trimmed().value());
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const iextp_tops::operational_halt_status_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("OperationalHaltStatusMessage");
    writer.Key("operational_halt_status");
    omi::json::rapid::text(writer, iextp_tops::operational_halt_status::to_string(message.fields.operational_halt_status.get().value()));
    writer.Key("timestamp");
    writer.Int64(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.Key("symbol");
    omi::json::rapid::text(writer, message.fields.symbol.get_trimmed().value());
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const iextp_tops::short_sale_price_test_status_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("ShortSalePriceTestStatusMessage");
    writer.Key("short_sale_price_test_status");
    omi::json::rapid::text(writer, iextp_tops::short_sale_price_test_status::to_string(message.fields.short_sale_price_test_status.get().value()));
    writer.Key("timestamp");
    writer.Int64(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.Key("symbol");
    omi::json::rapid::text(writer, message.fields.symbol.get_trimmed().value());
    writer.Key("detail");
    omi::json::rapid::text(writer, iextp_tops::detail::to_string(message.fields.detail.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const iextp_tops::security_event_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("SecurityEventMessage");
    writer.Key("security_event");
    omi::json::rapid::text(writer, iextp_tops::security_event::to_string(message.fields.security_event.get().value()));
    writer.Key("timestamp");
    writer.Int64(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.Key("symbol");
    omi::json::rapid::text(writer, message.fields.symbol.get_trimmed().value());
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const iextp_tops::quote_update_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("QuoteUpdateMessage");
    writer.Key("quote_update_flags");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.quote_update_flags.get().value()));
    writer.Key("timestamp");
    writer.Int64(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.Key("symbol");
    omi::json::rapid::text(writer, message.fields.symbol.get_trimmed().value());
    writer.Key("bid_size");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.bid_size.get().value()));
    writer.Key("bid_price");
    omi::json::rapid::decimal(writer, static_cast<std::int64_t>(message.fields.bid_price.get().value()), iextp_tops::bid_price::exponent);
    writer.Key("ask_price");
    omi::json::rapid::decimal(writer, static_cast<std::int64_t>(message.fields.ask_price.get().value()), iextp_tops::ask_price::exponent);
    writer.Key("ask_size");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.ask_size.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const iextp_tops::trade_report_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("TradeReportMessage");
    writer.Key("sale_condition_flags");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.sale_condition_flags.get().value()));
    writer.Key("timestamp");
    writer.Int64(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.Key("symbol");
    omi::json::rapid::text(writer, message.fields.symbol.get_trimmed().value());
    writer.Key("size");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.size.get().value()));
    writer.Key("price");
    omi::json::rapid::decimal(writer, static_cast<std::int64_t>(message.fields.price.get().value()), iextp_tops::price::exponent);
    writer.Key("trade_id");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.trade_id.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const iextp_tops::official_price_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("OfficialPriceMessage");
    writer.Key("price_type");
    omi::json::rapid::text(writer, iextp_tops::price_type::to_string(message.fields.price_type.get().value()));
    writer.Key("timestamp");
    writer.Int64(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.Key("symbol");
    omi::json::rapid::text(writer, message.fields.symbol.get_trimmed().value());
    writer.Key("official_price");
    omi::json::rapid::decimal(writer, static_cast<std::int64_t>(message.fields.official_price.get().value()), iextp_tops::official_price::exponent);
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const iextp_tops::trade_break_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("TradeBreakMessage");
    writer.Key("sale_condition_flags");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.sale_condition_flags.get().value()));
    writer.Key("timestamp");
    writer.Int64(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.Key("symbol");
    omi::json::rapid::text(writer, message.fields.symbol.get_trimmed().value());
    writer.Key("size");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.size.get().value()));
    writer.Key("price");
    omi::json::rapid::decimal(writer, static_cast<std::int64_t>(message.fields.price.get().value()), iextp_tops::price::exponent);
    writer.Key("trade_id");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.trade_id.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const iextp_tops::auction_information_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("AuctionInformationMessage");
    writer.Key("auction_type");
    omi::json::rapid::text(writer, iextp_tops::auction_type::to_string(message.fields.auction_type.get().value()));
    writer.Key("timestamp");
    writer.Int64(static_cast<std::int64_t>(message.fields.timestamp.get().value()));
    writer.Key("symbol");
    omi::json::rapid::text(writer, message.fields.symbol.get_trimmed().value());
    writer.Key("paired_shares");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.paired_shares.get().value()));
    writer.Key("reference_price");
    omi::json::rapid::decimal(writer, static_cast<std::int64_t>(message.fields.reference_price.get().value()), iextp_tops::reference_price::exponent);
    writer.Key("indicative_clearing_price");
    omi::json::rapid::decimal(writer, static_cast<std::int64_t>(message.fields.indicative_clearing_price.get().value()), iextp_tops::indicative_clearing_price::exponent);
    writer.Key("imbalance_shares");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.imbalance_shares.get().value()));
    writer.Key("imbalance_side");
    omi::json::rapid::text(writer, iextp_tops::imbalance_side::to_string(message.fields.imbalance_side.get().value()));
    writer.Key("extension_number");
    omi::json::rapid::character(writer, message.fields.extension_number.get().value());
    writer.Key("scheduled_auction_time");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.scheduled_auction_time.get().value()));
    writer.Key("auction_book_clearing_price");
    omi::json::rapid::decimal(writer, static_cast<std::int64_t>(message.fields.auction_book_clearing_price.get().value()), iextp_tops::auction_book_clearing_price::exponent);
    writer.Key("collar_reference_price");
    omi::json::rapid::decimal(writer, static_cast<std::int64_t>(message.fields.collar_reference_price.get().value()), iextp_tops::collar_reference_price::exponent);
    writer.Key("lower_auction_collar");
    omi::json::rapid::decimal(writer, static_cast<std::int64_t>(message.fields.lower_auction_collar.get().value()), iextp_tops::lower_auction_collar::exponent);
    writer.Key("upper_auction_collar");
    omi::json::rapid::decimal(writer, static_cast<std::int64_t>(message.fields.upper_auction_collar.get().value()), iextp_tops::upper_auction_collar::exponent);
    writer.EndObject();
}

}
