// Nasdaq.NsmEquities.Level2.Itch.v2.0 messages as JSON, written through RapidJSON.
//
// Generated by CppGenerators — do not edit.

#pragma once

#include "cpp/advanced/nasdaq/nsmequities/level2/itch/v2.0/messages/Definitions.hpp"
#include "json/rapid/Values.hpp"

namespace nasdaq::nsmequities::level2::itch::v2_0::json::rapid {

namespace itch_level2 = ::nasdaq::nsmequities::level2::itch::v2_0;

// The session dispatches every message the protocol has; these are the ones written, asked
// at compile time so a program instantiates nothing for the rest.
template <typename Message>
inline constexpr bool writes = true;

template <typename Writer>
void write(Writer& writer, const itch_level2::system_event_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("SystemEventMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("event_code");
    omi::json::rapid::text(writer, itch_level2::event_code::to_string(message.fields.event_code.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_level2::stock_directory_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("StockDirectoryMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("market_category");
    omi::json::rapid::text(writer, itch_level2::market_category::to_string(message.fields.market_category.get().value()));
    writer.Key("financial_status_indicator");
    omi::json::rapid::text(writer, itch_level2::financial_status_indicator::to_string(message.fields.financial_status_indicator.get().value()));
    writer.Key("round_lot_size");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.round_lot_size.get().value()));
    writer.Key("round_lots_only");
    omi::json::rapid::text(writer, itch_level2::round_lots_only::to_string(message.fields.round_lots_only.get().value()));
    writer.Key("issue_classification");
    omi::json::rapid::text(writer, itch_level2::issue_classification::to_string(message.fields.issue_classification.get().value()));
    writer.Key("issue_subtype");
    omi::json::rapid::text(writer, message.fields.issue_subtype.get_trimmed().value());
    writer.Key("authenticity");
    omi::json::rapid::text(writer, itch_level2::authenticity::to_string(message.fields.authenticity.get().value()));
    writer.Key("short_sale_threshold_indicator");
    omi::json::rapid::text(writer, itch_level2::short_sale_threshold_indicator::to_string(message.fields.short_sale_threshold_indicator.get().value()));
    writer.Key("ipo_flag");
    omi::json::rapid::text(writer, itch_level2::ipo_flag::to_string(message.fields.ipo_flag.get().value()));
    writer.Key("luld_reference_price_tier");
    omi::json::rapid::text(writer, itch_level2::luld_reference_price_tier::to_string(message.fields.luld_reference_price_tier.get().value()));
    writer.Key("etp_flag");
    omi::json::rapid::text(writer, itch_level2::etp_flag::to_string(message.fields.etp_flag.get().value()));
    writer.Key("etp_leverage_factor");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.etp_leverage_factor.get().value()));
    writer.Key("inverse_indicator");
    omi::json::rapid::text(writer, itch_level2::inverse_indicator::to_string(message.fields.inverse_indicator.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_level2::stock_trading_action_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("StockTradingActionMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("current_trading_state");
    omi::json::rapid::text(writer, itch_level2::current_trading_state::to_string(message.fields.current_trading_state.get().value()));
    writer.Key("reason");
    omi::json::rapid::text(writer, message.fields.reason.get_trimmed().value());
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_level2::reg_sho_short_sale_price_test_restricted_indicator_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("RegShoShortSalePriceTestRestrictedIndicatorMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("reg_sho_action");
    omi::json::rapid::text(writer, itch_level2::reg_sho_action::to_string(message.fields.reg_sho_action.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_level2::market_participant_position_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("MarketParticipantPositionMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("mpid");
    omi::json::rapid::text(writer, message.fields.mpid.get_trimmed().value());
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("primary_market_maker");
    omi::json::rapid::text(writer, itch_level2::primary_market_maker::to_string(message.fields.primary_market_maker.get().value()));
    writer.Key("market_maker_mode");
    omi::json::rapid::text(writer, itch_level2::market_maker_mode::to_string(message.fields.market_maker_mode.get().value()));
    writer.Key("market_participant_state");
    omi::json::rapid::text(writer, itch_level2::market_participant_state::to_string(message.fields.market_participant_state.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_level2::operational_halt_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("OperationalHaltMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("market_code");
    omi::json::rapid::text(writer, itch_level2::market_code::to_string(message.fields.market_code.get().value()));
    writer.Key("operational_halt_action");
    omi::json::rapid::text(writer, itch_level2::operational_halt_action::to_string(message.fields.operational_halt_action.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_level2::market_participant_bid_ask_update_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("MarketParticipantBidAskUpdateMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("market_side");
    omi::json::rapid::text(writer, itch_level2::market_side::to_string(message.fields.market_side.get().value()));
    writer.Key("participant_shares");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.participant_shares.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.price.get().value()), itch_level2::price::exponent);
    writer.Key("mpid");
    omi::json::rapid::text(writer, message.fields.mpid.get_trimmed().value());
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_level2::retail_price_interest_indicator_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("RetailPriceInterestIndicatorMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("interest_flag");
    omi::json::rapid::text(writer, itch_level2::interest_flag::to_string(message.fields.interest_flag.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_level2::market_wide_circuit_breaker_decline_level_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("MarketWideCircuitBreakerDeclineLevelMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("level_1");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.level_1.get().value()), itch_level2::level_1::exponent);
    writer.Key("level_2");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.level_2.get().value()), itch_level2::level_2::exponent);
    writer.Key("level_3");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.level_3.get().value()), itch_level2::level_3::exponent);
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_level2::market_wide_circuit_breaker_status_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("MarketWideCircuitBreakerStatusMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("breached_level");
    omi::json::rapid::text(writer, itch_level2::breached_level::to_string(message.fields.breached_level.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_level2::ipo_quoting_period_update_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("IpoQuotingPeriodUpdateMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("ipo_quotation_release_time");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.ipo_quotation_release_time.get().value()));
    writer.Key("ipo_quotation_release_qualifier");
    omi::json::rapid::text(writer, itch_level2::ipo_quotation_release_qualifier::to_string(message.fields.ipo_quotation_release_qualifier.get().value()));
    writer.Key("ipo_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.ipo_price.get().value()), itch_level2::ipo_price::exponent);
    writer.EndObject();
}

}
