// Nasdaq.NsmEquities.TotalView.Itch.v5.0.2018 wide parquet tests over the packet corpus.
//
// Generated by CppGenerators — do not edit.

#include <cctype>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <string>
#include <utility>
#include <vector>

#include <arrow/api.h>
#include <arrow/io/file.h>
#include <parquet/arrow/reader.h>

#include "PcapIterator.hpp"
#include "Frame.hpp"
#include "cpp/advanced/nasdaq/nsmequities/totalview/itch/v5.0.2018/messages/session.hpp"
#include "parquet/wide/nasdaq/nsmequities/totalview/itch/v5.0.2018/Record.hpp"

namespace protocol = ::nasdaq::nsmequities::totalview::itch::v5_0_2018;

namespace {

int failures = 0;

// Corpus checkout the captures are read from.
std::string root() {
    const char* value = std::getenv("OMI_PACKETS_DIR");

    if (value == nullptr) {
        std::printf("FAIL: OMI_PACKETS_DIR is not set\n");
        std::exit(1);
    }

    return std::string{ value };
}

// The handler the session layer dispatches into: each message becomes one row.
struct Rows {
    protocol::parquet::wide::Table table{};

    protocol::seq_action on_transport_header(const protocol::packet_header&, const packet::Frame&) {
        return protocol::seq_action::process;
    }

    template <typename Message>
    void on_message(const Message& message, std::uint64_t, const protocol::packet_header&) {
        if constexpr (protocol::parquet::wide::writes<Message>) {
            table.append(message);
        }
    }
};

// The messages a written file holds, read back out of its message column.
std::vector<std::string> messages(const std::string& path) {
    std::vector<std::string> names;

    auto opened = arrow::io::ReadableFile::Open(path);

    if (!opened.ok()) { return names; }

    // Arrow 19 deprecated the status-returning reader, so the result-returning one is used
    auto opening = ::parquet::arrow::OpenFile(*opened, arrow::default_memory_pool());

    if (!opening.ok()) { return names; }

    auto reader = std::move(*opening);

    std::shared_ptr<arrow::Table> table;

    if (!reader->ReadTable(&table).ok()) { return names; }

    const auto column = table->GetColumnByName("message");

    if (column == nullptr) { return names; }

    for (int chunk = 0; chunk < column->num_chunks(); ++chunk) {
        const auto values = std::static_pointer_cast<arrow::StringArray>(column->chunk(chunk));

        for (std::int64_t row = 0; row < values->length(); ++row) {
            names.push_back(values->GetString(row));
        }
    }

    return names;
}

// A capture is named by a path; a file written for it is named by one name.
std::string filename(std::string_view value) {
    std::string out{ value };
    for (char& letter : out) { if (std::isalnum(static_cast<unsigned char>(letter)) == 0) { letter = 0x5f; } }
    return out;
}

// Write every message of a capture into a table, through a Parquet file, and back again. A capture
// named for one message must hold it; a capture of a whole session names none, and is held only to
// what it holds.
void expect(const char* expected, const char* relative) {
    std::vector<std::pair<std::string, std::int64_t>> sources;
    sources.emplace_back(root() + "/" + relative, 0);

    packet::PcapIterator captures(sources);
    const bool named = expected[0] != '\0';
    const std::string name = named ? expected : relative;
    Rows rows;

    while (captures.advance()) {
        const packet::Frame frame(captures.data(), captures.length());

        if (!frame.valid()) { continue; }

        protocol::process_segment(rows, frame.payload, frame.payload_len, 0, frame);
    }

    if (rows.table.rows() == 0) {
        std::printf("FAIL %s: no rows written from capture\n", name.c_str());
        ++failures;
        return;
    }

    const std::string path = std::string{ "parquet_wide_nasdaq_nsmequities_totalview_itch_v5.0.2018." } + filename(relative) + ".parquet";

    try {
        omi::parquet::wide::write(rows.table.finish(), path);
    } catch (const std::exception& error) {
        std::printf("FAIL %s: %s\n", name.c_str(), error.what());
        ++failures;
        return;
    }

    const auto read = messages(path);

    if (read.size() != static_cast<std::size_t>(rows.table.rows())) {
        std::printf("FAIL %s: wrote %lld rows, read back %zu\n", name.c_str(), static_cast<long long>(rows.table.rows()), read.size());
        ++failures;
        return;
    }

    std::size_t matched = 0;

    for (const auto& message : read) {
        if (named && message == name) { ++matched; }
    }

    if (named && matched == 0) {
        std::printf("FAIL %s: %zu rows read back, none of the expected message\n", name.c_str(), read.size());
        ++failures;
        return;
    }

    std::printf("ok   %s: %zu rows written and read back, %zu of them the expected message\n", name.c_str(), read.size(), matched);
}

}

int main() {
    std::printf("== Nasdaq.NsmEquities.TotalView.Itch.v5.0.2018 (wide parquet)\n");
    expect("", "nasdaq/NsmEquities/TotalView.v5.0.zst");
    return failures == 0 ? 0 : 1;
}
