// Nasdaq.NsmEquities.Aggregated.Itch.v2.0 messages as JSON, written through RapidJSON.
//
// Generated by CppGenerators — do not edit.

#pragma once

#include "cpp/advanced/nasdaq/nsmequities/aggregated/itch/v2.0/messages/Definitions.hpp"
#include "json/rapid/Values.hpp"

namespace nasdaq::nsmequities::aggregated::itch::v2_0::json::rapid {

namespace itch_aggregated = ::nasdaq::nsmequities::aggregated::itch::v2_0;

// The session dispatches every message the protocol has; these are the ones written, asked
// at compile time so a program instantiates nothing for the rest.
template <typename Message>
inline constexpr bool writes = true;

template <typename Writer>
void write(Writer& writer, const itch_aggregated::system_event_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("SystemEventMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("event_code");
    omi::json::rapid::text(writer, itch_aggregated::event_code::to_string(message.fields.event_code.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_aggregated::stock_directory_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("StockDirectoryMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("market_category");
    omi::json::rapid::text(writer, itch_aggregated::market_category::to_string(message.fields.market_category.get().value()));
    writer.Key("financial_status_indicator");
    omi::json::rapid::text(writer, itch_aggregated::financial_status_indicator::to_string(message.fields.financial_status_indicator.get().value()));
    writer.Key("round_lot_size");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.round_lot_size.get().value()));
    writer.Key("round_lots_only");
    omi::json::rapid::text(writer, itch_aggregated::round_lots_only::to_string(message.fields.round_lots_only.get().value()));
    writer.Key("issue_classification");
    omi::json::rapid::text(writer, itch_aggregated::issue_classification::to_string(message.fields.issue_classification.get().value()));
    writer.Key("issue_sub_type");
    omi::json::rapid::text(writer, message.fields.issue_sub_type.get_trimmed().value());
    writer.Key("authenticity");
    omi::json::rapid::text(writer, itch_aggregated::authenticity::to_string(message.fields.authenticity.get().value()));
    writer.Key("short_sale_threshold_indicator");
    omi::json::rapid::text(writer, itch_aggregated::short_sale_threshold_indicator::to_string(message.fields.short_sale_threshold_indicator.get().value()));
    writer.Key("ipo_flag");
    omi::json::rapid::text(writer, itch_aggregated::ipo_flag::to_string(message.fields.ipo_flag.get().value()));
    writer.Key("luld_reference_price_tier");
    omi::json::rapid::text(writer, itch_aggregated::luld_reference_price_tier::to_string(message.fields.luld_reference_price_tier.get().value()));
    writer.Key("etp_flag");
    omi::json::rapid::text(writer, itch_aggregated::etp_flag::to_string(message.fields.etp_flag.get().value()));
    writer.Key("etp_leverage_factor");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.etp_leverage_factor.get().value()));
    writer.Key("inverse_indicator");
    omi::json::rapid::text(writer, itch_aggregated::inverse_indicator::to_string(message.fields.inverse_indicator.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_aggregated::stock_trading_action_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("StockTradingActionMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("trading_state");
    omi::json::rapid::text(writer, itch_aggregated::trading_state::to_string(message.fields.trading_state.get().value()));
    writer.Key("reason");
    omi::json::rapid::text(writer, message.fields.reason.get_trimmed().value());
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_aggregated::reg_sho_short_sale_price_test_restricted_indicator_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("RegShoShortSalePriceTestRestrictedIndicatorMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("reg_sho_action");
    omi::json::rapid::text(writer, itch_aggregated::reg_sho_action::to_string(message.fields.reg_sho_action.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_aggregated::market_participant_position_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("MarketParticipantPositionMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("mpid");
    omi::json::rapid::text(writer, message.fields.mpid.get_trimmed().value());
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("primary_market_maker");
    omi::json::rapid::text(writer, itch_aggregated::primary_market_maker::to_string(message.fields.primary_market_maker.get().value()));
    writer.Key("market_maker_mode");
    omi::json::rapid::text(writer, itch_aggregated::market_maker_mode::to_string(message.fields.market_maker_mode.get().value()));
    writer.Key("market_participant_state");
    omi::json::rapid::text(writer, itch_aggregated::market_participant_state::to_string(message.fields.market_participant_state.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_aggregated::mwcb_decline_level_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("MwcbDeclineLevelMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("level_1");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.level_1.get().value()), itch_aggregated::level_1::exponent);
    writer.Key("level_2");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.level_2.get().value()), itch_aggregated::level_2::exponent);
    writer.Key("level_3");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.level_3.get().value()), itch_aggregated::level_3::exponent);
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_aggregated::mwcb_status_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("MwcbStatusMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("breached_level");
    omi::json::rapid::text(writer, itch_aggregated::breached_level::to_string(message.fields.breached_level.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_aggregated::ipo_quoting_period_update_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("IpoQuotingPeriodUpdateMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("ipo_quotation_release_time");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.ipo_quotation_release_time.get().value()));
    writer.Key("ipo_quotation_release_qualifier");
    omi::json::rapid::text(writer, itch_aggregated::ipo_quotation_release_qualifier::to_string(message.fields.ipo_quotation_release_qualifier.get().value()));
    writer.Key("ipo_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.ipo_price.get().value()), itch_aggregated::ipo_price::exponent);
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_aggregated::luld_auction_collar_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("LuldAuctionCollarMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("auction_collar_reference_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.auction_collar_reference_price.get().value()), itch_aggregated::auction_collar_reference_price::exponent);
    writer.Key("upper_auction_collar_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.upper_auction_collar_price.get().value()), itch_aggregated::upper_auction_collar_price::exponent);
    writer.Key("lower_auction_collar_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.lower_auction_collar_price.get().value()), itch_aggregated::lower_auction_collar_price::exponent);
    writer.Key("auction_collar_extension");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.auction_collar_extension.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_aggregated::operational_halt_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("OperationalHaltMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("market_code");
    omi::json::rapid::text(writer, itch_aggregated::market_code::to_string(message.fields.market_code.get().value()));
    writer.Key("operational_halt_action");
    omi::json::rapid::text(writer, itch_aggregated::operational_halt_action::to_string(message.fields.operational_halt_action.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_aggregated::price_level_update_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("PriceLevelUpdateMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("market_side");
    omi::json::rapid::text(writer, itch_aggregated::market_side::to_string(message.fields.market_side.get().value()));
    writer.Key("participant_shares");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.participant_shares.get().value()));
    writer.Key("aggregate_shares");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.aggregate_shares.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.price.get().value()), itch_aggregated::price::exponent);
    writer.Key("mpid");
    omi::json::rapid::text(writer, message.fields.mpid.get_trimmed().value());
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_aggregated::net_order_imbalance_indicator_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("NetOrderImbalanceIndicatorMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("paired_shares");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.paired_shares.get().value()));
    writer.Key("imbalance_shares");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.imbalance_shares.get().value()));
    writer.Key("imbalance_direction");
    omi::json::rapid::text(writer, itch_aggregated::imbalance_direction::to_string(message.fields.imbalance_direction.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("far_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.far_price.get().value()), itch_aggregated::far_price::exponent);
    writer.Key("near_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.near_price.get().value()), itch_aggregated::near_price::exponent);
    writer.Key("current_reference_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.current_reference_price.get().value()), itch_aggregated::current_reference_price::exponent);
    writer.Key("cross_type");
    omi::json::rapid::text(writer, itch_aggregated::cross_type::to_string(message.fields.cross_type.get().value()));
    writer.Key("price_variation_indicator");
    omi::json::rapid::text(writer, itch_aggregated::price_variation_indicator::to_string(message.fields.price_variation_indicator.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_aggregated::retail_price_improvement_indicator_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("RetailPriceImprovementIndicatorMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("interest_flag");
    omi::json::rapid::text(writer, itch_aggregated::interest_flag::to_string(message.fields.interest_flag.get().value()));
    writer.EndObject();
}

template <typename Writer>
void write(Writer& writer, const itch_aggregated::direct_listing_with_capital_raise_price_discovery_message& message) {
    writer.StartObject();
    writer.Key("message");
    writer.String("DirectListingWithCapitalRaisePriceDiscoveryMessage");
    writer.Key("tracking_number");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.tracking_number.get().value()));
    writer.Key("timestamp");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.timestamp.get().value()));
    writer.Key("stock");
    omi::json::rapid::text(writer, message.fields.stock.get_trimmed().value());
    writer.Key("open_eligibility_status");
    omi::json::rapid::text(writer, itch_aggregated::open_eligibility_status::to_string(message.fields.open_eligibility_status.get().value()));
    writer.Key("minimum_allowable_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.minimum_allowable_price.get().value()), itch_aggregated::minimum_allowable_price::exponent);
    writer.Key("maximum_allowable_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.maximum_allowable_price.get().value()), itch_aggregated::maximum_allowable_price::exponent);
    writer.Key("near_execution_price");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.near_execution_price.get().value()), itch_aggregated::near_execution_price::exponent);
    writer.Key("near_execution_time");
    writer.Uint64(static_cast<std::uint64_t>(message.fields.near_execution_time.get().value()));
    writer.Key("lower_price_range_collar");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.lower_price_range_collar.get().value()), itch_aggregated::lower_price_range_collar::exponent);
    writer.Key("upper_price_range_collar");
    omi::json::rapid::unsigned_decimal(writer, static_cast<std::uint64_t>(message.fields.upper_price_range_collar.get().value()), itch_aggregated::upper_price_range_collar::exponent);
    writer.EndObject();
}

}
